### ISSUE TITLE
Is it productive?

### ISSUE THREAD

**Issue by FlowerWrong** [zhuhaow/NEKit#1]
Hi! Guy. Is this library productive?
And there is a error when build this demo.

```
error: no such file or directory: NEKit/src/IPStack/DirectUDPStack.swift
```

**Comment by zhuhaow** [comment]
Not yet. But probably in two weeks.

This will be fix soon. Just have been too busy lately.

**Comment by hhdong** [comment]
@zhuhaow Still have lot of thing to do! I have  find some issues.... Waitting for you to solve them.

**Comment by zhuhaow** [comment]
Please use [Gitter](https://gitter.im/zhuhaow/NEKit?utm_source=share-link&utm_medium=link&utm_campaign=share-link) to talk about this.
