### ISSUE TITLE
关于Nekit修改传参问题

### ISSUE THREAD

**Issue by LuckyTyga** [zhuhaow/NEKit#101]
你好大佬， 我想讨教一下关于Nekit的用法。

我现在想在Nekit在与服务端连接时传出自定义的字符串，但是苦于没有找到连接方法

**Comment by zhuhaow** [comment]
改adapter

**Comment by LuckyTyga** [comment]
具体实现细节是在每请求一个网页时，发送一个验证数据但是服务端这边接受不到
下面是我添加的代码
        let helloData = Data(bytes: UnsafePointer<UInt8>(([0x55, 0x01, 0x00] as [UInt8])), count: 3)
        socket?.write(data: helloData)

上面的代码在AdapterSocket中的open func write(data: Data)方法里面添加的

拜托大神帮我解答一下吧  麻烦了

**Comment by zhuhaow** [comment]
看看HTTPAdapter和ShadowsocksAdapter怎么写的。

**Comment by LuckyTyga** [comment]
还是没效果

我在项目扩展PacketTunnelProvider startTunnel里是这么写的：
self.proxyServer = GCDHTTPProxyServer(address: IPAddress(fromString: "127.0.0.1"), port: NEKit.Port(port: UInt16(self.proxyPort)))
try! self.proxyServer.start()

我在ShadowsocksAdapter中的didConnectWith和write方法添加
 let helloData = Data(bytes: UnsafePointer<UInt8>(([0x55, 0x01, 0x00] as [UInt8])), count: 3)
        socket.write(data: helloData)

服务端仍然接受不到正确数据

**Comment by zhuhaow** [comment]
那服务器里接收到了什么呢？

**Comment by LuckyTyga** [comment]
一串byte和网址   这边通过0x55来验证协议  

error connecting to:  dial tcp: missing address
receive first byte authFlag: 234
协议错误


服务端一直返回错误

**Comment by zhuhaow** [comment]
我既不知道你代码怎么写的，也不知道服务器接收到了什么，还要帮你猜错在哪里，难度是不是略大了一点。

**Comment by LuckyTyga** [comment]
那我确认一下  如果请求google的话数据传出走的是ShadowsocksAdapter里的write方法是吗

**Comment by zhuhaow** [comment]
自定义的协议为什么会用到ShadowsocksAdapter呢？而且这和Google有什么关系。

**Comment by LuckyTyga** [comment]
不是自定义的协议啦 只是在您写的基础上加一个数据验证的步骤  和google没关系  我只是想知道请求的时候会走这ShadowsocksAdapter里吧

**Comment by zhuhaow** [comment]
我觉得你一定在某些地方有很大的误解。

走不走ShadowsocksAdapter又不是我决定的，那不是看你是怎么改的么

**Comment by LuckyTyga** [comment]
稍等  我再试下

**Comment by LuckyTyga** [comment]
这么晚打扰了  我使用的是你另外的知名项目Specht的PacketTunnelProvider.swift   当访问外网的时候这部分代码会让程序走ShadowsocksAdapter是吗

**Comment by zhuhaow** [comment]
大致明白你要干什么了，而且你也没看懂代码。
改一下StreamObfuscator里面的OriginStreamObfuscater.requestData
