### ISSUE TITLE
支持shadowsocks的udp转发了吗？

### ISSUE THREAD

**Issue by gaotong2055** [zhuhaow/NEKit#102]
我看到有UDPDirectStack，这个是直接转发udp的吗？

**Comment by zhuhaow** [comment]
是

**Comment by aishuidedabai** [comment]
那怎么转发udp

**Comment by leon1227** [comment]
The same question: how?
It seems important to enable udp over shadowsocks for console players like xboxone and ps4...

**Comment by RanchenY** [comment]
@gaotong2055 , @aishuidedabai, @leon1227
hi, 各位完成了udp转发了吗？

**Comment by YourMelody** [comment]
@RanchenY  朋友实现UDP转发了嘛？

**Comment by RanchenY** [comment]
后面没有使用nekit了.


发自我的 iPhone

**Comment by gopaulo** [comment]
Any updates on this end? Just point the general direction so we can track how to do it....

**Comment by zhuhaow** [comment]
For anyone want to know how to handle UDP packet, take a look at UDPDirectStack and how it is used in Specht. This shows everything you need to know.
