### ISSUE TITLE
下載後呈現coredata版本不正確的問題

### ISSUE THREAD

**Issue by yojjoyy1** [zhuhaow/NEKit#107]
你好，我想請問我下載下來後按照步驟
carthage update --no-use-binaries --platform mac,ios
然後build後報出coredata版本不對的問題
不曉得該如何修改
![2017-10-06 5 19 14](https://user-images.githubusercontent.com/24377605/31275200-ee262220-aa5b-11e7-8b44-5d9c9e6698e4.png)
感謝

**Comment by zhuhaow** [comment]
不知，但是可以多给点信息。

**Comment by yojjoyy1** [comment]
我下載你的NEKit後放到我的專案內
放到專案內後carthage update --no-use-binaries --platform mac,ios
結果就爆出這個問題了
詢問後是coredata版本不正確
但要解這個bug不曉得要如何更改版本，也不曉得跟改到幾
不知如何解
我想做ssr的vpn
小弟尋找了8個月找不到任何方式．．．
github上得下載下來都會有bug沒辦法跑～“～
請問大大知道我目前這個bug如何解嗎？

**Comment by zhuhaow** [comment]
完整log发一下

**Comment by yojjoyy1** [comment]
抱歉
今天早上build他的問題又改變了
我從新carthage update --no-use-binaries --platform mac,ios
變成沒有CocoaLumberjackSwift module
![2017-10-09 12 21 56](https://user-images.githubusercontent.com/24377605/31325197-01b553e4-ac80-11e7-9259-1b3e1108c869.png)

**Comment by zhuhaow** [comment]
Build完就有了

**Comment by zhuhaow** [comment]
自己的app要把framework自己加进去

**Comment by yojjoyy1** [comment]
有加入NEKit的framework
他在framework裡找不到CocoaLumberjackSwift module
![2017-10-09 12 42 45](https://user-images.githubusercontent.com/24377605/31325429-9fc63826-ac82-11e7-8cd4-ae6d62c7f153.png)

**Comment by yojjoyy1** [comment]
已解決
發現因為我先拉NEKit近專案在carthage update --no-use-binaries --platform mac,ios
他會跑，但carthae資源檔不在xcode內
要先carthage update --no-use-binaries --platform mac,ios在拉進去專案內
xcode才會繼承需要的依賴
只是問題又回到原點
這問題解決後
又跑出跟一開始的錯誤一樣了
coredata版本錯誤
這點一直解不了～“～
![2017-10-09 6 02 17](https://user-images.githubusercontent.com/24377605/31333291-113bbe78-acaf-11e7-9c5e-c14cbef468a5.png)

**Comment by zhuhaow** [comment]
你的build应当是在app的目录下面，怎么会在nekit的目录下面。

虽然不应该是这个问题。

**Comment by zhuhaow** [comment]
你的整个设置都不对，carthage根本不是你这么用的，你怎么会再用Xcode编译……

**Comment by yojjoyy1** [comment]
不好意思，小弟淺薄不太懂甚麼意思
carthage不是利用命令列進去打指令的方式去做的嗎?

**Comment by zhuhaow** [comment]
checkout 文件夹怎么会出现在xcode里……

**Comment by yojjoyy1** [comment]
不好意思不太懂
不是把專案拉到xocde內所有的資源都會吃進去了嗎？
還是該拉什麼檔才是正確的?

**Comment by zhuhaow** [comment]
看一下spechtlite怎么设置的，travis是怎么构建的

**Comment by yojjoyy1** [comment]
好的我去研究一下
謝謝指導
