### ISSUE TITLE
carthage update --no-use-binaries --platform mac,ios 报错

### ISSUE THREAD

**Issue by aishuidedabai** [zhuhaow/NEKit#108]
Task failed with exit code 65:
 /usr/bin/xcrun xcodebuild -workspace /Users/admin/Desktop/NEKit-master-2/Carthage/Checkouts/CocoaLumberjack/Framework/Lumberjack.xcworkspace -scheme CocoaLumberjackSwift-macOS -configuration Release -derivedDataPath /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/CocoaLumberjack/3.3.0 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build (launched in /Users/admin/Desktop/NEKit-master-2/Carthage/Checkouts/CocoaLumberjack)

**Comment by zhuhaow** [comment]
完整log发一下

**Comment by Sky891028** [comment]
xcode9 同样错误 降级到Xcode8.3.3 日志如下 我楼下发xcode9的日志 现在去编译
=== BUILD TARGET CocoaLumberjackSwift-iOS OF PROJECT Lumberjack WITH CONFIGURATION Release ===

Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **

**Comment by aishuidedabai** [comment]
# txb @ admin in ~/Desktop/NEKit-master on git:master x [11:40:04] C:1
$ carthage update --no-use-binaries --platform mac,ios
*** Fetching CocoaLumberjack
*** Fetching YamlSwift
*** Fetching tun2socks
*** Fetching CocoaAsyncSocket
*** Fetching Resolver
*** Checking out MMDB-Swift at "0.2.7"
*** Checking out Nimble at "v7.0.1"
*** Checking out Resolver at "0.1.3"
*** Checking out YamlSwift at "0cb5ccfb1f9e310de8b2b474fd955a42e3fe8c65"
*** Checking out CocoaAsyncSocket at "7.6.1"
*** Checking out tun2socks at "0.6.1"
*** Checking out Sodium-framework at "v1.0.10.1"
*** Checking out CocoaLumberjack at "3.3.0"
*** Checking out Quick at "v1.1.0"
*** xcodebuild output can be found in /var/folders/6h/503z_gqn3fx_c1tk9fxtxpvr0000gn/T/carthage-xcodebuild.yEyn21.log
*** Building scheme "Mac Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "CocoaLumberjackSwift-macOS" in Lumberjack.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/admin/Desktop/NEKit-master/Carthage/Checkouts/CocoaLumberjack/Framework/Lumberjack.xcworkspace -scheme CocoaLumberjackSwift-macOS -configuration Release -derivedDataPath /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/CocoaLumberjack/3.3.0 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/admin/Desktop/NEKit-master/Carthage/Checkouts/CocoaLumberjack)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/6h/503z_gqn3fx_c1tk9fxtxpvr0000gn/T/carthage-xcodebuild.yEyn21.log

**Comment by Sky891028** [comment]
xcode9问题如下 
** BUILD FAILED **
The following build commands failed:
	CompileSwift normal armv7
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by zhuhaow** [comment]
@aishuidedabai  Please check the xcodebuild log for more details: /var/folders/6h/503z_gqn3fx_c1tk9fxtxpvr0000gn/T/carthage-xcodebuild.yEyn21.log

**Comment by zhuhaow** [comment]
@Sky891028 和他一样，完整的log文件

**Comment by aishuidedabai** [comment]
/usr/bin/xcrun xcodebuild -project /Users/admin/Desktop/NEKit-master/Carthage/Checkouts/CocoaAsyncSocket/CocoaAsyncSocket.xcodeproj -scheme Mac\ Framework -configuration Release -derivedDataPath /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/CocoaAsyncSocket/7.6.1 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/admin/Desktop/NEKit-master/Carthage/Checkouts/CocoaAsyncSocket)2017-10-09 11:41:52.729 xcodebuild[20031:355137] [MT] DVTPlugInManager: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for KSImageNamed.ideplugin (com.ksuther.KSImageNamed) not present
2017-10-09 11:41:52.789 xcodebuild[20031:355137] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RTImageAssets.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-10-09 11:41:52.789 xcodebuild[20031:355137] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-10-09 11:41:52.789 xcodebuild[20031:355137] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/CocoaAsyncSocket/7.6.1

Build settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

=== BUILD TARGET Mac CocoaAsyncSocket OF PROJECT CocoaAsyncSocket WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

/usr/bin/xcrun xcodebuild -project /Users/admin/Desktop/NEKit-master/Carthage/Checkouts/CocoaAsyncSocket/CocoaAsyncSocket.xcodeproj -scheme iOS\ Framework -configuration Release -derivedDataPath /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/CocoaAsyncSocket/7.6.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/admin/Desktop/NEKit-master/Carthage/Checkouts/CocoaAsyncSocket)2017-10-09 11:41:57.229 xcodebuild[20058:355339] [MT] DVTPlugInManager: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for KSImageNamed.ideplugin (com.ksuther.KSImageNamed) not present
2017-10-09 11:41:57.289 xcodebuild[20058:355339] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RTImageAssets.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-10-09 11:41:57.289 xcodebuild[20058:355339] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-10-09 11:41:57.290 xcodebuild[20058:355339] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/CocoaAsyncSocket/7.6.1

Build settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos10.3

=== BUILD TARGET iOS CocoaAsyncSocket OF PROJECT CocoaAsyncSocket WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/CocoaAsyncSocket/7.6.1/Build/Intermediates/CocoaAsyncSocket.build/all-product-headers.yaml

** BUILD SUCCEEDED **

/usr/bin/xcrun xcodebuild -project /Users/admin/Desktop/NEKit-master/Carthage/Checkouts/CocoaAsyncSocket/CocoaAsyncSocket.xcodeproj -scheme iOS\ Framework -configuration Release -derivedDataPath /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/CocoaAsyncSocket/7.6.1 -sdk iphonesimulator -destination platform=iOS\ Simulator,id=794C56C8-02BD-4324-A082-E688F9498052 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/admin/Desktop/NEKit-master/Carthage/Checkouts/CocoaAsyncSocket)2017-10-09 11:41:59.163 xcodebuild[20081:355440] [MT] DVTPlugInManager: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for KSImageNamed.ideplugin (com.ksuther.KSImageNamed) not present
2017-10-09 11:41:59.227 xcodebuild[20081:355440] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RTImageAssets.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-10-09 11:41:59.227 xcodebuild[20081:355440] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-10-09 11:41:59.227 xcodebuild[20081:355440] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/CocoaAsyncSocket/7.6.1

Build settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphonesimulator10.3

=== BUILD TARGET iOS CocoaAsyncSocket OF PROJECT CocoaAsyncSocket WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/CocoaAsyncSocket/7.6.1/Build/Intermediates/CocoaAsyncSocket.build/all-product-headers.yaml

** BUILD SUCCEEDED **

/usr/bin/xcrun xcodebuild -workspace /Users/admin/Desktop/NEKit-master/Carthage/Checkouts/CocoaLumberjack/Framework/Lumberjack.xcworkspace -scheme CocoaLumberjackSwift-macOS -configuration Release -derivedDataPath /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/CocoaLumberjack/3.3.0 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/admin/Desktop/NEKit-master/Carthage/Checkouts/CocoaLumberjack)2017-10-09 11:43:22.005 xcodebuild[20762:362360] [MT] DVTPlugInManager: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for KSImageNamed.ideplugin (com.ksuther.KSImageNamed) not present
2017-10-09 11:43:22.369 xcodebuild[20762:362360] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RTImageAssets.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-10-09 11:43:22.370 xcodebuild[20762:362360] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-10-09 11:43:22.370 xcodebuild[20762:362360] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/CocoaLumberjack/3.3.0

Build settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO

=== BUILD TARGET CocoaLumberjack-macOS OF PROJECT Lumberjack WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/CocoaLumberjack/3.3.0/Build/Intermediates/Lumberjack.build/all-product-headers.yaml

=== BUILD TARGET CocoaLumberjackSwift-macOS OF PROJECT Lumberjack WITH CONFIGURATION Release ===

Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

**Comment by aishuidedabai** [comment]
@zhuhaow 大哥全部错误

**Comment by Sky891028** [comment]
完整的太长了  我发的是底部的错误  那我根上 
Xcode8.3.3 LOG-=====>和他的基本一致   底部可以对比一下

**Comment by Sky891028** [comment]
完整的太长了  我发的是底部的错误  
Xcode8.3.3 LOG-=====>和他的基本一致   底部可以对比一下

**Comment by zhuhaow** [comment]
试试看把这个清空 `/Users/admin/Library/Caches/org.carthage.CarthageKit`.

**Comment by zhuhaow** [comment]
用xcode 8.3.3能用swift3么？

**Comment by Sky891028** [comment]
xcode8.3.3就是swift3 xcode9是3.2和4

**Comment by aishuidedabai** [comment]
@zhuhaow  清空了Caches 重新 carthage update --no-use-binaries --platform mac,ios 遇到一样的问题

**Comment by Sky891028** [comment]
command line tools是用xcode8.3.3 还是xcode9

**Comment by aishuidedabai** [comment]
@Sky891028 不管用9还是8都是一样的错误

**Comment by Sky891028** [comment]
@zhuhaow  你用的哪个xcode构建的

**Comment by aishuidedabai** [comment]
@Sky891028 没解决，xcode8和9

**Comment by Sky891028** [comment]
查了一下资料 有指向是xcode共存导致的 我先卸载了xcode8.3.3正在编译 目前一切顺利 有结果 我立刻反馈

**Comment by Sky891028** [comment]
成功了 但是nekit好像不支持 swift3.2啊  我再去下个xcode8.3.3试试 你可以先卸载xcode9进行编译

**Comment by aishuidedabai** [comment]
@Sky891028  swift4，只要这个支持

**Comment by yojjoyy1** [comment]
剛解決了
下載下來的檔案先別裝到專案內，直接carthage update --no-use-binaries --platform mac,ios，跑完再裝進去
我之前事先把NEKit拉到專案內在carthage update --no-use-binaries --platform mac,ios
發現讀取不到Carthage這個資源資料夾
xcode資源內完全沒有這裡面的檔案
導致抓不到CocoaLumberjack模組
試試

**Comment by yojjoyy1** [comment]
結果這個解完又回到原本的問題了
....
Could not determine generated file paths for Core Data code generation: Error Domain=NSCocoaErrorDomain Code=260 "No current version for model at path /Users/cxicl/Desktop/VPN2/VPN2/NEKit/Carthage/Checkouts/CocoaLumberjack/Demos/CoreDataLogger/CoreDataLogger/CoreDataLogger.xcdatamodeld:" UserInfo={NSFilePath=/Users/cxicl/Desktop/VPN2/VPN2/NEKit/Carthage/Checkouts/CocoaLumberjack/Demos/CoreDataLogger/CoreDataLogger/CoreDataLogger.xcdatamodeld, NSLocalizedDescription=No current version for model at path /Users/cxicl/Desktop/VPN2/VPN2/NEKit/Carthage/Checkouts/CocoaLumberjack/Demos/CoreDataLogger/CoreDataLogger/CoreDataLogger.xcdatamodeld:}
coredata版本不正確，也不曉得在哪裡改，改多少..

**Comment by aishuidedabai** [comment]
@Sky891028 折腾半天，我发现造成的原因应该不是一两个

**Comment by Sky891028** [comment]
@zhuhaow 测试提交的时候 发现这两个问题  
ERROR ITMS-90057: "The bundle 'Payload/rabbit.app/Frameworks/NEKit.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString."
ERROR ITMS-90056: "This bundle Payload/rabbit.app/Frameworks/NEKit.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion."

**Comment by wangjinwei0806** [comment]
告诉你们一个简单的方法,把所以的第三方依赖全部下载下来,一个一个进行编译,想要那个版本就可以编译那个版本, swift4有测试,完全是没有问题..

**Comment by zhuhaow** [comment]
因为没有release，个人建议手动修改

**Comment by Sky891028** [comment]
是的 这里附上设置命令
defaults write "$PWD/Carthage/Build/iOS/NEKit.framework/Info.plist" CFBundleShortVersionString 0.2.0
defaults write "$PWD/Carthage/Build/iOS/NEKit.framework.dSYM/Contents/Info.plist" CFBundleShortVersionString 0.2.0
defaults write "$PWD/Carthage/Build/iOS/NEKit.framework/Info.plist" CFBundleVersion 10000
defaults write "$PWD/Carthage/Build/iOS/NEKit.framework.dSYM/Contents/Info.plist" CFBundleVersion 10000

**Comment by bingozb** [comment]
XCode 9，使用 `carthage update` 出现错误，完整 log 如下：

```shell
$ carthage update --no-use-binaries --platform ios
*** Fetching NEKit
*** Fetching Resolver
*** Fetching tun2socks
*** Fetching YamlSwift
*** Fetching CocoaLumberjack
*** Fetching CocoaAsyncSocket
*** Checking out CocoaAsyncSocket at "7.6.1"
*** Checking out CocoaLumberjack at "3.3.0"
*** Checking out MMDB-Swift at "0.2.7"
*** Checking out Resolver at "0.1.3"
*** Checking out Sodium-framework at "v1.0.10.1"
*** Checking out tun2socks at "0.6.1"
*** Checking out YamlSwift at "3.4.0"
*** Checking out NEKit at "0.12.2"
*** xcodebuild output can be found in /var/folders/9j/c_9mf_4913z66d00dw_lqwsm0000gn/T/carthage-xcodebuild.SUmwdd.log
*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
*** Building scheme "CocoaLumberjack-iOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjackSwift-iOS" in Lumberjack.xcworkspace
*** Building scheme "MMDB-iOS" in MMDB.xcodeproj
*** Building scheme "Resolver-iOS" in Resolver.xcodeproj
*** Building scheme "Sodium-iOS" in Sodium.xcodeproj
*** Building scheme "lwip-iOS" in tun2socks.xcodeproj
*** Building scheme "tun2socks-iOS" in tun2socks.xcodeproj
*** Building scheme "Yaml iOS" in Yaml.xcodeproj
*** Building scheme "NEKit-iOS" in NEKit.xcodeproj
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal armv7
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/IPStack/DNS/DNSSession.swift:48:96: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/IPStack/DNS/DNSSession.swift:48:114: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/Utils/UInt128.swift:417:20: warning: 'BitwiseOperations' is deprecated: Use FixedWidthInteger protocol instead
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/Utils/UInt128.swift:503:1: error: type 'UInt128' does not conform to protocol 'BinaryInteger'
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/Utils/UInt128.swift:503:1: error: type 'UInt128' does not conform to protocol 'Numeric'
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/Utils/UInt128.swift:355:21: error: binary operator '&+' cannot be applied to operands of type 'UInt128' and 'Int'
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/Utils/UInt128.swift:359:21: error: binary operator '&-' cannot be applied to operands of type 'UInt128' and 'Int'
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/Utils/UInt128.swift:370:25: error: binary operator '&-' cannot be applied to two 'UInt128' operands
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/Utils/UInt128.swift:372:21: error: binary operator '&+' cannot be applied to two 'UInt128' operands
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/Utils/UInt128.swift:629:69: error: binary operator '&+' cannot be applied to two 'UInt128' operands
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/RawSocket/NWTCPSocket.swift:145:74: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/RawSocket/NWTCPSocket.swift:145:74: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/RawSocket/NWTCPSocket.swift:169:74: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/RawSocket/NWTCPSocket.swift:169:74: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/RawSocket/NWTCPSocket.swift:284:78: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/RawSocket/NWTCPSocket.swift:284:78: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/ProxyServer/ProxyServer.swift:26:35: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/Utils/IPAddress.swift:157:69: error: binary operator '&+' cannot be applied to two 'UInt128' operands
/Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/src/Utils/IPAddress.swift:168:69: error: binary operator '&+' cannot be applied to two 'UInt128' operands
A shell task (/usr/bin/xcrun xcodebuild -project /Users/bingo/Desktop/iOS/DKVPN/Carthage/Checkouts/NEKit/NEKit.xcodeproj -scheme NEKit-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal armv7
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by bingozb** [comment]
@zhuhaow 完美解决，谢谢

**Comment by tonyair0408** [comment]
怎么解决啊？有没有方法可以私邮一个的

**Comment by Sky891028** [comment]
求确认 xcode9可以编译运行吗？ 如果可以 就去卸载833了

**Comment by yojjoyy1** [comment]
@Sky891028 xcode9可以我有編譯成功

**Comment by bingozb** [comment]
@Sky891028 可以，我已经卸载833了

**Comment by Sky891028** [comment]
@bingozb  好的 谢谢

**Comment by Sky891028** [comment]
git "https://github.com/zhuhaow/NEKit" "master"
依然是@bingozb的那个错误 
Cartfile是不是写错了？

**Comment by yojjoyy1** [comment]
@Sky891028 自己做一個Cartfile 裡面加入git "https://github.com/zhuhaow/NEKit" "master"再打指令下去應該就可以了

**Comment by zhuhaow** [comment]
如果还有问题，你们仔细理解一下Carthage究竟是怎么用的（`SpechtLite`），`NEKit` 需要使用`master`。

**Comment by yushengcao** [comment]
使用master编译出来的CFBundleShortVersionString不符合版本号规范（类似1.0.0），上传不了Appstore

**Comment by CoderJin** [comment]
你手动改一下不就行了

**Comment by wangxuewen** [comment]
各位大神帮忙看下这个，你们说的方法都试了，就是在 Building scheme "MMDB-iOS" in MMDB.xcodeproj 这个地方超时。

*** Building scheme "MMDB-iOS" in MMDB.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/admin/Desktop/APlusAccelerator_new/APlusAccelerator/Carthage/Checkouts/MMDB-Swift/MMDB.xcodeproj -scheme MMDB-iOS -configuration Release -derivedDataPath /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/MMDB-Swift/0.2.8 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/3m/jdmksrbj5h7406vfb8ltpp7r0000gn/T/MMDB-Swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/admin/Desktop/APlusAccelerator_new/APlusAccelerator/Carthage/Checkouts/MMDB-Swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/3m/jdmksrbj5h7406vfb8ltpp7r0000gn/T/carthage-xcodebuild.WNnGKp.log
administratordeMacBook-Pro:APlusAccelerator admin$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
