### ISSUE TITLE
请问能写一个UDP转发的例子吗，或者公开这部分源码

### ISSUE THREAD

**Issue by aishuidedabai** [zhuhaow/NEKit#109]
我用了potatso，但是发现udp很奇怪，怀疑是有缺陷的，但是nekit的转发做的很好，希望大哥告知思路，最好给出具体代码

**Comment by zhuhaow** [comment]
在IPStack里面捕获UDP转发。

**Comment by aishuidedabai** [comment]
@zhuhao 可以提供具体思路吗
