### ISSUE TITLE
ShadowsocksAdapterFactory初始化

### ISSUE THREAD

**Issue by bolee** [zhuhaow/NEKit#111]
初始化参数：
    public init(serverHost: String, serverPort: Int, protocolObfuscaterFactory: NEKit.ShadowsocksAdapter.ProtocolObfuscater.Factory, cryptorFactory: NEKit.ShadowsocksAdapter.CryptoStreamProcessor.Factory, streamObfuscaterFactory: NEKit.ShadowsocksAdapter.StreamObfuscater.Factory)
其中protocolObfuscaterFactory这Factory怎么用，看了源代码和文档(没有)，都没找到。

**Comment by bolee** [comment]
@mrkizy 好久了，目前没用这玩意了。建议你可以去看看NEKIT的官方开发相关资料。

**Comment by mrkizy** [comment]
@bolee 已经ok了，是api更新了。。。在issues找到别人写的
