### ISSUE TITLE
求解决支持WhatsAPP

### ISSUE THREAD

**Issue by aishuidedabai** [zhuhaow/NEKit#113]
WhatsAPP 的支持需要帮助

**Comment by zhuhaow** [comment]
需要UDP的支持，但是NEKit不会再更新支持

**Comment by CoderJin** [comment]
@aishuidedabai  你如何处理的 ？

**Comment by gopaulo** [comment]
@aishuidedabai Ditto here >> What did you do?

**Comment by CXTretar** [comment]
> 我已修改nekit解决，多谢

请问大神是如何解决的呢？

**Comment by Taher-17** [comment]
@aishuidedabai Please advise how you fixed this

**Comment by weqeo** [comment]
> 我已修改nekit解决，多谢

能请问下您怎么解决的吗？谢谢～

**Comment by gopaulo** [comment]
How did you do it @weqeo  ?

**Comment by weqeo** [comment]
@gopaulo I didn't resolve this question too, i'm looking for some solution ,when i found it ,i will @ u

**Comment by aishuidedabai** [comment]
https://t.me/NEKitGroup   在群里可以找到解决办法
