### ISSUE TITLE
xcode9提示No such module 'NEKit'

### ISSUE THREAD

**Issue by zhubinfeng** [zhuhaow/NEKit#115]
已经在项目中添加了NEKit.framework

**Comment by zhuhaow** [comment]
Extension和host app 都要加

**Comment by zhubinfeng** [comment]
你好，使用carthage update --no-use-binaries --platform ios命令后

*** Building scheme "Yaml iOS" in Yaml.xcodeproj

*** Building scheme "NEKit-iOS" in NEKit.xcodeproj

Build Failed

Task failed with exit code 65:

其他的库都可以编译通过，但是NETKit却报错了，您知道是什么原因吗？





在 2017-11-03 10:09:35，"zhuhaow" <notifications@github.com> 写道：
Extension和host app 都要加

**Comment by zhuhaow** [comment]
至少给出错误log吧
