### ISSUE TITLE
tun2socks error

### ISSUE THREAD

**Issue by itamaker** [zhuhaow/NEKit#118]
/Desktop/breakwa/Carthage/Build/iOS/tun2socks.framework/tun2socks compiled with older version of Swift language (3.0) than previous files (4.0) file /Desktop/breakwa/Carthage/Build/iOS/tun2socks.framework/tun2socks' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by itamaker** [comment]
error

**Comment by zhuhaow** [comment]
你是用 `carthage update --no-use-binaries --platform mac,ios` 安装的？
