### ISSUE TITLE
Please support swift 4.0.2 for Xcode 9.1

### ISSUE THREAD

**Issue by meigesir** [zhuhaow/NEKit#120]

**Comment by zhubinfeng** [comment]
@meigesir try         github "zhuhaow/NEKit" "master"

**Comment by meigesir** [comment]
@zhubinfeng Xcode 9 can，Xcode 9.1 can't

**Comment by zhubinfeng** [comment]
@meigesir I build success with Xcode. You can download .framework from "http://pan.baidu.com/s/1eR7jjUU".

**Comment by zhubinfeng** [comment]
@meigesir  I build success with Xcode9.1. You can download from "http://pan.baidu.com/s/1eR7jjUU".

**Comment by zhuhaow** [comment]
I should be fixed.

**Comment by meigesir** [comment]
@zhuhaow Yes, now can，tks。
