### ISSUE TITLE
Xcode9.1 报错

### ISSUE THREAD

**Issue by fandongtongxue** [zhuhaow/NEKit#122]
[carthage-xcodebuild.kcTQdI.log](https://github.com/zhuhaow/NEKit/files/1456022/carthage-xcodebuild.kcTQdI.log)
错误日志在上
*** Building scheme "NEKit-iOS" in NEKit.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/fandong/Documents/GitHub/SSDemo/Carthage/Checkouts/NEKit/NEKit.xcodeproj -scheme NEKit-iOS -configuration Release -derivedDataPath /Users/fandong/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/NEKit/0.12.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath ./ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/fandong/Documents/GitHub/SSDemo/Carthage/Checkouts/NEKit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/5f/xsc55grx3y1btd31ph_srxjm0000gn/T/carthage-xcodebuild.kcTQdI.log
localhost:SSDemo fandong$

**Comment by fandongtongxue** [comment]
希望作者可以看到

**Comment by zhuhaow** [comment]
Fixed

**Comment by zhaoyunyi** [comment]
更新到最新了么，目前还是这样

**Comment by zhuhaow** [comment]
用master
