### ISSUE TITLE
请教一个，那个一次性认证，跟 混淆，怎么设置？

### ISSUE THREAD

**Issue by tausha** [zhuhaow/NEKit#123]
请教一个，那个一次性认证，跟 混淆，怎么设置？
求个例子

**Comment by tausha** [comment]
那个混淆其实我不太明白
OriginProtocolObfuscater,HTTPProtocolObfuscater,TLSProtocolObfuscater，

//下面这样有什么用？
let obfuscater = ShadowsocksAdapter.ProtocolObfuscater.HTTPProtocolObfuscater.Factory(hosts:["intl.aliyun.com","cdn.aliyun.com"], customHeader:nil)

**Comment by pengxianhe** [comment]
let obfuscater = ShadowsocksAdapter.ProtocolObfuscater.HTTPProtocolObfuscater.Factory(hosts:["intl.aliyun.com","cdn.aliyun.com"], customHeader:nil)
这个的意思是混淆地址，把不合法的地址改为合法地址，例如上面改为了阿里云，我是这样理解的

**Comment by zhuhaow** [comment]
不完全是，可以参考原作者的设计，目的是混淆成http流量
