### ISSUE TITLE
iOS 11里面wifi/4g切换会导致GCDHTTPProxyServer不可用

### ISSUE THREAD

**Issue by Scholar01** [zhuhaow/NEKit#124]
测试了一夜发现的这个问题
分两次编译在4G WIFI下运行没问题
但是如果在WIFI下运行,关闭VPN,切换4G,打开VPN,会出现所有网页都没办法访问.反之亦然

**Comment by Scholar01** [comment]
代码就是很平常的ss过程.   创建VPN,所有http走127.0.0.1 然后VPN创建GCDHTTPProxyServer转发.

现在在ios 9 10 都正常,唯独iOS 11切换网络后,所有网页都不能访问

**Comment by Scholar01** [comment]
看了一下 我的问题类似他的  
https://github.com/zhuhaow/NEKit/issues/96

切换网络后,所有网络都无法访问了

代码也只是参考demo的代码

**Comment by Scholar01** [comment]
`var proxyServer: ProxyServer!

    override func startTunnel(options: [String : NSObject]?, completionHandler: @escaping (Error?) -> Void) {
         completionHandler(nil)
        
        
        //设置shadowsocks
        guard let conf = (protocolConfiguration as! NETunnelProviderProtocol).providerConfiguration else{
            NSLog("[ERROR] No ProtocolConfiguration Found")
            exit(EXIT_FAILURE)
        }


        let ss_adder = conf["ss_address"] as! String
        let ss_port = conf["ss_port"] as! Int
        let method = conf["ss_method"] as! String
        let password = conf["ss_password"] as!String




        let algorithm:CryptoAlgorithm

        switch method{
        case "aes-128-cfb":algorithm = .AES128CFB
        case "aes-192-cfb":algorithm = .AES192CFB
        case "aes-256-cfb":algorithm = .AES256CFB
        default:
            fatalError("Undefined algorithm!")
        }

        let obfuscater = ShadowsocksAdapter.ProtocolObfuscater.OriginProtocolObfuscater.Factory()
        let ssAdapterFactory = ShadowsocksAdapterFactory(serverHost: ss_adder, serverPort: ss_port, protocolObfuscaterFactory:obfuscater, cryptorFactory: ShadowsocksAdapter.CryptoStreamProcessor.Factory(password: password, algorithm: algorithm), streamObfuscaterFactory: ShadowsocksAdapter.StreamObfuscater.OriginStreamObfuscater.Factory())

        //定制规则
        var UserRules:[NEKit.Rule] = []
        let adapter:NEKit.AdapterFactory
        adapter = ssAdapterFactory
        var rule_array : [NEKit.DomainListRule.MatchCriterion] = []
        rule_array.append(DomainListRule.MatchCriterion.suffix("ip138.com"))
        UserRules.append(DomainListRule(adapterFactory: adapter, criteria: rule_array))

        // 创建规则

        let directAdapterFactory = DirectAdapterFactory()
        let chinaRule = CountryRule(countryCode: "CN", match: true, adapterFactory: directAdapterFactory)
        let unKnowLoc = CountryRule(countryCode: "--", match: true, adapterFactory: directAdapterFactory)
        let dnsFailRule = DNSFailRule(adapterFactory: ssAdapterFactory)

        let allRule = AllRule(adapterFactory: ssAdapterFactory)
        UserRules.append(contentsOf: [chinaRule,unKnowLoc,dnsFailRule,allRule])

        let manager = RuleManager(fromRules: UserRules, appendDirect: true)

        RuleManager.currentManager = manager
        let proxyPort =  9090
        

//       RawSocketFactory.TunnelProvider = self
        //打开手机VPN,连接到代理服务器
        let ipv4Settings = NEIPv4Settings(addresses: ["192.169.89.1"], subnetMasks: ["255.255.255.0"])
        let networkSettings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: "8.8.8.8")
        networkSettings.mtu = 1500
        networkSettings.ipv4Settings = ipv4Settings
        let proxySettings = NEProxySettings()
        proxySettings.httpEnabled = true
        proxySettings.httpServer = NEProxyServer(address: "127.0.0.1", port: proxyPort)
        proxySettings.httpsEnabled = true
        proxySettings.httpsServer = NEProxyServer(address: "127.0.0.1", port: proxyPort)
        proxySettings.excludeSimpleHostnames = true
        // This will match all domains
        proxySettings.matchDomains = [""]
        networkSettings.proxySettings = proxySettings
       
        setTunnelNetworkSettings(networkSettings) {
            error in
            guard error == nil else {
                completionHandler(error)
                return
            }
            
            //打开代理服务器
           
            self.proxyServer = GCDHTTPProxyServer(address: IPAddress(fromString: "127.0.0.1"), port: NEKit.Port(port: UInt16(proxyPort)))
            try? self.proxyServer.start()
        
            completionHandler(nil)
          
            
        }
        
    }
    
    
    override func stopTunnel(with reason: NEProviderStopReason,
                             completionHandler: @escaping () -> Void){
        self.proxyServer.stop()
        NSLog("proxyServer stop")
        completionHandler()
        exit(EXIT_SUCCESS)
    }`

**Comment by Scholar01** [comment]
试了3台ios11手机 100%出现这个问题.

**Comment by Scholar01** [comment]
safari无法打开网页,因为已丢失网络连接

**Comment by Scholar01** [comment]
@zhuhaow

**Comment by zhuhaow** [comment]
发我一个demo app

**Comment by Scholar01** [comment]
@zhuhaow 发到哪里?

**Comment by Scholar01** [comment]
@zhuhaow 发到哪里?

**Comment by zhuhaow** [comment]
随意任何方式联系，发邮件，telegram都可以

**Comment by datoujiejie** [comment]
重新生成一下profile

**Comment by Scholar000** [comment]
@datoujiejie

请问有联系方式吗 我不太理解

**Comment by Scholar01** [comment]
@zhuhaow
我没找到您的邮箱..
能否留一下..
是在谢谢

please

**Comment by zhuhaow** [comment]
试试看不要自己退出

~~exit(EXIT_SUCCESS)~~

**Comment by zhuhaow** [comment]
找不到那你就留你的吧……

**Comment by Scholar01** [comment]
@zhuhaow 
962888866@qq.com

**Comment by jzfjay** [comment]
这个问题解决了么？ 我这边也测试多次发现这个问题

**Comment by zhuhaow** [comment]
Reopen if the issue persists.

**Comment by wangedoo** [comment]
@zhuhaow 你好，我这里也发现这个问题 iOS 11里面wifi/4g切换会导致浏览器里无法访问网页了，这个问题解决了吗 ？？？

**Comment by wangedoo** [comment]
自己写的demo在一个网络状态（4G/wifi）然后数据都是可以成功的，然后切换到另一个网络状态，浏览器的请求都是失败

**Comment by wangedoo** [comment]
Safari浏览器打不开该网页，因为已丢失网络连接

**Comment by arvincong** [comment]
hi wifi 切换到4g时，原来使用vpn 打开的网页不能访问了。但是切换网络应该没有影响才对。能帮忙分析下补。 swift4.1

**Comment by AlfredCN** [comment]
hi wifi 切换到4g时，原来使用vpn 打开的网页不能访问了，并且重新打开也连不上了，iOS 11上出现的，iOS10 没有问题，是iOS11 系统的bug 吗？

**Comment by jzfjay** [comment]
不是 iOS11 系统的bug,   你查看下你的APP是否允许访问 网络（4G/wifi）

2018-06-05 23:28 GMT+08:00 AlfredCN <notifications@github.com>:

**Comment by hair-man** [comment]
想问一下 最终这个是怎么解决的

**Comment by LEEZHO** [comment]
各位,我現在是 vpn 連接成功 但是ip 地址還是沒有改變 。是什麼原因呢 有朋友遇到嗎

**Comment by CXTretar** [comment]
> 想问一下 最终这个是怎么解决的
我之前遇到了类似的问题，尝试了一下，在App开启了网络访问权限后，问题好像解决了，你可以在Info.plist中设置网络访问权限，或者在设置中手动打开试试。

**Comment by veibei** [comment]
这个问题有最终的结论吗？
