### ISSUE TITLE
Will NEKit support chacha20-ietf-poly1305?

### ISSUE THREAD

**Issue by kingname** [zhuhaow/NEKit#127]
I have noticed that the supported protocols in document of NEKit do not contain `chacha20-ietf-poly1305`. Does this protocol standard or not, and will you support it?

**Comment by zhuhaow** [comment]
To be precise, chacha20-ietf-poly1305 is an authenticated encryption construction. What you really want is Shadowsocks over chacha20-ietf-poly1305, I guess. 

I'll keep the support for chacha20-ietf-poly1305 but there will be no support for Shadowsocks.

**Comment by kingname** [comment]
Yes, I'd like Shadowsocks over chacha20-ietf-poly1305. As you will not support it for Shadowsocks, can you give me some document so that I can integrate it to SS by myself?

**Comment by zhuhaow** [comment]
Just notice you are asking in NEKit repo.

NEKit does not provide swift method for chacha20-ietf-poly1305, but libsodium is provided as a carthage dependency.

As for Shadowsocks, https://shadowsocks.org/en/spec/AEAD-Ciphers.html and https://shadowsocks.org/en/spec/Protocol.html

**Comment by kingname** [comment]
Thanks for your reminding.
