### ISSUE TITLE
Can not build on Swift 4

### ISSUE THREAD

**Issue by starFelix** [zhuhaow/NEKit#129]
*** Skipped installing Resolver.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1) and the local version is 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38)."

**Comment by zhuhaow** [comment]
`carthage update --no-use-binaries --platform mac,ios`

**Comment by starFelix** [comment]
Unfortunately, it still had error when I run the update command.

NEKit/src/Utils/IPAddress.swift:157:69: error: binary operator '&+' cannot be applied to two 'UInt128' operands
            return IPAddress(ipv6InNetworkOrder: (address.asUInt128 &+ range).byteSwapped)

**Comment by zhuhaow** [comment]
Use master branch
