### ISSUE TITLE
fell in with  : unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by sails** [zhuhaow/NEKit#13]
**

> _Sep  7 10:26:30 Guangjiande-iPhone nesessionmanager[122] <Notice>: NESMVPNSession[- bj:064F7EE5-05B5-459D-B0E7-F6AC718CF799]: status changed to connected
> Sep  7 10:26:30 Guangjiande-iPhone assertiond[63] <Error>: assertion failed: 13G36: assertiond + 72572 [0B862A7D-6E8B-3778-AD17-C7694ECD5BCD]: 0x3
> Sep  7 10:26:30 Guangjiande-iPhone Unknown[63] <Error>:
> Sep  7 10:26:30 Guangjiande-iPhone PacketTunnel[1047] <Error>: fatal error: unexpectedly found nil while unwrapping an Optional value
> Sep  7 10:26:30 Guangjiande-iPhone nesessionmanager[122] <Notice>: NESMVPNSession[- bj:064F7EE5-05B5-459D-B0E7-F6AC718CF799]: status changed to disconnecting
> 
> Sep  7 10:26:45  NESMVPNSession: status changed to connected
> Sep  7 10:26:45 Guangjiande-iPhone assertiond[63] <Error>: assertion failed: 13G36: assertiond + 72572 [0B862A7D-6E8B-3778-AD17-C7694ECD5BCD]: 0x3
> Sep  7 10:26:45 Guangjiande-iPhone PacketTunnel[1048] <Notice>: Accepted a new socket from IP stack.
> Sep  7 10:26:45 Guangjiande-iPhone PacketTunnel[1048] <Error>: fatal error: unexpectedly found nil while unwrapping an Optional value_

**

**Comment by sails** [comment]
Sep  7 10:57:39 Guangjiande-iPhone ReportCrash[1160] <Error>: Exception Type:  EXC_BREAKPOINT (SIGTRAP)
       	Exception Codes: 0x0000000000000001, 0x0000000100a66588
       	Triggered by Thread:  5
Sep  7 10:57:39 Guangjiande-iPhone ReportCrash[1160] <Error>: Thread 0 name:  Dispatch queue: com.apple.main-thread
       	Thread 0:
       	0   libsystem_kernel.dylib             	0x0000000181070fd8 0x181070000 + 4056
       	1   libsystem_kernel.dylib             	0x0000000181070e54 0x181070000 + 3668
       	2   CoreFoundation                     	0x00000001814a8c60 0x1813c8000 + 920672
       	3   CoreFoundation                     	0x00000001814a6964 0x1813c8000 + 911716
       	4   CoreFoundation                     	0x00000001813d0c50 0x1813c8000 + 35920
       	5   Foundation                         	0x0000000181de0cfc 0x181dd4000 + 52476
       	6   Foundation                         	0x0000000181e36030 0x181dd4000 + 401456
       	7   libxpc.dylib                       	0x0000000181194c64 0x181184000 + 68708
       	8   libxpc.dylib                       	0x00000001811969dc 0x181184000 + 76252
       	9   Foundation                         	0x0000000181fb3d60 0x181dd4000 + 1965408
       	10  PlugInKit                          	0x00000001887fac48 0x1887ec000 + 60488
       	11  PlugInKit                          	0x00000001887fa8dc 0x1887ec000 + 59612
       	12  PlugInKit                          	0x00000001887fac6c 0x1887ec000 + 60524
       	13  libextension.dylib                 	0x0000000181dc6058 0x181db0000 + 90200
       	14  libdyld.dylib                      	0x0000000180f6e8b8 0x180f6c000 + 10424
Sep  7 10:57:39 Guangjiande-iPhone ReportCrash[1160] <Error>: Thread 1 name:  Dispatch queue: cocoa.lumberjack
       	Thread 1:
       	0   libsystem_kernel.dylib             	0x0000000181071014 0x181070000 + 4116
       	1   libdispatch.dylib                  	0x0000000180f4e8c4 0x180f3c000 + 75972
       	2   CocoaLumberjack                    	0x00000001004f3204 0x1004ec000 + 29188
       	3   CocoaLumberjack                    	0x00000001004f1ac4 0x1004ec000 + 23236
       	4   libdispatch.dylib                  	0x0000000180f3d4bc 0x180f3c000 + 5308
       	5   libdispatch.dylib                  	0x0000000180f3d47c 0x180f3c000 + 5244
       	6   libdispatch.dylib                  	0x0000000180f494c0 0x180f3c000 + 54464
       	7   libdispatch.dylib                  	0x0000000180f40f80 0x180f3c000 + 20352
       	8   libdispatch.dylib                  	0x0000000180f3d47c 0x180f3c000 + 5244
       	9   libdispatch.dylib                  	0x0000000180f4b914 0x180f3c000 + 63764
       	10  libdispatch.dylib                  	0x0000000180f4b0b0 0x180f3c000 + 61616
       	11  libsystem_pthread.dylib            	0x0000000181155470 0x181154000 + 5232
       	12  libsystem_pthread.dylib            	0x0000000181155020 0x181154000 + 4128
Sep  7 10:57:39 Guangjiande-iPhone ReportCrash[1160] <Error>: Thread 2 name:  Dispatch queue: com.apple.libdispatch-manager
       	Thread 2:
       	0   libsystem_kernel.dylib             	0x000000018108d4d8 0x181070000 + 120024
       	1   libdispatch.dylib                  	0x0000000180f507d8 0x180f3c000 + 83928
       	2   libdispatch.dylib                  	0x0000000180f3f648 0x180f3c000 + 13896
Sep  7 10:57:39 Guangjiande-iPhone ReportCrash[1160] <Error>: Thread 3:
       	0   libsystem_kernel.dylib             	0x000000018108cb48 0x181070000 + 117576
       	1   libsystem_pthread.dylib            	0x0000000181155530 0x181154000 + 5424
       	2   libsystem_pthread.dylib            	0x0000000181155020 0x181154000 + 4128
Sep  7 10:57:39 Guangjiande-iPhone ReportCrash[1160] <Error>: Thread 4:
       	0   libsystem_kernel.dylib             	0x000000018108cb48 0x181070000 + 117576
       	1   libsystem_pthread.dylib            	0x0000000181155530 0x181154000 + 5424
       	2   libsystem_pthread.dylib            	0x0000000181155020 0x181154000 + 4128
Sep  7 10:57:39 Guangjiande-iPhone ReportCrash[1160] <Error>: Thread 5 name:  Dispatch queue: tun2socks.IPStackQueue
       	Thread 5 Crashed:
       	0   libswiftCore.dylib                 	0x0000000100a66588 0x100928000 + 1303944
       	1   NEKit                              	0x0000000100181814 0x100164000 + 120852
       	2   NEKit                              	0x0000000100181a2c 0x100164000 + 121388
       	3   tun2socks                          	0x000000010076706c 0x100760000 + 28780
       	4   lwip                               	0x000000010062242c 0x100618000 + 42028
       	5   lwip                               	0x000000010061f624 0x100618000 + 30244
       	6   tun2socks                          	0x0000000100767204 0x100760000 + 29188
       	7   libdispatch.dylib                  	0x0000000180f3d4bc 0x180f3c000 + 5308
       	8   libdispatch.dylib                  	0x0000000180f3d47c 0x180f3c000 + 5244
       	9   libdispatch.dylib                  	0x0000000180f494c0 0x180f3c000 + 54464
       	10  libdispatch.dylib                  	0x0000000180f40f80 0x180f3c000 + 20352
       	11  libdispatch.dylib                  	0x0000000180f3d47c 0x180f3c000 + 5244
       	12  libdispatch.dylib                  	0x0000000180f4b914 0x180f3c000 + 63764
       	13  libdispatch.dylib                  	0x0000000180f4b0b0 0x180f3c000 + 61616
       	14  libsystem_pthread.dylib            	0x0000000181155470 0x181154000 + 5232
       	15  libsystem_pthread.dylib            	0x0000000181155020 0x181154000 + 4128
Sep  7 10:57:39 Guangjiande-iPhone ReportCrash[1160] <Error>: Thread 6:
       	0   libsystem_kernel.dylib             	0x000000018108cb48 0x181070000 + 117576
       	1   libsystem_pthread.dylib            	0x0000000181155530 0x181154000 + 5424
       	2   libsystem_pthread.dylib            	0x0000000181155020 0x181154000 + 4128
Sep  7 10:57:39 Guangjiande-iPhone ReportCrash[1160] <Error>: Thread 7:
       	0   libsystem_pthread.dylib            	0x000000018115501c 0x181154000 + 4124
Sep  7 10:57:39 Guangjiande-iPhone ReportCrash[1160] <Error>: Thread 8:
       	0   libsystem_kernel.dylib             	0x000000018108cb48 0x181070000 + 117576
       	1   libsystem_pthread.dylib            	0x0000000181155530 0x181154000 + 5424
       	2   libsystem_pthread.dylib            	0x0000000181155020 0x181154000 + 4128
Sep  7 10:57:39 Guangjiande-iPhone ReportCrash[1160] <Error>: Thread 5 crashed with ARM Thread State (64-bit):
       	    x0: 0x0000000100f10a00   x1: 0x000000018114e8f4   x2: 0x0000000134d40440   x3: 0x0000000000000008
       	    x4: 0x0000000000000000   x5: 0x0000000000000020   x6: 0x0000000000000000   x7: 0x0000000000000fa0
       	    x8: 0x0000000100f10a08   x9: 0x0000000000001000  x10: 0x0000000134d44000  x11: 0x0000000000000fff
       	   x12: 0x0000000134d40000  x13: 0x0000000000003fff  x14: 0xffffffffffffc000  x15: 0x0000000000003fff
       	   x16: 0x00000001810b8168  x17: 0x0000000100b28040  x18: 0x0000000000000000  x19: 0x0000000134d31f60
       	   x20: 0x0000000134e3dc40  x21: 0x0000000134d31d30  x22: 0x0000000100227160  x23: 0x000000010076d8b0
       	   x24: 0x0000000134d31ff0  x25: 0x00000001001819e4  x26: 0x0000000100628000  x27: 0x00000001006281f8
       	   x28: 0x0000000100628000  fp: 0x000000016e246a90   lr: 0x0000000100a66588
       	    sp: 0x000000016e246a80   pc: 0x0000000100a66588 cpsr: 0x20000000

**Comment by zhuhaow** [comment]
This does not seems like from the latest NEKit.
Are you using the latest tun2socks library?

**Comment by sails** [comment]
am I using  tun2socks 0.3.0
![image](https://cloud.githubusercontent.com/assets/1535004/18306634/43bc38e6-751f-11e6-904d-15b839fc2ec8.png)

**Comment by zhuhaow** [comment]
Emm, try to use dSYM file to get a more detailed stack information.

2016年9月7日 +0800 17:20 sails <notifications@github.com>，写道：

**Comment by sails** [comment]
I can't get crash file in PacketTunnel process:
`Sep 12 10:47:06 Guangjiande-iPhone ReportCrash[3778] <Warning>: Report of type '109(109_PacketTunnel)' not saved because the limit of 25 logs has been reached
Sep 12 10:47:06 Guangjiande-iPhone ReportCrash[3778] <Error>: Notice: This report is abbreviated for syslog inclusion because it could not be saved to disk.
       	Symbolication may be possible by manually cleaning up and including the Binary Image section of a full report from this same device -- good luck!
Sep 12 10:47:06 Guangjiande-iPhone ReportCrash[3778] <Error>: Process:             PacketTunnel [3776]
       	Path:                /private/var/containers/Bundle/Application/31D2FE00-1DD5-4938-95A3-6E8D292B076F/NetKit.app/PlugIns/PacketTunnel.appex/PacketTunnel
       	OS Version:          iOS 9.3.5 (13G36)
Sep 12 10:47:06 Guangjiande-iPhone ReportCrash[3778] <Error>: Exception Type:  EXC_BREAKPOINT (SIGTRAP)
       	Exception Codes: 0x0000000000000001, 0x0000000100a7e588
       	Triggered by Thread:  4
Sep 12 10:47:06 Guangjiande-iPhone ReportCrash[3778] <Error>: Thread 0 name:  Dispatch queue: com.apple.main-thread`

![image](https://cloud.githubusercontent.com/assets/1535004/18423894/08b8ec42-78dc-11e6-81ed-5bb474af5ea9.png)

so i don't know slide address in arm64:
![image](https://cloud.githubusercontent.com/assets/1535004/18423909/32e90c04-78dc-11e6-9c8e-336bc4ac68b8.png)

**Comment by zhuhaow** [comment]
Well, I know there are some bugs in tun2socks, I just don't know where. 
I have fixed some potential bugs, it helped, the crash reduced significantly.
I think there is something wrong in my modifications of lwip, but I do not know where and do not have time to look into it now. 

So my recommendation is (as of now): if the crashing frequency is acceptable, then just ignore it, if not, then do not process IP packets.

**Comment by sails** [comment]
I don't know How can I get  detailed stack information，can you get me some advice

**Comment by zhuhaow** [comment]
I think it is because lwip tries to dereference some nil pointer, because that is what happens when I test it. So I think there is something wrong in my modifications of lwip. If you want to, you can look at the modifications by searching tun2socks in the source code, everything changed should be commented with "tun2socks".

As of how to get a stack information, I do not know. I'm not an iOS developer or a macOS developer. But it seems like you need to clean up the existing logs first. Maybe by connecting to you macbook and use "Devices" to delete them.

**Comment by sails** [comment]
This is my code, often problems occur, I hope useful to analyze the reasons for you
`print("start setting\n")
        guard let ssAdapterFactory = ShadowsocksAdapterFactory(serverHost: address!, serverPort: port, encryptAlgorithm: encryptAlgorithm, password: password) else {
            NSLog("ssAdapterFactory is nil, address:%@, port:%d, encryptAlgorithm:%@, password:%@",
                  address!, port, encryptAlgorithm, password)
            completionHandler(startError)
            return
        }
        

        let allRule = AllRule(adapterFactory: ssAdapterFactory)

        // Create rule manager, rules will be matched in order.
        let manager = RuleManager(fromRules: [allRule], appendDirect: true)

        // Set this manager as the active manager
        RuleManager.currentManager = manager

        RawSocketFactory.TunnelProvider = self

        let networkSettings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: address!)

 
        let ipv4Settings = NEIPv4Settings(addresses: ["192.169.89.1"], subnetMasks: ["255.255.255.0"])
        ipv4Settings.includedRoutes = [NEIPv4Route.defaultRoute()]
        ipv4Settings.excludedRoutes = [
            NEIPv4Route(destinationAddress: "10.0.0.0", subnetMask: "255.0.0.0"),
            NEIPv4Route(destinationAddress: "100.64.0.0", subnetMask: "255.192.0.0"),
            NEIPv4Route(destinationAddress: "127.0.0.0", subnetMask: "255.0.0.0"),
            NEIPv4Route(destinationAddress: "169.254.0.0", subnetMask: "255.255.0.0"),
            NEIPv4Route(destinationAddress: "172.16.0.0", subnetMask: "255.240.0.0"),
            NEIPv4Route(destinationAddress: "192.168.0.0", subnetMask: "255.255.0.0"),
        ]
        networkSettings.IPv4Settings = ipv4Settings
        
        let proxySettings = NEProxySettings()
        proxySettings.HTTPEnabled = true
        proxySettings.HTTPServer = NEProxyServer(address: "127.0.0.1", port: proxyPort)
        proxySettings.HTTPSEnabled = true
        proxySettings.HTTPSServer = NEProxyServer(address: "127.0.0.1", port: proxyPort)
        proxySettings.excludeSimpleHostnames = true
        // This will match all domains
        proxySettings.matchDomains = [""]
        networkSettings.proxySettings = proxySettings



        
        // the 198.18.0.0/15 is reserved for benchmark.
        let DNSSettings = NEDNSSettings(servers: ["198.18.0.1"])
        DNSSettings.matchDomains = [""]
        DNSSettings.matchDomainsNoSearch = false
        networkSettings.DNSSettings = DNSSettings

        interface = TUNInterface(packetFlow: packetFlow)
        let fakeIPPool = IPv4Pool(start: IPv4Address(fromString: "172.169.1.0")!, end: IPv4Address(fromString: "172.169.255.0")!)
        let dnsServer = DNSServer(address: IPv4Address(fromString: "172.169.0.1")!, port: Port(port: 53), fakeIPPool: fakeIPPool)
        
        let resolver = UDPDNSResolver(address: IPv4Address(fromString: "114.114.114.114")!, port: Port(port: 53))
        dnsServer.registerResolver(resolver)
        interface?.registerStack(dnsServer)
        DNSServer.currentServer = dnsServer
        
        let udpStack = UDPDirectStack()
        interface?.registerStack(udpStack)
        
        let tcpStack = TCPStack.stack
        interface?.registerStack(tcpStack)
        
        setTunnelNetworkSettings(networkSettings) {
            error in
            guard error == nil else {
                NSLog("Encountered an error setting up the network: \(error)")
                completionHandler(error)
                return
            }

            NSLog("start proxy server")
            self.proxyServer = GCDHTTPProxyServer(address: IPv4Address(fromString: "127.0.0.1"), port: Port(port: UInt16(self.proxyPort)))
            try! self.proxyServer?.start()
            
            completionHandler(nil)
            
            NSLog("start interface")
            self.interface?.start()
        }`

**Comment by zhuhaow** [comment]
It seems alright, there is just something wrong in tun2socks.
