### ISSUE TITLE
Can you update the code for introducing?

### ISSUE THREAD

**Issue by starFelix** [zhuhaow/NEKit#130]
I found the code in  READ.ME is out of date. Some class was renamed such as ListRule and some class' function was changed such as ShadowsocksAdapterFactory.
Because there are so few of documents about this project, the code for introducing is very important for me or somone else who didn't know this project very much.

**Comment by zhuhaow** [comment]
I design this framework as something to help avoid reinventing the wheel, not as some black box just works.

You can take a look at the doc site here, https://zhuhaow.github.io/NEKit <https://zhuhaow.github.io/NEKit>. I think it should be up to date.

Sorry for any inconvenience. I updated the readme to point that out.

**Comment by starFelix** [comment]
I know what you mean, but I think it's necessary for providing some code so that others can understand this project easier.
