### ISSUE TITLE
编译出来的.ipa文件很大，其中Frameworks就50多M

### ISSUE THREAD

**Issue by NasserGo** [zhuhaow/NEKit#133]
请问这是什么问题？

其中NEKit.framework就是19.1M， 请问该如何瘦身？

谢谢。

**Comment by zhuhaow** [comment]
把所有framework改成静态的lib

**Comment by NasserGo** [comment]
对这方面不是很了解， 可以多给点提示吗？

**Comment by zhuhaow** [comment]
http://lmgtfy.com/?q=xcode+static+library
