### ISSUE TITLE
DebugTunnelObserver: Observer<TunnelEvent>  not work

### ISSUE THREAD

**Issue by Sky891028** [zhuhaow/NEKit#137]
这个observer不工作 请问是什么原因 使用debugObserver和自己重写 都没有signal回调

**Comment by zhuhaow** [comment]
factory注册了么

**Comment by Sky891028** [comment]
注册了 只有这个回调没有日志
这是注册方法  
        ObserverFactory.currentFactory = SSObserverFactory() //
使用DebugObserverFactory() 也是一样的 AdapterSocketEvent有 tunnelEvent没有

**Comment by Sky891028** [comment]
override func getObserverForTunnel(_ tunnel: Tunnel) -> Observer<TunnelEvent>
    {
        return tunnelObser()
    }
    class tunnelObser: Observer<TunnelEvent> {
        var traffic = 0
        override open func signal(_ event: TunnelEvent) {
            switch event {
..........
这样写是没有问题的吧

**Comment by zhuhaow** [comment]
看起来没啥问题，解决了么

**Comment by Sky891028** [comment]
@zhuhaow  没有上报 这是我的邮箱 sky891028@gmail.com  我把重写的observerFactory贴下面 

`import Cocoa
import NEKit
import CocoaLumberjackSwift

class SSObserverFactory: ObserverFactory {
    
    override func getObserverForTunnel(_ tunnel: Tunnel) -> Observer<TunnelEvent>
    {
        return tunnelObser()
    }
    class tunnelObser: Observer<TunnelEvent> {
        var traffic = 0
        override open func signal(_ event: TunnelEvent) {
            switch event {
            case let .proxySocketReadData(data, from: socket, on: tunnel):
                DDLogInfo("Tunnel \(tunnel) received \(data.count) bytes from proxy socket \(socket).")
            case let .proxySocketWroteData(data, by: socket, on: tunnel):
                if let data = data {
                    DDLogInfo("Proxy socket \(socket) sent \(data.count) bytes data from Tunnel \(tunnel).")
                } else {
                    DDLogInfo("Proxy socket \(socket) sent data from Tunnel \(tunnel).")
                }
            case let .adapterSocketReadData(data, from: socket, on: tunnel):
                DDLogInfo("Tunnel \(tunnel) received \(data.count) bytes from adapter socket \(socket).")
            case let .adapterSocketWroteData(data, by: socket, on: tunnel):
                if let data = data {
                    DDLogInfo("Adatper socket \(socket) sent \(data.count) bytes data from Tunnel \(tunnel).")
                } else {
                    DDLogInfo("Adapter socket \(socket) sent data from Tunnel \(tunnel).")
                }
            
            default:
                break
            }
        }
    }
}

`

**Comment by zhuhaow** [comment]
你断点跟踪一下

**Comment by DullDevil** [comment]
在 Tunnel.swift 中的 observer 用 weak 修饰了

**Comment by zhuhaow** [comment]
......

Thanks. Fixed.
