### ISSUE TITLE
和shadowsocks的关系？

### ISSUE THREAD

**Issue by RanchenY** [zhuhaow/NEKit#141]
您好，
想问一下，NEKit和shadowsocks的关系是怎样的呢？
谢谢

**Comment by zhuhaow** [comment]
简单的来说，NEKit 和 SS 没有任何关系。

NEKit 是一个帮助创建代理应用的库，NEKit 的目标是可以简单的支持任何的代理协议。当前的 NEKit 内置了 SS 的协议支持，仅此而已。

不过在 libnekit 中将来会完全移除所有的非 RFC 协议（现在的 libnekit 内置了 SS 的支持）。

**Comment by rcy1122** [comment]
那如果是基于ss做网络代理，是不是可以直接用NSKit代替呢？

**Comment by zhuhaow** [comment]
代替什么呢？

**Comment by rcy1122** [comment]
代替ss 实现某些网络请求代理。
比如：用NEKit 实现tun2socks抓包，然后在本地建立一个local（就像ss-local一样），然后和server端连接。对网络这一块还不是很了解，说的可能不是很明白，见谅。。

**Comment by zhuhaow** [comment]
可以是可以。

但是我真的建议大家做任何事情还是要先有基础知识。

**Comment by rcy1122** [comment]
好的，继续学习NE
谢谢
