### ISSUE TITLE
Confusing about the declaration

### ISSUE THREAD

**Issue by tomisacat** [zhuhaow/NEKit#142]
In README you declare:

>NEKit does not depend on Network Extension framework. You can use NEKit without Network Extension entitlement to build a rule based proxy in a few lines.

but actually Network Extension Framework is used in this project, such as in `/src/RawSocket/NWTCPSocket.swift`, is the README outdated or something I missed?

Appreciate your great work : )

**Comment by zhuhaow** [comment]
Well. The thing is, network extension permission is only checked when the specific method is called. So if you don’t call it, you can just assume that network extension is not used, though it is linked.

**Comment by tomisacat** [comment]
well, that makes sense. thanks : )
