### ISSUE TITLE
Some question about encrypt method.

### ISSUE THREAD

**Issue by chinsyo** [zhuhaow/NEKit#143]
```
Every iOS device has a dedicated AES-256 crypto engine built into the
DMA path between the flash storage and main system memory, making file
encryption highly efficient. On A9 or later A-series processors, the flash
storage subsystem is on an isolated bus that is only granted access to
memory containing user data via the DMA crypto engine.
```
```
Apart from the UID and GID, all other cryptographic keys are created by the
system’s random number generator (RNG) using an algorithm based on
CTR_DRBG. System entropy is generated from timing variations during boot,
and additionally from interrupt timing once the device has booted. Keys
generated inside the Secure Enclave use its true hardware random number
generator based on multiple ring oscillators post processed with CTR_DRBG.
```
Referenced: [Apple Docs](https://www.apple.com/business/docs/iOS_Security_Guide.pdf) page12

So does it means iPhone use A9 or later support hardware-accelerated AES Encryption?
And what encryption mode it support, GCM, CTR or what?
If it's GCM, will NEKit support GCM mode native?

**Comment by zhuhaow** [comment]
NEKit use encryption provided by Apple whenever possible.

You can take a look at `src/Socket/AdapterSocket/Shadowsocks/CryptoStreamProcessor.swift` to check these algorithm are provided by which library.

**Comment by zhuhaow** [comment]
This [header](https://opensource.apple.com/source/CommonCrypto/CommonCrypto-36064/CommonCrypto/CommonCryptor.h) may also help.
