### ISSUE TITLE
Where can I record every request under proxy?

### ISSUE THREAD

**Issue by chinsyo** [zhuhaow/NEKit#144]
I have add DDLog with ASLLogger and TTYLogger with verbose level. But no logs appear on my xcode console.

Or how can I set symbolic breakpoints inside NEKit on - [GCDProxyServer newSocketQueueForConnectionFromAddress: onSock:] .It seems it didnt work even if i step by step follow stackoverflow.

I want to implement a feature that record every request under proxy.

**Comment by chinsyo** [comment]
```swift
override func startTunnel(options: [String : NSObject]?, completionHandler: @escaping (Error?) -> Void) {
        DDLog.removeAllLoggers()
        DDLog.add(DDASLLogger.sharedInstance, with: DDLogLevel.info)
        DDLog.add(DDTTYLogger.sharedInstance, with: DDLogLevel.verbose)
        ObserverFactory.currentFactory = DebugObserverFactory()
        DDLogWarn("start tunnel")
```
after the tunnel start running, I can't see  "start tunnel", and debug observer logs.

**Comment by zhuhaow** [comment]
Extension runs in a different process. You should be able to find log of `DDASLLogger` in Console.app.
