### ISSUE TITLE
How can I share wifi with other smartphones while nekit running.

### ISSUE THREAD

**Issue by chinsyo** [zhuhaow/NEKit#146]
P1: Phone with nekit running.
P2: Phone needs proxy.

I have try out many times.

1. Turn on p1 hotspot and then p2 join the network, didn't work.
2. P1 and p2 join the same wifi, set p2 proxy in wifi settings to p1's ip address (172.16.x.x for me), port of proxy server(9090 for me), didn't work.
3. Same as [2], but replace p1's ip address to NEIPv4Settings address first (and only, 192.169.89.1 for me)

I dont set exceptionList, set [""] to matchDomains. And the configuration rule has set 
```
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
      - 127.0.0.0/8
      - 224.0.0.0/8
      - 169.254.0.0/16
      localhost
```
with direct.

**Comment by chinsyo** [comment]
All of workaround didn't work for me. Plz help me.

**Comment by zhuhaow** [comment]
For obvious security reason, hotspot on iPhone is isolated. https://apple.stackexchange.com/questions/194842/iphone-is-the-hotspot-isolated-can-you-see-other-devices

So in you case, there is no workaround.

**Comment by chinsyo** [comment]
So is there any way to implement function like surge 'wifi-access' ?

**Comment by chinsyo** [comment]
@zhuhaow

**Comment by zhuhaow** [comment]
A server listen on 0.0.0.0

**Comment by chinsyo** [comment]
@zhuhaow It seems that this solution didn't work for me, and it will cause proxy error what need to reset the system networking settings.

Is there any demo project?

**Comment by zhuhaow** [comment]
Ehh, how can setting a proxy cause you have to reset system settings?

How did you do it? Didn't you just go to the wifi setting and set proxy to you other phone's (intranet) ip address?

**Comment by chinsyo** [comment]
@zhuhaow After running a GCDHTTPProxyServer with 0.0.0.0:9090, and setting proxySettings.httpServer ,proxySettings.httpsServer, remove direct rule below
```
  #内网IP不走代理
  - type: iplist
    adapter: direct
    criteria:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
      - 127.0.0.0/8
      - 224.0.0.0/8
      - 169.254.0.0/16
```
After that. The phone running nekit cant open local server(created by python3 -m http.server), baidu.com and google.com. The same as another phone.

Revert the project to 127.0.0.1:9090 and add the rule,still cant open local server, baidu and google.

Reset system settings and reboot the phone, Open website is OK.

**Comment by chinsyo** [comment]
RemoveProfile and uninstall the app didn't work, so I reset system settings.

**Comment by zhuhaow** [comment]
I don't understand why there is a profile involved. 

I'm not sure if you really understand what every setting you write (which I don't know) does, which unlike some other areas, would turn NE development from a nightmare to a hell.

Clearly there is something wrong and not working correctly. I recommend you to read [Specht](https://github.com/zhuhaow/specht) if you want to work with NE.

PS: Make sure you understand what "wifi-sharing" in surge means because what you want initially is not possible.

**Comment by zhuhaow** [comment]
I made a mistake. In order to start a server listen on all interfaces with `NEKit`, you have to init the server by `GCDHTTPProxyServer(address: nil, port: Port(port: 9090))` .

**Comment by ufo22940268** [comment]
@zhuhaow 

It seems that start server with `GCDHTTPProxyServer(address: nil, port: Port(port: 9090))`, the proxy server won't listen to "127.0.0.1:9090"

**Comment by zhuhaow** [comment]
How did you verify that?

**Comment by ufo22940268** [comment]
```
        proxySettings.httpServer = NEProxyServer(address: "127.0.0.1", port: 9090)
        proxySettings.httpEnabled = true
//        proxySettings.httpsServer = NEProxyServer(address: "127.0.0;.1", port: 9090)
//        proxySettings.httpsEnabled = true
//        proxySettings.matchDomains = [""]
        proxySettings.matchDomains = ["api.xinpinget.com"]
        networkSettings.proxySettings = proxySettings
        
        networkSettings.dnsSettings = NEDNSSettings(servers: ["114.114.114.114"])

        let ipv4Settings = NEIPv4Settings(addresses: ["192.169.89.1"], subnetMasks: ["255.255.255.0"])
        networkSettings.ipv4Settings = ipv4Settings

        RawSocketFactory.TunnelProvider = self
        
        setTunnelNetworkSettings(networkSettings) { (error) in

            if let error = error {
                NSLog("++++++++++" + error.localizedDescription)
            }
            
            self.proxyServer = GCDHTTPProxyServer(address: nil, port: 9090)
```

When i set http proxy like above, then client can't access to website. But after i change to `self.proxyServer = GCDHTTPProxyServer(address: IPAddress(fromString: "127.0.0.1"), port: 9090)`, it works again.

**Comment by zhuhaow** [comment]
this behavior does not compliant to the doc of CocoaAsyncSocket, I don’t know why.

**Comment by ufo22940268** [comment]
Ok, i will try to figure out later.

**Comment by chinsyo** [comment]
@ufo22940268 Have you figure out?
