### ISSUE TITLE
我想问一下IOS的VPN组件能接管所有的请求吗？

### ISSUE THREAD

**Issue by liaogang** [zhuhaow/NEKit#147]
怎么微信的TCP请求还是直接发到　广东深圳的IP地址去了啊

**Comment by zhuhaow** [comment]
你可以稍微具体一点……

**Comment by liaogang** [comment]
我在wingy上配置了一个shadowsocks服务器，把代理模式设置成为全局的。点击连接，IOS状态栏上成功出现了VPN的标示。　我再在电脑上用rvictl -s b7e04d06ea14302872114ef06bdcf6c577f392b8开启
Starting device b7e04d06ea14302872114ef06bdcf6c577f392b8 [SUCCEEDED] with interface rvi1
重启微信，打开wireshark进行抓包。　　发现还是有一些直接包走到14.215.158.119这个IP里面去了。　我查到这个IP是广东省深圳市 电信，就是腾讯的服务器。　没有经过我的shadowsocks服务器

**Comment by zhuhaow** [comment]
wingy并没有真正的工作在ip层，只是创建了一个代理服务器，并更新了系统网络设置而已。

所以如果微信自己用CFSocket或事其他的什么，可能就没有走代理。

**Comment by liaogang** [comment]
明白了。多谢

**Comment by Skifary** [comment]
@zhuhaow 有没有办法让所有的请求走代理呢？
