### ISSUE TITLE
求救，carthage update后失败

### ISSUE THREAD

**Issue by WiiliamChik** [zhuhaow/NEKit#148]
xcode 9.1，运行carthage update --no-use-binaries --platform mac,ios命令失败。完整log如下，感谢作者大大帮忙。

*** Fetching YamlSwift
*** Fetching Resolver
*** Fetching tun2socks
*** Fetching CocoaLumberjack
*** Fetching CocoaAsyncSocket
*** Checking out CocoaAsyncSocket at "7.6.2"
*** Checking out CocoaLumberjack at "3.4.1"
*** Checking out MMDB-Swift at "0.2.7"
*** Checking out Nimble at "v7.0.1"
*** Checking out Quick at "v1.1.0"
*** Checking out Resolver at "0.1.3"
*** Checking out Sodium-framework at "v1.0.10.1"
*** Checking out tun2socks at "0.6.1"
*** Checking out YamlSwift at "3e880fee0e68653f8304392cf0a9b7fc4b376a38"
*** xcodebuild output can be found in /var/folders/0z/66fl75_x2sg5zx96x1dzsx080000gn/T/carthage-xcodebuild.ebP2hE.log
*** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
2018-03-08 22:27:24.411 xcodebuild[25896:4066414] [MT] PluginLoading: Required plug-in compatibility UUID C3998872-68CC-42C2-847C-B44D96AB2691 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-03-08 22:27:26.834 xcodebuild[25896:4066676]  DTDeviceKit: deviceType from a0237c76ac24fe547e67e6156df49572c62e1ced was NULL
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/WilliamChik/Library/Developer/Xcode/DerivedData/CocoaAsyncSocket-adwhjqpqxsyktggjxenqmblvkovu/Build/Intermediates.noindex/CocoaAsyncSocket.build/Release-iphoneos/iOS\ CocoaAsyncSocket.build/Objects-normal/armv7/GCDAsyncSocket.o Source/GCD/GCDAsyncSocket.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/WilliamChik/Library/Developer/Xcode/DerivedData/CocoaAsyncSocket-adwhjqpqxsyktggjxenqmblvkovu/Build/Intermediates.noindex/CocoaAsyncSocket.build/Release-iphoneos/iOS\ CocoaAsyncSocket.build/Objects-normal/arm64/GCDAsyncSocket.o Source/GCD/GCDAsyncSocket.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
/Users/WilliamChik/Documents/github folder/NEKit/Carthage/Checkouts/CocoaAsyncSocket/Source/GCD/GCDAsyncSocket.m:7585:3: error: receiver 'NSTimer' for class message is a forward declaration
/Users/WilliamChik/Documents/github folder/NEKit/Carthage/Checkouts/CocoaAsyncSocket/Source/GCD/GCDAsyncSocket.m:7585:11: error: no known class method for selector 'scheduledTimerWithTimeInterval:target:selector:userInfo:repeats:'
/Users/WilliamChik/Documents/github folder/NEKit/Carthage/Checkouts/CocoaAsyncSocket/Source/GCD/GCDAsyncSocket.m:7585:3: error: receiver 'NSTimer' for class message is a forward declaration
/Users/WilliamChik/Documents/github folder/NEKit/Carthage/Checkouts/CocoaAsyncSocket/Source/GCD/GCDAsyncSocket.m:7585:11: error: no known class method for selector 'scheduledTimerWithTimeInterval:target:selector:userInfo:repeats:'
A shell task (/usr/bin/xcrun xcodebuild -project "/Users/WilliamChik/Documents/github folder/NEKit/Carthage/Checkouts/CocoaAsyncSocket/CocoaAsyncSocket.xcodeproj" -scheme "iOS Framework" -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
2018-03-08 22:27:24.411 xcodebuild[25896:4066414] [MT] PluginLoading: Required plug-in compatibility UUID C3998872-68CC-42C2-847C-B44D96AB2691 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-03-08 22:27:26.834 xcodebuild[25896:4066676]  DTDeviceKit: deviceType from a0237c76ac24fe547e67e6156df49572c62e1ced was NULL
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/WilliamChik/Library/Developer/Xcode/DerivedData/CocoaAsyncSocket-adwhjqpqxsyktggjxenqmblvkovu/Build/Intermediates.noindex/CocoaAsyncSocket.build/Release-iphoneos/iOS\ CocoaAsyncSocket.build/Objects-normal/armv7/GCDAsyncSocket.o Source/GCD/GCDAsyncSocket.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/WilliamChik/Library/Developer/Xcode/DerivedData/CocoaAsyncSocket-adwhjqpqxsyktggjxenqmblvkovu/Build/Intermediates.noindex/CocoaAsyncSocket.build/Release-iphoneos/iOS\ CocoaAsyncSocket.build/Objects-normal/arm64/GCDAsyncSocket.o Source/GCD/GCDAsyncSocket.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

**Comment by zhuhaow** [comment]
升级到9.2或者用更老版本的NEKit
可以看一下changelog，看看能用那个版本的。不过可能会有没修的bug。
