### ISSUE TITLE
关于HTTPAdapter 类里面构建HTTP消息头的疑问

### ISSUE THREAD

**Issue by liaogang** [zhuhaow/NEKit#149]
override public func didConnectWith(socket: RawTCPSocketProtocol) {
        super.didConnectWith(socket: socket)

        guard let url = URL(string: "\(session.host):\(session.port)") else {
            observer?.signal(.errorOccured(HTTPAdapterError.invalidURL, on: self))
            disconnect()
            return
        }
        let message = CFHTTPMessageCreateRequest(kCFAllocatorDefault, "CONNECT" as CFString, url as CFURL, kCFHTTPVersion1_1).takeRetainedValue()
        if let authData = auth {
            CFHTTPMessageSetHeaderFieldValue(message, "Proxy-Authorization" as CFString, authData.authString() as CFString?)
        }
        CFHTTPMessageSetHeaderFieldValue(message, "Host" as CFString, "\(session.host):\(session.port)" as CFString?)
        CFHTTPMessageSetHeaderFieldValue(message, "Content-Length" as CFString, "0" as CFString?)

        guard let requestData = CFHTTPMessageCopySerializedMessage(message)?.takeRetainedValue() else {
            observer?.signal(.errorOccured(HTTPAdapterError.serailizationFailure, on: self))
            disconnect()
            return
        }

        internalStatus = .readingResponse
        write(data: requestData as Data)
        socket.readDataTo(data: Utils.HTTPData.DoubleCRLF)
    }

这个类是不是不完整啊？
这里为什么不读完进来的消息头就直接写一个CONNECT呢，万一是GET或POST呢？

**Comment by zhuhaow** [comment]
就算是 GET 或者 POST 依然可以用 CONNECT 连接。

这里就是用 CONNECT 进行简单的 TCP 转发，唯一的缺点是跳过了代理的缓存。

**Comment by liaogang** [comment]
那请问在这里要怎么取得进来的消息头啊，我想把进来的消息头原封不动的发到代理。　中间就加一个Proxy-Authorization认证

**Comment by liaogang** [comment]
因为我发现直接用这个类会连不上服务器
         let httpAdp = HTTPAdapterFactory(serverHost: "110.166.200.223" , serverPort: ss_port , auth: HTTPAuthentication(username: "T82ET82H349NZ84C", password: "8E8C9740BA122425" ))
        let httpRule = HTTPRule(adapterFactory: httpAdp )
        let manager = RuleManager(fromRules: UserRules, appendDirect: false )

都是返回401

**Comment by zhuhaow** [comment]
不是很理解这么做的必要性。

不过 HTTPAdapter 是要支持所有 TCP 连接的，所以并没有这个功能。

**Comment by liaogang** [comment]
CONNECT test.abuyun.com:80 HTTP/1.1
Host: test.abuyun.com:80
Proxy-Authorization: Basic VDgyRVQ4MkgzNDlOWjg0Qzo4RThDOTc0MEJBMTIyNDI1
Content-Length: 0

HTTP/1.1 400 Bad Request
Server: station
Date: Sat, 24 Mar 2018 12:28:54 GMT
Content-Type: text/html
Content-Length: 170
Connection: close

**Comment by zhuhaow** [comment]
你这是代理服务器么

**Comment by liaogang** [comment]
对啊。　这个头被代理直接转发到了internet的主机上，主机的http服务不认connect,返回了400

**Comment by zhuhaow** [comment]
你这是透明代理？

**Comment by liaogang** [comment]
应该是的。　所以我现在就是想在原生的HTTP头里面加上Proxy-auth认证信息。　但是好像只能读到ConnectSession的URL和PORT。

**Comment by zhuhaow** [comment]
你的设置太不合理了。
