### ISSUE TITLE
SpeedAdapter

### ISSUE THREAD

**Issue by burnsra** [zhuhaow/NEKit#15]
I was attempting to implement without using YAML config, as noted in the README.  Is it possible to implement a SpeedAdapter/Rule?

**Comment by zhuhaow** [comment]
SpeedAdapter itself can be seen as some rule based on speed, though it is used as a regular adapter.

Just initialize a SpeedAdapter with the adapters you want to use and than use it as a regular adapter.

-------------------
Zhuhao Wang
Zhejiang university

2016年9月9日 +0800 09:53 Robert Burns <notifications@github.com>，写道：

**Comment by burnsra** [comment]
I don't believe there are any initializers for SpeedAdapters currently.  Can you confirm?

**Comment by zhuhaow** [comment]
Opps, this is a bug. I just forgot to mark so many things with `public`. Fixed in master now.
Everything you think should be public pretty much should be public.

**Comment by burnsra** [comment]
Don't believe you can initialize the SpeedAdapter still.

**Comment by zhuhaow** [comment]
public initializer is not inherited as public? hmmm........

**Comment by zhuhaow** [comment]
Fixed now, I hope.
