### ISSUE TITLE
工程紧急！！！！！求助！！！！！1导入包出错

### ISSUE THREAD

**Issue by 502885507** [zhuhaow/NEKit#152]
/bin/sh -c /Users/dream1024/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/MMDB-Swift/0.2.7/Build/Intermediates.noindex/ArchiveIntermediates/MMDB-OSX/IntermediateBuildFilesPath/MMDB.build/Release/MMDB-OSX.build/Script-366F5FDE1F0515CD00DE3883.sh
/Users/dream1024/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/MMDB-Swift/0.2.7/Build/Intermediates.noindex/ArchiveIntermediates/MMDB-OSX/IntermediateBuildFilesPath/MMDB.build/Release/MMDB-OSX.build/Script-366F5FDE1F0515CD00DE3883.sh: line 2: [: /Users/dream1024/Desktop/C++: binary operator expected
/Users/dream1024/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/MMDB-Swift/0.2.7/Build/Intermediates.noindex/ArchiveIntermediates/MMDB-OSX/IntermediateBuildFilesPath/MMDB.build/Release/MMDB-OSX.build/Script-366F5FDE1F0515CD00DE3883.sh: line 3: /Users/dream1024/Desktop/C++: No such file or directory

** ARCHIVE FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/dream1024/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/MMDB-Swift/0.2.7/Build/Intermediates.noindex/ArchiveIntermediates/MMDB-OSX/IntermediateBuildFilesPath/MMDB.build/Release/MMDB-OSX.build/Script-366F5FDE1F0515CD00DE3883.sh
(1 failure)

看了 好几个 关于这个方面的问题 各种方法都试了  还是这个错误
工程紧急 
求助！！！！！！！！！！！

**Comment by zhuhaow** [comment]
就算脚本内容是机密你也可以把出错的那行贴出来吧

**Comment by 502885507** [comment]
Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/dream1024/Desktop/C++\ CASE/Carthage/Checkouts/MMDB-Swift/MMDB.xcodeproj -scheme MMDB-iOS -configuration Release -derivedDataPath /Users/dream1024/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/MMDB-Swift/0.2.7 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/rd/3n6mgs115mx_0rz8crqqcdn00000gp/T/MMDB-Swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/dream1024/Desktop/C++ CASE/Carthage/Checkouts/MMDB-Swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/rd/3n6mgs115mx_0rz8crqqcdn00000gp/T/carthage-xcodebuild.5vM1Tg.log

**Comment by 502885507** [comment]
已经配置了 代理
 并且 可以下载GeoLite2-Country.mmdb
不过这个文件是我单独 跑了 curl http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz 才下载下来

**Comment by 502885507** [comment]
github "zhuhaow/NEKit" "master" 用的是master

**Comment by 502885507** [comment]
xcode 用的是 9.2

**Comment by zhuhaow** [comment]
那你跑一下 MMDB-Swift 下面的 `update_database.sh` 呢？

**Comment by zhuhaow** [comment]
还有一点就是下载这个文件应该不需要挂代理的

**Comment by 502885507** [comment]
Updating GeoIP database.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1673k  100 1673k    0     0   836k      0  0:00:02  0:00:02 --:--:--  647k
Updated GeoIP database.

**Comment by zhuhaow** [comment]
试试加上 `env -i` 呢？

`env -i ./update_database.sh`

**Comment by zhuhaow** [comment]
你之前有成功过么，我看到你这个 `C++ Case` 的文件夹名心里就很虚啊。换一个不容易出错的吧。

**Comment by 502885507** [comment]
JokersMacBook-Pro:MMDB-Swift dream1024$ env -i ./update_database.sh
Updating GeoIP database.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1673k  100 1673k    0     0   453k      0  0:00:03  0:00:03 --:--:--  453k
Updated GeoIP database.

**Comment by 502885507** [comment]
没有成功过。。我换个文件夹名试试

**Comment by zhuhaow** [comment]
如果还能跑的话你直接跑一下出错的这个脚本
`/bin/sh -c /Users/dream1024/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/MMDB-Swift/0.2.7/Build/Intermediates.noindex/ArchiveIntermediates/MMDB-OSX/IntermediateBuildFilesPath/MMDB.build/Release/MMDB-OSX.build/Script-366F5FDE1F0515CD00DE3883.sh`
看看错误信息。

**Comment by 502885507** [comment]
说出来你可能不信  我换了个文件夹名字 好了！！！！！！！！

**Comment by zhuhaow** [comment]
你用这种文件夹名字早晚要掉坑的，着没啥可不信的
