### ISSUE TITLE
Is there a way to change the DNS server without TUNInterface

### ISSUE THREAD

**Issue by lambchopinc** [zhuhaow/NEKit#153]
Hi, TUNInterface does not work any more. In this case, any way to change the global DNS server for iOS?  Thanks

**Comment by zhuhaow** [comment]
You can set the dns to what ever server you want with network extension.

**Comment by lambchopinc** [comment]
Thanks for the reply. You mean NEDNSProxyProvider?  This is available in iOS 11.

**Comment by zhuhaow** [comment]
Just take a look at the configuration you can specify when you start vpn.
