### ISSUE TITLE
Update Readme to newest version

### ISSUE THREAD

**Issue by cuongtv51** [zhuhaow/NEKit#158]
I see some sample code in README have some old class ( IPv4Address, IPv4Pool ... ), 
And, I don't know TODO section have suppport IPv6 now?
Can We update readme for newest version?

**Comment by zhuhaow** [comment]
I won't provide new features for NEKit so there won't be full IPv6 support (but it should have partial support).

As for the doc, you can help and create a pull request. I don't have much capacity recently and it is not on the top of my priority list.
