### ISSUE TITLE
Compatible with swift4.0

### ISSUE THREAD

**Issue by weibo1314** [zhuhaow/NEKit#159]
carthage error
Compatible with swift4.0

I've added "master", but I can't.
<img width="992" alt="wx20180504-115634 2x" src="https://user-images.githubusercontent.com/20176993/39612447-38affae2-4f92-11e8-90c0-9f674aa0c24b.png">
<img width="240" alt="111" src="https://user-images.githubusercontent.com/20176993/39612453-4658daec-4f92-11e8-9983-c7a94347454e.png">

**Comment by weibo1314** [comment]
Is to use  "carthage update --no-use-binaries --platform ios"

**Comment by weibo1314** [comment]
<img width="563" alt="wx20180504-134333 2x" src="https://user-images.githubusercontent.com/20176993/39614264-27f172ee-4fa1-11e8-90a3-f508fe52b06a.png">

**Comment by zhuhaow** [comment]
不要用编译好的包，所有东西都自己编译。你引入了其他package的话请用当前你想用的Xcode/swift版本编译。

**Comment by weibo1314** [comment]
我没有引入其他的啊...Cartfile里只有  github "zhuhaow/NEKit" "master"

**Comment by zhuhaow** [comment]
你整个项目没有用其他的framework？

**Comment by weibo1314** [comment]
我有用cocoapods

**Comment by zhuhaow** [comment]
swift —version 显示什么

**Comment by weibo1314** [comment]
![wx20180504-140216](https://user-images.githubusercontent.com/20176993/39614621-cb55a228-4fa3-11e8-8e0e-64f156181547.png)

**Comment by zhuhaow** [comment]
你xcode什么版本呢，Xcode->toolchains显示什么

**Comment by weibo1314** [comment]
我用的9.2...我有安装9.3..但是wcdb报错..又装了一个9.2的

**Comment by zhuhaow** [comment]
命令行用的是4.1，来自xcode 9.3。
用xcode-select换到xcode 9.2， 应该是4.0.2。

**Comment by weibo1314** [comment]
那我应该怎么办呢[捂脸]...降低swift版本吗

**Comment by zhuhaow** [comment]
xcode-select

**Comment by weibo1314** [comment]
我把9.3的xcode删了...现在可以了.....万分感谢...大大的star送给你
