### ISSUE TITLE
randomly got an critical error

### ISSUE THREAD

**Issue by simpzan** [zhuhaow/NEKit#16]
```
<Critical>: NWTCPSocket got an error when reading data: Optional(Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected")
```

**Comment by zhuhaow** [comment]
This is by design. I may remove that log soon.

-------------------
Zhuhao Wang
Zhejiang university

2016年9月11日 +0800 11:25 Samuel <notifications@github.com>，写道：

**Comment by simpzan** [comment]
If this is a normal case, It should not be an critical error.

**Comment by zhuhaow** [comment]
I agree.
It is the system that thinks it is critical. However, there is no consequence. This error is there because I want to simplify the implementations. Will be fixed.

-------------------
Zhuhao Wang
Zhejiang university

2016年9月11日 +0800 13:33 Samuel <notifications@github.com>，写道：
