### ISSUE TITLE
问一个审核的问题

### ISSUE THREAD

**Issue by harveyHW** [zhuhaow/NEKit#160]
我的app使用NEPacketTunnelProvider和NEPacketTunnelManager来创建了一个vpn开发完成。
 在PacketTunnelAPP中，使用了 NEKit， Yaml， CocoaLumberjackSwift，NetworkExtension框架
但是在我上架的时候因为这个问题被拒，这是什么意思呢？请教一下
但是我看到官方文档说明，proxy是不用提交邮件申请entitlements吧？

Guideline 2.5.1 - Performance - Software Requirements

Your app uses public APIs in an unapproved manner, which does not comply with guideline 2.5.1 of the App Store Review Guidelines.

Specifically, ‘NEPacketTunnelProvider’.

Since there is no accurate way of predicting how an API may be modified and what effects those modifications may have, Apple does not permit unapproved uses of public APIs in App Store apps.

@zhuhaow  please help me  thax！

**Comment by zhuhaow** [comment]
不知道，没搞过iOS开发，没上架过app

如果你想试试，可以把中国区去掉看能不能上架

**Comment by liaogang** [comment]
apple 有个例子simpletunnel你可以参考一下 @harveyHW

**Comment by bjlualy** [comment]
遇到了同样的问题，解决了吗？

**Comment by AlfredCN** [comment]
遇到同样的问题，但是没有指出来Specifically, ‘NEPacketTunnelProvider’.

请问怎么解决的？

**Comment by YanweiLi** [comment]
> 遇到同样的问题，但是没有指出来Specifically, ‘NEPacketTunnelProvider’.
> 
> 请问怎么解决的？

我也遇到这样的问题 ， 没有指出来Specifically, ‘NEPacketTunnelProvider’.。  请问你解决了吗？
