### ISSUE TITLE
提供一个iOS里100%重现tun2socks的crash的步骤

### ISSUE THREAD

**Issue by liaogang** [zhuhaow/NEKit#161]
先开启TunInterface
再打开百度iOS客户端，app加载主页面的时候会crash.  可以用Xcode9来调试vpn组件,attach到VPN组件的时候，可以看到程序在TSTCPScoket.writeData停下来。 

![2018-05-07 5 11 46](https://user-images.githubusercontent.com/3311527/39694441-e8556eda-5219-11e8-9471-096e274b882c.png)

**Comment by zhuhaow** [comment]
谢谢，这里似乎 data 的长度有问题，怎么会一次发这么大的数据呢（虽然没啥错）。

不过这里并不是crash的唯一原因，即便正确处理了 data 的最大长度问题，还是会崩溃的

**Comment by liaogang** [comment]
恩。数据长度超过了unit16的范围了。　我把过长的数据分成了几个小份数据，目前百度app测试还是可以的。

**Comment by YMChina** [comment]
@liaogang 请问要怎么把过长的数据分成几个小份数据？
