### ISSUE TITLE
我通过.conf可以设置规则..但是怎么设置全局不走代理..只有我规定的域名和ip走代理

### ISSUE THREAD

**Issue by weibo1314** [zhuhaow/NEKit#162]
<img width="311" alt="qq20180509-163456 2x" src="https://user-images.githubusercontent.com/20176993/39804555-ed5d9810-53a6-11e8-8280-cb6cfa85a1dc.png">

**Comment by zhuhaow** [comment]
我不是很明白你想问什么，这个看起来也不像正确的 build-in 的 config 的写法。

全局不走最后加一个 all， direct。

**Comment by weibo1314** [comment]
可以提供一个,全局不走代理...只有我规则内的ip和域名走代理的规则文件截图参考一下么...万分感谢

**Comment by weibo1314** [comment]
<img width="765" alt="qq20180510-103737 2x" src="https://user-images.githubusercontent.com/20176993/39849311-49cf91ce-543e-11e8-965c-9953190d09f4.png">
我是在这里设置规则文件

<img width="412" alt="qq20180510-103827 2x" src="https://user-images.githubusercontent.com/20176993/39849324-56bf3ca4-543e-11e8-89ab-6256378bf5bd.png">
这里是我规则文件内的配置,但是现在默认是全局走代理..可以设置不走代理的域名和ip,,,我希望实现全局不走代理..只有我规则内的ip和域名走代理...

**Comment by zhuhaow** [comment]
额，把direct和代理的adapter的名字换一下？

**Comment by weibo1314** [comment]
换一下就可以了?需求是所有的域名和ip都不走代理..只有我规定的域名和ip走..这个文件里的criteria我贵修改

**Comment by zhuhaow** [comment]
这个又不是我写的，我连代码都看不到信息比你还少还不就是猜。

我现在还没搞懂这里是有什么难点，难道走代理的写代理的adapter name直连写direct有什么不合理的么？你能不能说清楚道理逻辑上这个配置文件哪个环节你搞不懂
