### ISSUE TITLE
把NEKit移植到iOS8

### ISSUE THREAD

**Issue by liaogang** [zhuhaow/NEKit#164]
简单来说就是我想把您的NEKit移植到iOS8上面去。因为用到了[私有的VPN API](https://blog.michael.kuron-germany.de/2010/09/ios-4-1-undocumented-vpn-api-used-by-cisco-anyconnect/)。目前我通过这个API向系统申请到了一个Tun口。而且能够从Tun口拿到数据，也可以写回。　
比如这个截图里有一些DNS的包，数据包含完整的Frame.
![2018-05-23 4 14 36](https://user-images.githubusercontent.com/3311527/40411937-7588d210-5ea4-11e8-99e0-3aa48462a113.png)

但是iOS8里的NetworkExtern不如9里的接口全，也没有Network库。 
就是NEKit里 NWTCPSocket所依赖的  NWUDPSession , 和　NWUDPSocket所依赖的NWUDPSession没有。

也就是说这些UDP和TCP的包头要自己处理。您有什么好的建议吗？

**Comment by zhuhaow** [comment]
根本建议，放弃所有今天都还在用iOS8的用户。

修改相关的东西，包括：
1. 在 `RawSocketFactory` 中返回正确的 socket。
2. 在 `CocoaAsyncSocket` 的相关代码中，使用

```
- (BOOL)connectToHost:(NSString *)host
               onPort:(UInt16)port
         viaInterface:(NSString *)interface
          withTimeout:(NSTimeInterval)timeout
                error:(NSError **)errPtr
```

进行连接，从而保证走正确的device。UDP同理自己实现。

另外，NEKit在32位上有bug需要修复，具体bug未知。

**Comment by liaogang** [comment]
网络方面的细节不是很懂。　我现在拿到了一个tunnel fd,　现在只能用用read和write函数来读写数据。
具体怎么跟您说的-[CocoaAsyncSocket connectToHost:onPort:viaInterface:withTimeout:]连接起来还没明白。



    const int max = 1024;
    
    Byte buf[max] = {};
    
    while (1) {
        ssize_t readed = 0;
        
        NSLog(@"+ to read");
        readed = read(ctrl->getTunelFd(), buf, max * sizeof(buf[0]));
        
        if (readed > 0) {
            if (buf[13] == 11) {
                NSLog(@"UDP");
            }
            else{
                NSLog(@"TCP");
            }
            
            NSString *str = @"";
            
            for (int i = 0; i < readed; i ++) {
                str = [str stringByAppendingFormat:@" %02x", buf[i] ];
            }

            NSLog(@"%@",str);
            
            //NSLog(@"+ read %zu bytes from tun interface: %s", readed , buf);
        }
        else{
            NSLog(@"+ read nothing");
        }
        
        
        
        char *resp =
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/plain; charset=utf-8\r\n"
        "Connection: close\r\n"
        "Vary: Accept-Encoding\r\n"
        "Pragma: no-cache\r\n"
        "\r\n"
        "asdfqwer";
        
        
        ssize_t writed = write(ctrl->getTunelFd(), resp, strlen(resp));
        NSLog(@"writed %zu bytes",writed);
        
        
        sleep( 3 );
        
    }

**Comment by zhuhaow** [comment]
都忘了这个问题了，这个就难一些了。

之前我说的那些都是为了保护连接到目标服务器的不要再走到tun里面去变成loop的。

这里牵涉的不仅是网络的问题还有线程和堵塞的问题。你可以思考怎么把这个fd封装成和packetflow（network extension）类似的使用方式。

写的话用一个dispatch_queue堵塞写。
读用另一个dispatch_queue堵塞读，但是要考虑对应socket的写入还没有完成，需要一个queue，满了就扔掉所有新的。

如果你不理解上面是要解决什么问题的话（基本和网络无关），那你基本写不出来。

不如说说什么非要iOS 8。

**Comment by zhuhaow** [comment]
现在在用 iOS 8 越狱的人应该都不是会安app的人吧

**Comment by liaogang** [comment]
只能说不是正常用户。那什么羊毛党..　



我今天把iOS8里面一层的接口模清了。

就是这个类封装的一组C函数。 -[NEPacketTunnelFlow readPacketsWithCompletionHandler]
```
NEVirtualInterface NEVirtualInterfaceCreateFromSocket(CFAllocatorRef allocator, int fd, dispatch_queue_t queue, int flag);

//设置为自动
NEVirtualInterface NEVirtualInterfaceSetReadAutomatically(NEVirtualInterface arg0, int flag );

typedef void(^MyBlock5)(NEVirtualInterface vi,int* pProtocols,Byte** pBuffer,int* pBufferLength,int numberOfArray);
//void NEVirtualInterfaceSetReadMultipleIPPacketsHandler(NEVirtualInterface arg0, MyBlock5 arg1);//ios9
typedef void(^MyBlock5Old)(NEVirtualInterface vi,int protocol,Byte* buffer,int length);
void NEVirtualInterfaceSetReadIPPacketHandler(NEVirtualInterface vi, MyBlock5Old callback );//ios8

NEVirtualInterface NEVirtualInterfaceReadyToRead( NEVirtualInterface vi,  int flag);

void NEVirtualInterfaceWriteIPPacket(NEVirtualInterface vi,int protocol,Byte* buffer,int length);
```

下一步就是要把DNS的调通
因为我以前没怎么搞过网络底层。估计我要把NEKit的TunInterface的数据流动摸得很清楚才能搞通。

**Comment by zhuhaow** [comment]
……

我感觉设个代理应该就够了

**Comment by liaogang** [comment]
DNS的没什么问题了。我用GCDAsyncUdpSocket代替了NWUDPSession

TCP的单个简单的网页打开也还可以。就是百度这种大网站，还有打开AppStore就好慢，是怎么回事啊？

我主要在　RawSocketFactory　返回的地方把NWTCPSocket换成了GCDTCPSocket，
然后在GCDTCPSocket里        用这个连接　try socket.connect(toHost: host, onPort: UInt16(port), viaInterface: "en0", withTimeout: -1)　

我用TCPDUMP监视en0和utun0两个接口，也没发现在loop存在啊。

**Comment by zhuhaow** [comment]
很可能是某些原因因此很多包丢失了或者变无效的了

**Comment by liaogang** [comment]
应该是没问题的。　我现在重新用你的版重新改了一次，这次能用了。
