### ISSUE TITLE
有条件的自动断开VPN

### ISSUE THREAD

**Issue by kylo-2** [zhuhaow/NEKit#168]
你好，请教下怎么知道vpn服务不能使用了，此时客户端自动断开vpn连接
（对网络这块不太了解）

**Comment by zhuhaow** [comment]
什么叫不能使用呢？如果定义的清楚我想你应该可以想到怎么实现

**Comment by kylo-2** [comment]
比如正在使用的过程中vpn服务到期了，客户端知道了就能自动断开连接

**Comment by zhuhaow** [comment]
那你extension自己stop就好了

**Comment by kylo-2** [comment]
这个知道，就是没搞懂应该怎么去监听这个状态
----- 原始邮件 -----
发件人：zhuhaow <notifications@github.com>
收件人：zhuhaow/NEKit <NEKit@noreply.github.com>
抄送人：kylo-2 <15658694047@sina.cn>,  Author <author@noreply.github.com>
主题：Re:_[zhuhaow/NEKit]_有条件的自动断开VPN_(#168)
日期：2018年06月03日 14点43分

那你extension自己stop就好了



> On 3 Jun 2018, at 14:42, kylo-2 <notifications@github.com> wrote:

> 

> 比如正在使用的过程中vpn服务到期了，客户端知道了就能自动断开连接

> 

> —

> You are receiving this because you commented.

> Reply to this email directly, view it on GitHub, or mute the thread.



&mdash;
