### ISSUE TITLE
Resolve hostname to ip

### ISSUE THREAD

**Issue by alisolutions** [zhuhaow/NEKit#169]
Is their any support in the library to resolve hostname to ip while using PacketTunnelProvider Extension?

**Comment by zhuhaow** [comment]
If you route dns to tun interface then you have to handle it yourself or use the build-in DNSResolver

**Comment by alisolutions** [comment]
Thanks,
Can you please give me any example that how I may use DNSResolver?

**Comment by zhuhaow** [comment]
You have two choices, don’t route DNS server address to tun interface, or use DNSResolver as part of DNSServer which is part of the IPStack.

Take a look at Specht for example.

**Comment by alisolutions** [comment]
I am using DNSResolver, can you please guide me that where I should append that hostname to ip lookup entry?
Also can you please tell me is their any role of fakeIps which I should use?
Please guide.

**Comment by zhuhaow** [comment]
What do you want to achieve? What are you using NEKit for? It does not feel like you are using it properly.

Anyway, You can find the real ip in connectsession.ipaddress or follow the way how it is done.

**Comment by alisolutions** [comment]
My main aim is to edit etc/host file to add hostname to ip address lookup. But we can not achieve that without root access. So now I am using NEKit so that I can resolve that hostname to ip. 
In outputSession function of DNSServer class, I manually replace the ip address in the answer like following. But that is not working. Can you please help me that how I can achieve that, I think we should resolve it locally. Or can I add any Rule for that?

if (session.requestMessage.queries[0].name == "www.mywebsite.com") {
            let response = DNSMessage()
            response.transactionID = session.requestMessage.transactionID
            response.messageType = .response
            response.recursionAvailable = true
            let resolvedIp = IPAddress(fromString: "192.168.2.3")!
            // since we only support ipv4 as of now, it must be an answer of type A
            response.answers.append(DNSResource.ARecord(session.requestMessage.queries[0].name, TTL: UInt32(Opt.DNSFakeIPTTL), address: resolvedIp))
            session.expireAt = Date().addingTimeInterval(Double(Opt.DNSFakeIPTTL))
            guard response.buildMessage() else {
                DDLogError("Failed to build DNS response.")
                return
            }
            
            udpParser.payload = response.payload
        }

**Comment by zhuhaow** [comment]
Have you looked at this one?
https://github.com/zhuhaow/NEKit/issues/110

**Comment by alisolutions** [comment]
I got it. Let me try it.
