### ISSUE TITLE
Can not connect to telegram

### ISSUE THREAD

**Issue by dddeee2004** [zhuhaow/NEKit#174]
Hi,i am useing nekit to developer a VPN client,everything was ok,but today I found when VPN was open (using shadow socket) the telegram app can not connect , and I found Wingy was also have this problem, I do not know why.

**Comment by zhuhaow** [comment]
Because Telegram ignores proxy setting and you are not actually setting up a VPN routing everything.

There is no simple solution other than use tun which NEKit support is not stable.

**Comment by dddeee2004** [comment]
请问怎么解决呢？

**Comment by zhuhaow** [comment]
把所有流量route到NE的tun上，然后处理

**Comment by zhoubo6419** [comment]
@dddeee2004 你的现在可以了吗

**Comment by 493441755** [comment]
@zhoubo6419 你的现在可以了吗

**Comment by candiceatwb** [comment]
@dddeee2004 请问这个问题解决了吗？

**Comment by dddeee2004** [comment]
解决了 但不是用的这个框架




------------------ Original ------------------

**Comment by candiceatwb** [comment]
@dddeee2004 谢谢你的回复

**Comment by candiceatwb** [comment]
@dddeee2004 顺便问下，你当时有尝试 @zhuhaow 给的 “把所有流量route到NE的tun上，然后处理”  建议吗？

**Comment by dddeee2004** [comment]
没有 我研究了SS 源码 并基于此开发了完整的程序。ios/android版支持最新 xcode/android studio 编译，有 demo，支持智能/全局代理，支持规则文件解析。ss库为最新 3.25版本，支持最新加密试。
具体在知识星球搜索 APP代理开发------------------ Original ------------------

**Comment by candiceatwb** [comment]
@dddeee2004 好，谢谢。

**Comment by geeyan** [comment]
> 解决了 但不是用的这个框架
> […](#)
> ------------------ Original ------------------ From: candiceatwb <notifications@github.com> Date: Thu,Jun 20,2019 3:05 PM To: zhuhaow/NEKit <NEKit@noreply.github.com> Cc: dddeee2004 <149424560@qq.com>, Mention <mention@noreply.github.com> Subject: Re: [zhuhaow/NEKit] Can not connect to telegram (#174) @dddeee2004 请问这个问题解决了吗？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

可以问一下用的是哪个框架吗，目前也遇到了这个问题

**Comment by mobisecitalia** [comment]
> 解决了 但不是用的这个框架
> […](#)

Which framework are you using?
