### ISSUE TITLE
开启tun后，其他app使用GCDAsyncSocket通过tcp发送数据，当服务端主动关闭连接后，客户端无法收到socketDidDisconnect回调

### ISSUE THREAD

**Issue by fishbeauty** [zhuhaow/NEKit#176]
在测试tcp转发过程发现的现象

首先开启tun

服务端很简单，每次accept新的socket之后，读取数据，然后回写一条数据，然后主动关闭连接

客户端写一个测试小程序，创建一个GCDAsyncSocket，连接服务端，发送一条消息

如果不使用tcp转发，最后客户端能进到 socketDidDisconnect 方法，知道已经断开连接

如果开启tun, 服务端关闭后，客户端无法进入 socketDidDisconnect，观察log,发现，adapterSocket,proxySocket,tunnnel 均已经close

请问这是什么原因呢

这样对客户端有没有影响

**Comment by zhuhaow** [comment]
既然log都打出来了为什么回调没有调呢？你断点调试一下。

**Comment by fishbeauty** [comment]
我指的socketDidDisconnect回调，不是NEKit这块，而是我写的另一个测试app,里面只开了一个GCDAsyncSocket  这个socket 当服务端主动关闭连接的时候，无法收到关闭连接的回调

**Comment by fishbeauty** [comment]
NEKit在开启tcp转发之后，假设这里转发使用的是DirectAdapter,
当真实服务器直接关闭socket之后，DirectAdapter 会读取数据失败，然后关闭
接着告诉tunnel,tunnel再告诉proxySocket进行关闭
proxySocket封装的是  TUNTCPSocket  ,总之最后会调用到   TSTCPSocket.close
最后TSTCPSocket.close会调用到 lwip
上面是NEKit的实现，看起来流程是没有问题的


但是对其其他App来看,确实没有触发socket主动关闭

**Comment by zhuhaow** [comment]
你说lwip没有发FIN包？

**Comment by fishbeauty** [comment]
@zhuhaow   对看上去就是这样的，lwip没发FIN包，所以造成没有关闭socket

**Comment by Taherismail17** [comment]
How do u use LWIP to turn run to socks? The VPN works on websites but not all apps (Facebook). I’m using this - https://github.com/sheng/ladder-ios

**Comment by xiezhirong2015** [comment]
请问下 同样的配置 国行的手机就能连VPN  港版美版的都只是显示VPN连接成功，但是网页打不开，是countryRule的设置问题还是别的问题
