### ISSUE TITLE
While VPN enabled, turning WiFi off causes WiFi to still be "on" but all connections fail?

### ISSUE THREAD

**Issue by PyroFilmsFX** [zhuhaow/NEKit#177]
Using NEKit, NEPacketTunnelProvider extension.

This issue sounds odd, and originally assumed to be caused by having onDemand enabled.

Essentially, if WiFi is enabled, connect to the VPN, then disconnect (or disable) WiFi (which would fallback to cellular) just keeps the WiFi interface enabled in the statusbar, but WiFi (or cellular) is not actually enabled or working. All connections fail. I can provide code if need be.

After trying many workarounds, I even programmatically disabled the onDemand rule and this still occurs. So that's what takes me here.

I assumed something was wrong with my netowork change obserer, but "defaultPath.debugDescription" is always the same, before or after attempting to disconnect from WiFi, so I am not even sure how I could detect the attempted disconnect? 

It is just extra odd because the VPN itself works flawlessly other than this one issue. I cannot find it reported anywhere else.

Thank you in advanced for any help or ideas.

**Comment by Ricardo1980** [comment]
What did you do to fix that?
