### ISSUE TITLE
上传ipa包报错 90056 90057

### ISSUE THREAD

**Issue by wolfhous** [zhuhaow/NEKit#179]
iTunes Store Operation Failed
ERROR ITMS-90057: "The bundle 'Payload/vpn.app/Frameworks/NEKit.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString."
iTunes Store Operation Failed
ERROR ITMS-90056: "This bundle Payload/vpn.app/Frameworks/NEKit.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion."

**Comment by zhuhaow** [comment]
如果你修改过nekit那么生成的包就不会有正确的tag，你可以手动修改一下

**Comment by yuzhijiang** [comment]
问一下楼主，只需要手动修改nekit里面的plist吗？我修改过还是出现同样的问题，而且重新打包好像版本号还是1.0

**Comment by changfeifan** [comment]
@wolfhous  请问修改成了什么数值？

**Comment by hair-man** [comment]
> @wolfhous 请问修改成了什么数值？

类似x.x.x就可以，自己随便写
