### ISSUE TITLE
module compiled with Swift 4.1.2 cannot be imported in Swift 4.0.3

### ISSUE THREAD

**Issue by MKXiaoyue** [zhuhaow/NEKit#180]
NEkit do not support Swift 4.1.2

**Comment by zhuhaow** [comment]
What you copied says that you are trying to import module compiled with 4.1.2 to a project using 4.0.3. This usually means you complied NEKit with 4.1.2 which means NEKit supports 4.1.2, and you are using 4.0.3, which is bundled with Xcode 9.2 I think.

Try to compile NEKit with `carthage update --no-use-binaries --platform mac,ios`, and if it does not compile with 4.0.3, you need to use older version of NEKit or upgrade your Xcode.
