### ISSUE TITLE
UDP filtering

### ISSUE THREAD

**Issue by hay187** [zhuhaow/NEKit#182]
Hello,

I need to filter (see and edit) UDP traffic on the device to all IPs.  I don't care about TCP or other packet traffic at all except that it needs to work and not be blocked from the users perspective.

What would be the easiest way to let TCP traffic through untouched?  From my understanding I have no choice but to use the TUNInterface (the memory leaks and bugs are a side issue) to make sure all scenarios will work?

My next issue is, if I do enable TUNInterface ipv6 only networks fail because of the DNS resolver issue.  Would I even need my own resolver in this case?

Any help appreciated.

**Comment by Ricardo1980** [comment]
Read section 4 from this doc for your first question. Seems that you are not going to like the answer.
https://nsg.ee.ethz.ch/fileadmin/user_upload/theses/MA-2016-47.pdf

**Comment by hay187** [comment]
Ok as expected I need to recreate the tcp flow myself.  Tun2socks seems the easiest way since Nat doesn’t work properly inside the extension.

Aside from the issues in tun2socks ipv6 is the other issue.

Is there source code for that spy spy app?

**Comment by zhuhaow** [comment]
That app seems does not really provide a working TCP stack but simply assuming there is no packet loss (which probably works since the stack only runs locally).

**Comment by hay187** [comment]
Ahh so that may not be too reliable because there could be cases where there’s local loss due to resources etc.

I’ll double check the NAT issue otherwise will need to update lwip and tun2socks for iOS.  The original code seems to have only just added ipv6 support in svn

**Comment by zhuhaow** [comment]
Hi @Ricardo1980, we found NE now allows use NAT so we don't need self-implemented IP stack to handle TCP packet.

I'm going to close this now.

**Comment by Ricardo1980** [comment]
@zhuhaow Nice. Do you have any like or something I can read to learn more about that? Searching "Network Extension ios NAT" in google does not return anything.

**Comment by zhuhaow** [comment]
Because NAT does not really have anything to do with NE. Just search NAT. 

And you don't need it to work with DNS filtering
