### ISSUE TITLE
CCCrypto Update 野指针 Crash

### ISSUE THREAD

**Issue by ZengyiMa** [zhuhaow/NEKit#185]
Hi,我在使用 NEKit 的 ShadowsocksAdapter 的时候发现可以正常连接上，但是只要连接Google，PacketTunnel 会Crash，如下图的debug信息
![image](https://user-images.githubusercontent.com/3383471/43537205-44b52060-95f1-11e8-93dd-575a612bd5aa.png)

系统是 iOS 11.4.1，希望作者解答。谢谢了

补充一下，是 AES128FCB 加密方式出现了crash

**Comment by zhuhaow** [comment]
加上
```
if data.count == 0 {
return
}
```

**Comment by ZengyiMa** [comment]
验证了一下。确实可以。感谢
