### ISSUE TITLE
yaml规则过大时，会出现崩溃

### ISSUE THREAD

**Issue by android0276** [zhuhaow/NEKit#189]
我使用的是swift4.1，将yaml在VPNManager中解析，然后通过配置传过来，可是解析出现数据decode错误，求解救

**Comment by zhoubo6419** [comment]
怎么样 解决了不 @android0276

**Comment by android0276** [comment]
@zhoubo6419 已经解决了，谢谢

**Comment by zhoubo6419** [comment]
哈哈 你是怎么解决这个问题 @android0276

**Comment by zhoubo6419** [comment]
我已经被卡死好久了 😂

**Comment by android0276** [comment]
你把微信二维码发我邮箱thunken.shi@gmail.com

**Comment by android0276** [comment]
把yaml解析成纯字符串的字典再传过来

**Comment by zhoubo6419** [comment]
我是直接传字符串过去的，但是Yaml.load 这个方法就失败 那我这个就没有问题 那是啥原因呢

**Comment by zhoubo6419** [comment]
对了 你的规则文件有多少行？

**Comment by android0276** [comment]
yaml.load要放在vpnmanage里面，放tunnel必定闪退，我2000行

**Comment by zhoubo6419** [comment]
哦哦哦好的 那我知道了 哈哈 我试试

**Comment by android0276** [comment]
你搞好了这个，发现要想用Telegram，你还需要打开tun模式，这个tun2socks目前我发现所有开源都有坑

**Comment by zhoubo6419** [comment]
😂 😂 😂 还有这个坑
