### ISSUE TITLE
Sample Implementation: Packet filter

### ISSUE THREAD

**Issue by PantherJohn** [zhuhaow/NEKit#194]
A passthru local tunnel that intercepts packets on `TCPStack`. What should the code be like?

**Comment by PantherJohn** [comment]
@zhuhaow

**Comment by zhuhaow** [comment]
Take a look at https://github.com/zhuhaow/Specht

**Comment by PantherJohn** [comment]
@zhuhaow 

> `peekSourcePort(_:)`
> Get the source port of the IP packet without parsing the whole packet.

So will I be able to modify the source port along the way? Just to make sure.

**Comment by zhuhaow** [comment]
There are many utility methods to help. And I think there is one to change the port

On 12 Sep 2018, at 19:42, Jared Hillier <notifications@github.com> wrote:

@zhuhaow

peekSourcePort(_:)
Get the source port of the IP packet without parsing the whole packet.

So will I be able to modify the source port along the way? Just to make sure.

**Comment by PantherJohn** [comment]
@zhuhaow and this is not possible without `IPPacket` class. Network Extension framework has no support for packet header modification. Rebuilding packets? That would be cumbersome and inefficient.

**Comment by zhuhaow** [comment]
There aren’t any build-in support, which makes sense since it can’t be general.


If you just want to modify the port, you can write one in a few lines.


On 12 Sep 2018, at 20:14, Jared Hillier <notifications@github.com> wrote:

@zhuhaow and this is not possible without IPPacket class. Network Extension framework has no support for packet header modification. Rebuilding packets? That would be cumbersome and inefficient.

**Comment by PantherJohn** [comment]
@zhuhaow **Update:**
Should the implementation be
```
packet.sourcePort = /* Source port */
packet.destinationPort =  /* Destination Port */
```
I'm a newbie in Swift. Sorry about that.

**Comment by zhuhaow** [comment]
You get a Data which is just a memory block, you can just replace specific range with build-in method. 

On 12 Sep 2018, at 21:38, Jared Hillier <notifications@github.com> wrote:

@zhuhaow Update:
Should the implementation be

packet.sourcePort = /* Source port */
packet.destinationPort =  /* Destination Port */
I'm a newbie in Swift. Sorry about that.

**Comment by PantherJohn** [comment]
Agreed. [Router.swift](https://github.com/zhuhaow/NEKit/blob/master/src/IPStack/Router.swift) has offered a great example for this.
