### ISSUE TITLE
xcode10 GM版本 编译问题

### ISSUE THREAD

**Issue by chenfengfeng** [zhuhaow/NEKit#195]
Overlapping accesses to 'data', but modification requires exclusive access; consider copying to a local variable
```swift
open func update( _ data: inout Data) {
        _ = data.withUnsafeMutableBytes {
            CCCryptorUpdate(cryptor, $0, data.count, $0, data.count, nil)
        }
    }
```
NEKit/src/Crypto/CCCrypto.swift最后一个方法报错
其他地方也有类似错误,Xcode对于这个比较严格了,记得之前只是警告

**Comment by zhuhaow** [comment]
Fixed

**Comment by liuyihua2015** [comment]
How can we solve this problem? I also met！
