### ISSUE TITLE
Xcode10编译无法通过

### ISSUE THREAD

**Issue by zezezea** [zhuhaow/NEKit#197]
import NEKit
❗️Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: /Users/xx/Desktop/Rabbit/Carthage/Build/iOS/NEKit.framework/Modules/NEKit.swiftmodule/arm64.swiftmodule

试了 rm -rf ~/Library/Caches/org.carthage.CarthageKit/DerivedData
        carthage update --no-use-binaries --platform iOS

仍然无法解决

**Comment by weqeo** [comment]
我也是，求解决办法

**Comment by zhuhaow** [comment]
用xcode-select选择正确的默认xcode版本

**Comment by weqeo** [comment]
> 用xcode-select选择正确的默认xcode版本

要用之前版本的Xcode跑是吗～

**Comment by zhuhaow** [comment]
> Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler

你保证两个一样就行了，随你想要哪个版本

**Comment by weqeo** [comment]
> > Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler
> 
> 你保证两个一样就行了，随你想要哪个版本

谢谢，还是有点迷，如果要在Xcode10下编译的话，需要执行`carthage update --no-use-binaries --platform ios` 就可以了，对吗～

**Comment by zhuhaow** [comment]
xcode-select 选择你要的xcode版本，运行 `carthage update --no-use-binaries --platform ios` 编译。再打开正确的xcode版本。

**Comment by weqeo** [comment]
> xcode-select 选择你要的xcode版本，运行 `carthage update --no-use-binaries --platform ios` 编译。再打开正确的xcode版本。

thanks~
