### ISSUE TITLE
V2ray support

### ISSUE THREAD

**Issue by ShuoHuang** [zhuhaow/NEKit#199]
hey zhuhaow,

i am using NEKit within my app. now we have a new demand.we need support v2ray.can you add it in NEKit?

**Comment by ShuoHuang** [comment]
how to do it? can you give me a realization process?

**Comment by zhuhaow** [comment]
You can reference anything in AdapterSocket and things calls them.

On 18 Oct 2018, at 13:34, ShuoHuang <notifications@github.com> wrote:

how to do it? can you give me a realization process?

**Comment by Taherismail17** [comment]
I also am trying to do this will Nekit support the WS protocol with Vmess?

**Comment by ShuoHuang** [comment]
> I also am trying to do this will Nekit support the WS protocol with Vmess?

Did you succeed?

**Comment by Taherismail17** [comment]
No @ShuoHuang , Im also trying to implement a method to get shadowsocks to work with udp and all apps - no luck yet

**Comment by huang-ju** [comment]
Did you succeed? @ShuoHuang @Taherismail17

**Comment by lidakang1** [comment]
Shadowsocks is not safe anymore now. It's instantly recognized by G*W.
We need vmess+tls+ws protocol support in NEKit plz. Thanks.  @zhuhaow

**Comment by wfkbyni** [comment]
Did you succeed? @huang-ju @Taherismail17
