### ISSUE TITLE
IPv4Address clase hashValue crash on 32bit cpu under iOS9

### ISSUE THREAD

**Issue by networkextension** [zhuhaow/NEKit#20]
IPAddress.swift 
    public var hashValue: Int {
        return Int(_in_addr.s_addr)
    }
stop reason = EXC_BREAKPOINT (code=EXC_ARM_BREAKPOINT, subcode=0xe7ffdefe)
let r :Int32 = Int32(bitPattern: _in_addr.s_addr)
 return Int(r)

**Comment by networkextension** [comment]
test code

for i in 1 ...  100{
            
            let addr = IPv4Address.init(fromUInt32InHostOrder:(UInt32.max - UInt32(i)))
            print(addr.hashValue)
        }

**Comment by zhuhaow** [comment]
Fixed
