### ISSUE TITLE
Personal VPN

### ISSUE THREAD

**Issue by JosephShenton** [zhuhaow/NEKit#200]
Hey! I was wondering how to setup NEKit as a personal VPN instead of a VPN Configuration?

**Comment by zhuhaow** [comment]
What does personal VPN and configuration mean? If you mean Apple Configuration, you don't have to worry, you can't do it.

**Comment by Ricardo1980** [comment]
I guess he is talking about this:

https://developer.apple.com/documentation/networkextension/netunnelprovidermanager
"VPN configurations created using NETunnelProviderManager are classified as regular enterprise VPN configurations (as opposed to the Personal VPN configurations created by NEVPNManager). Only one enterprise VPN configuration can be enabled on the system at a time. If both a Personal VPN and an enterprise VPN are active on the system simultaneously, the enterprise VPN takes precedence, meaning that if the routes for the two VPNs conflict then the routes for the enterprise VPN will take precedence. The Personal VPN will remain active and connected while the enterprise VPN is active and connected, and any traffic that is routed to the Personal VPN and is not routed to the enterprise VPN will continue to traverse the Personal VPN."

So, the answer is no.
