### ISSUE TITLE
use UDPDNSResolver crush

### ISSUE THREAD

**Issue by ameue** [zhuhaow/NEKit#201]
let resolver = UDPDNSResolver(address: IPAddress(fromString: "114.114.114.114")!, port: NEKit.Port(port: 53))

**Comment by Taherismail17** [comment]
@zhuhaow Also having this crash error

**Comment by FatChou** [comment]
<detail><summary><code>call stack</code><br><pre>
NEKit`UDPDNSResolver.__allocating_init(address:port:):
    0x104592320 <+0>:   stp    x24, x23, [sp, #-0x40]!
    0x104592324 <+4>:   stp    x22, x21, [sp, #0x10]
    0x104592328 <+8>:   stp    x20, x19, [sp, #0x20]
    0x10459232c <+12>:  stp    x29, x30, [sp, #0x30]
    0x104592330 <+16>:  add    x29, sp, #0x30            ; =0x30 
    0x104592334 <+20>:  mov    x22, x1
    0x104592338 <+24>:  mov    x19, x0
    0x10459233c <+28>:  nop    
    0x104592340 <+32>:  ldr    x0, #0xa1e20              ; lazy cache variable for type metadata for NEKit.UDPDNSResolver
    0x104592344 <+36>:  cbnz   x0, 0x104592364           ; <+68> at DNSResolver.swift
    0x104592348 <+40>:  adr    x8, #0xa1e20              ; full type metadata for NEKit.UDPDNSResolver
    0x10459234c <+44>:  nop    
    0x104592350 <+48>:  add    x0, x8, #0x10             ; =0x10 
    0x104592354 <+52>:  bl     0x104609184               ; symbol stub for: swift_getInitializedObjCClass
    0x104592358 <+56>:  adr    x8, #0xa1e08              ; lazy cache variable for type metadata for NEKit.UDPDNSResolver
    0x10459235c <+60>:  nop    
    0x104592360 <+64>:  stlr   x0, [x8]
    0x104592364 <+68>:  mov    w1, #0x28
    0x104592368 <+72>:  orr    w2, wzr, #0x7
    0x10459236c <+76>:  bl     0x104609064               ; symbol stub for: swift_allocObject
    0x104592370 <+80>:  mov    x21, x0
    0x104592374 <+84>:  add    x0, x21, #0x18            ; =0x18 
    0x104592378 <+88>:  str    xzr, [x21, #0x20]
    0x10459237c <+92>:  mov    x1, #0x0
    0x104592380 <+96>:  bl     0x1046092e0               ; symbol stub for: swift_unknownWeakInit
    0x104592384 <+100>: mov    x20, x19
    0x104592388 <+104>: bl     0x1045ede78               ; NEKit.IPAddress.presentation.getter : Swift.String at IPAddress.swift:29
    0x10459238c <+108>: mov    x20, x0
    0x104592390 <+112>: mov    x23, x1
    0x104592394 <+116>: rev    w8, w22
    0x104592398 <+120>: lsr    w22, w8, #16
    0x10459239c <+124>: nop    
    0x1045923a0 <+128>: nop    
    0x1045923a4 <+132>: ldr    x24, #0xa4904             ; static NEKit.Opt.UDPSocketActiveTimeout : Swift.Int
    0x1045923a8 <+136>: mov    x0, #0x0
    0x1045923ac <+140>: bl     0x1045e23a0               ; type metadata accessor for NEKit.NWUDPSocket at <compiler-generated>
    0x1045923b0 <+144>: bl     0x104608fe0               ; symbol stub for: objc_allocWithZone
    0x1045923b4 <+148>: mov    x4, x0
    0x1045923b8 <+152>: mov    x0, x20
    0x1045923bc <+156>: mov    x1, x23
    0x1045923c0 <+160>: mov    x2, x22
    0x1045923c4 <+164>: mov    x3, x24
    0x1045923c8 <+168>: mov    x20, x4
    0x1045923cc <+172>: bl     0x1045e2514               ; NEKit.NWUDPSocket.init(host: Swift.String, port: Swift.Int, timeout: Swift.Int) -> Swift.Optional<NEKit.NWUDPSocket> at NWUDPSocket.swift:43
    0x1045923d0 <+176>: cbz    x0, 0x10459241c           ; <+252> [inlined] NEKit.UDPDNSResolver.init(address: NEKit.IPAddress, port: NEKit.Port) -> NEKit.UDPDNSResolver at DNSResolver.swift:17
    0x1045923d4 <+180>: nop    
    0x1045923d8 <+184>: nop    
    0x1045923dc <+188>: str    x0, [x21, #0x10]
    0x1045923e0 <+192>: ldr    x8, #0xa4908              ; direct field offset for NEKit.NWUDPSocket.delegate : weak Swift.Optional<NEKit.NWUDPSocketDelegate>
    0x1045923e4 <+196>: add    x0, x0, x8
    0x1045923e8 <+200>: adr    x8, #0x8fac8              ; protocol witness table for NEKit.UDPDNSResolver : NEKit.NWUDPSocketDelegate in NEKit
    0x1045923ec <+204>: nop    
    0x1045923f0 <+208>: str    x8, [x0, #0x8]
    0x1045923f4 <+212>: mov    x1, x21
    0x1045923f8 <+216>: bl     0x1046092c8               ; symbol stub for: swift_unknownWeakAssign
    0x1045923fc <+220>: mov    x0, x19
    0x104592400 <+224>: bl     0x104609238               ; symbol stub for: swift_release
    0x104592404 <+228>: mov    x0, x21
    0x104592408 <+232>: ldp    x29, x30, [sp, #0x30]
    0x10459240c <+236>: ldp    x20, x19, [sp, #0x20]
    0x104592410 <+240>: ldp    x22, x21, [sp, #0x10]
    0x104592414 <+244>: ldp    x24, x23, [sp], #0x40
    0x104592418 <+248>: ret    
->  0x10459241c <+252>: brk    #0x1

</pre></summary></detail>

**Comment by ameue** [comment]
I solved this problem

**Comment by ameue** [comment]
Before use UDPDNSResolver, add this 'RawSocketFactory.TunnelProvider = self' in PakectTunnel

**Comment by Taherismail17** [comment]
That fixes the crash but UDP not working

**Comment by Taherismail17** [comment]
@ameue Crash is fixed. UDP Forward doesn't work for me, did you manage to get it to work?
