### ISSUE TITLE
http URL不兼容问题，估计是代码小bug

### ISSUE THREAD

**Issue by android0276** [zhuhaow/NEKit#203]
http://xxxx.com/preview/iframe?id=xxx&cache=|
该域名规则为直连，出错的原因关键在于   cache=|   ，这里不是数字1，是符号|   ， 这会导致直接没法发送请求，请求日志里面也没有任何信息，但是surge和charles是没有此问题的，麻烦作者看一下。

**Comment by android0276** [comment]
作者你可以用这个链接做测试  http://alibaba-inc.com/preview/iframe?id=303714&cache=|

**Comment by zhuhaow** [comment]
这确实是个bug，之前baidu好像也有过，原因是url是不允许出现`|`的。所以并不是这里的bug。

另外，这个东西之前修复过，至于为什么还有问题，你可以研究下 https://github.com/zhuhaow/NEKit/blob/master/src/Utils/HTTPURL.swift 里的逻辑哪里写错了，我最近没有时间。

**Comment by android0276** [comment]
cache=|  做URLencode   cache=%7c就可以

**Comment by android0276** [comment]
好的，感谢

**Comment by android0276** [comment]
原因就是那个|符号没有做url编码，可是我看你这里是个很长的正则表达式，好复杂，不会搞

**Comment by zhuhaow** [comment]
我是无法访问阿里内网的，所以这个链接我测试不了，你自己试试。

**Comment by android0276** [comment]
你已经改好了吗，这么快

**Comment by android0276** [comment]
你改好了我马上试一把

**Comment by zhuhaow** [comment]
好了

**Comment by android0276** [comment]
我拉下来试一把

**Comment by android0276** [comment]
可以了，牛逼

**Comment by zhuhaow** [comment]
这个bug只有在domain有`-`并且没有用https的情况下会触发。我这么多年用下来没发现过问题。充分体现了阿里安全建设的落后……

**Comment by android0276** [comment]
我们的一个页面搭建平台的锅，内网的东西很多都是http，主要明文方便调试，除了对外的会弄成https

**Comment by zhuhaow** [comment]
这个我理解，自己内部的东西基本都是http。但是一般上了 alibaba-inc.com 我感觉就比较正规了，应当直接全站默认 https reverse proxy 的

**Comment by android0276** [comment]
登陆这个搭建平台的时候需要我们的工号绑定的证书才能登录

**Comment by android0276** [comment]
话说我还有个需求, 就是在请求日志里把Http的path路径也打印出来

**Comment by android0276** [comment]
这个复杂吗

**Comment by zhuhaow** [comment]
打不出来，或者你强行改代码，在HTTPProxySocket里面加上log。
要么就接一层 Charles

**Comment by android0276** [comment]
嗯，懂

**Comment by android0276** [comment]
对了我想再问你一个问题，就是我把你这个的 tun2sock 改成了 potasto 的tun2sock，稳定性非常好，手机上几天都不会断开，http在上层走httpProxy就处理了，tcp流量路由是通过 ipv4Settings.excludedRoutes  排除了200条oserv的路由，
我不想用excludedRoutes这个方式，我想用你那个通过自定义DNS 返回 faceip 的方式，可是这个改造似乎非常难，如果我想自己改，成本高吗

**Comment by zhuhaow** [comment]
如果你只是指替换了TCPStack的话那应该是0成本吧。

**Comment by android0276** [comment]
我就替换TcpStack，可是路由这块 FakeIP 这个不好弄，  我又不能全部路由到 tun2sock

**Comment by zhuhaow** [comment]
你是完全用potatso的代码接管了所有packet然后发出去了？那就要大改了。

**Comment by android0276** [comment]
大神，我还想请教一个问题，我想知道某个HTTP代理是由哪个进程发起的，我现在有个思路，就是知道发起请求的源端口，通过源端口查进程id，然后打印进程名。可是这个请求的源端口在哪里能拿到呢，我在HTTPProxySocket里面拿到的已经是代理发起的源端口了，或者你有没有更好的办法达到我想要的效果
