### ISSUE TITLE
swift version error

### ISSUE THREAD

**Issue by manang** [zhuhaow/NEKit#204]
Hi,
I'm trying to compile your code with xcode 10
I have the following error:
Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: NEKit/Carthage/Build/iOS/MMDB.framework/Modules/MMDB.swiftmodule/x86_64.swiftmodule

do you have a solution to build this project?
Thank you very much

**Comment by zhuhaow** [comment]
See #197
