### ISSUE TITLE
这不是issue，如果要想拿到应用发起请求的源端口，需要修改哪个类达到目的

### ISSUE THREAD

**Issue by android0276** [zhuhaow/NEKit#211]
我想根据应用发起的源端口，反查进程id，然后获取进程信息，需要修改哪个类呢，请作者简单说一下，感激

**Comment by zhuhaow** [comment]
这个主要取决于你那了要干什么。可以在任何拿到session的地方反查。

**Comment by android0276** [comment]
我想知道每个请求是由哪一个进程发起的，目前我的思路是查看这个请求发起的源端口，然后根据源端口查到进程id进而获取进程信息

**Comment by android0276** [comment]
大神，你有什么好的思路吗

**Comment by android0276** [comment]
目前不知道nekit里哪里能拿到请求最原始的源端口

**Comment by android0276** [comment]
能大概说下在哪个类里面吗

**Comment by zhuhaow** [comment]
在https://github.com/zhuhaow/NEKit/tree/master/src/Socket/ProxySocket 不就是连上来的

**Comment by android0276** [comment]
还是没理解，是RawTCPSocketProtocol.swift 里的 sourcePort 就是进程发起的源端口吗

**Comment by android0276** [comment]
不过好像不对，我打印过，这个好像是代理后的源端口

**Comment by android0276** [comment]
这个源端口会不会在设置为系统代理那里就托管了，到nekit已经是需要代理后的源端口了

**Comment by android0276** [comment]
不对，我觉得Nekit里一定是能拿到进程源端口的

**Comment by android0276** [comment]
<img width="879" alt="2018-11-13 at 4 30 pm" src="https://user-images.githubusercontent.com/8524130/48400515-7d9bb300-e761-11e8-8c1a-78ab51c9c78b.png">
我又试了一把，确实拿到的是代理后的源端口

**Comment by android0276** [comment]
大神，帮帮我，好复杂

**Comment by zhuhaow** [comment]
什么叫代理后的源端口

**Comment by android0276** [comment]
![image](https://user-images.githubusercontent.com/8524130/48403065-133a4100-e768-11e8-9b0e-cc164166850c.png)
打印出来是这个端口

**Comment by zhuhaow** [comment]
那就试试 https://github.com/robbiehanson/CocoaAsyncSocket/wiki/Reference_GCDAsyncSocket#connectedAddress 里的 connectedHost 和 connectedPort ？你可以直接看一下底层的socket包裹的实现里的port。

**Comment by android0276** [comment]
谢谢大神，根据你提供的这个gcdsocket文档我已经解决了
