### ISSUE TITLE
关于UDPDirectStack转发UDP疑问

### ISSUE THREAD

**Issue by ameue** [zhuhaow/NEKit#214]
看到转发是用findOrCreateSocketForPacket方法读取pacektFlow封装的IPPacket对象，创建NWUDPSocket对象转发的，这个NWUDPSocket是IPPacket用读出来的destinationAddress创建的，疑问：
destinationAddress是用pacektFlow读出来的UDP数据的目的地址，那么是从本地直接转发到目的服务器，没有转发到配置的ss服务器吗？

**Comment by zhuhaow** [comment]
没有

**Comment by ameue** [comment]
如果改造的话，可以哪里入手呢？可以给点思路吗

**Comment by ameue** [comment]
转发之前，再封装个socks5的头部？

**Comment by zhuhaow** [comment]
这取决于你要怎么发了，根据你想要的协议封装

On 22 Nov 2018, at 09:59, Popeye <notifications@github.com> wrote:

转发之前，再封装个socks5的头部？
