### ISSUE TITLE
Swift 4 Support 

### ISSUE THREAD

**Issue by TheMrugraj** [zhuhaow/NEKit#218]
Not able to move ahead after `carthage update` due to the Incompatible version of Swift for two libraries.
- Resolver
- Tun2Socks

```Skipped installing Resolver.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1) and the local version is 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)."
*** Downloading tun2socks.framework binary at "0.6.1"
*** Skipped installing tun2socks.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1) and the local version is 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)."```

Is there any idea on how to get NEKit running.

**Comment by zhuhaow** [comment]
Does this work?

carthage update --no-use-binaries --platform mac,ios

**Comment by TheMrugraj** [comment]
No it does not work. Still facing the same issue

**Comment by zhuhaow** [comment]
Sorry for the late reply. I just tried `carthage update --no-use-binaries --platform mac,ios` and it works. It's not likely you will see the same error if you use `--no-use-binaries` since there is no binaries used, so there can't be error as "framework was built with 3.0.1"
