### ISSUE TITLE
unresolved identifier 

### ISSUE THREAD

**Issue by lljxx1** [zhuhaow/NEKit#219]
i'm new to ios, i don't know how to fix this error
please help! thanks a lot.
xcode 9.2
<img width="1680" alt="2018-11-24 2 51 55" src="https://user-images.githubusercontent.com/7993835/48965481-eb18d080-eff8-11e8-95e9-2f5266291a13.png">

**Comment by zhuhaow** [comment]
You are not correctly referencing the dependencies. You should look up how to work with Carthage.

On 24 Nov 2018, at 14:55, fun <notifications@github.com> wrote:

i'm new to ios, i don't know how to fix this error
please help! thanks a lot.
xcode 9.2

**Comment by zhuhaow** [comment]
The demo may be outdated. Please refer to code and doc for the latest api

**Comment by lljxx1** [comment]
**IPv4Address** change to **IPAddress**
works.
