### ISSUE TITLE
iOS 12.1 'Update Required'

### ISSUE THREAD

**Issue by JosephShenton** [zhuhaow/NEKit#220]
Hi, upon adding the VPN to an iOS 12.1 device you get the message update require for the vpn. See the attached screenshot.

You can find the code we use here: https://github.com/useignition/Lazarus

Any help would be appreciated.
![img-0802](https://user-images.githubusercontent.com/12966231/49057101-50b3c980-f252-11e8-93c6-060683798a73.JPG)

**Comment by zhuhaow** [comment]
I'm not sure. Have you tried to reinstall it with Xcode?

**Comment by JosephShenton** [comment]
Yes

**Comment by zhuhaow** [comment]
I don’t know why this happens and I don’t have time to test that right now. If you ever find the solution, please kindly post it here. I’ll try when I have time next week
