### ISSUE TITLE
Can we monitor the MimeType?

### ISSUE THREAD

**Issue by TheMrugraj** [zhuhaow/NEKit#225]
Can we monitor the MimeTypes of Response? I actually want to check if the Response Mimetype is any specific type e.g. "application/pdf" than want to count the number of PDF has been downloaded via Proxy.

**Comment by TheMrugraj** [comment]
> nekit-rs

Can you please share any doc or resource to refer this?

**Comment by zhuhaow** [comment]
I don’t have doc for this yet. I haven’t tried to use this on iOS also.

But the code shouldn’t be difficult to understand.

在 2019年1月1日，21:14，Mrugrajsinh Vansadia <notifications@github.com> 写道：

nekit-rs

Can you please share any doc or resource to refer this?
