### ISSUE TITLE
App Store Connect Operation Error - CFBundleVersion and CFBundleShortVersionString Missing

### ISSUE THREAD

**Issue by TheMrugraj** [zhuhaow/NEKit#227]
I am not sure whether this is the issue from due to Carthage or NEKit as I tried to check few threads of Carthage and people are saying that this was the issue previously but in the newer version, it's been fixed on PR. So, reporting this issue here.

![image](https://user-images.githubusercontent.com/6426983/50628694-38c11b00-0f5f-11e9-866c-0d831f238cb0.png)

**Comment by TheMrugraj** [comment]
For now, I have fixed this by manually editing the `info.plist` of Framework

**Comment by cheenbee** [comment]
NEKit的info.plist中的版本号不符合苹果规定的版本号规则,修改成三段式最好,1.0.0即可

**Comment by stevelyc** [comment]
现在这里的bug没有解决，修改成1.0.0还是会报错。能说下具体操作吗

**Comment by alsojin** [comment]
手动改 issues 里面也有这个的解决方案

**Comment by TheMrugraj** [comment]
Closing this issue. 
Because versioning is happening using the most recent Tag in your Git.
So, if your Tag is 1.0.1 then it will use the same value as Version. So no need to set manually but, give Tag name carefully and make sure its Positive Integer separated using `.` Otherwise, you may face the issue in App submission.

Please refer https://github.com/zhuhaow/NEKit/issues/257
