### ISSUE TITLE
Carthage update error : CocoaLumberjackSwift-watchOS 

### ISSUE THREAD

**Issue by newpgt** [zhuhaow/NEKit#230]
A shell task (/usr/bin/xcrun xcodebuild -project /Users/XXXXX/Desktop/swift4Tested/RabbitVpnDemo-master/Carthage/Checkouts/CocoaLumberjack/Lumberjack.xcodeproj -scheme CocoaLumberjackSwift-watchOS -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme CocoaLumberjackSwift-watchOS is not currently configured for the build action.

Carthage update won't work! (Xcode Version 10.1 (10B61))

**Comment by zhuhaow** [comment]
You are building for watchOS which is not supported.

**Comment by newpgt** [comment]
> You are building for watchOS which is not supported.
> […](#)

I am not building for watchOS.
 Just download https://github.com/yichengchen/RabbitVpnDemo , and use the command:
carthage update --no-use-binaries --platform ios
The error popup.
And also tried to use a cartfile in an empty folder, run carthage update --no-use-binaries --platform ios, still Not installed with Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory". I've already clear DerivedData folder.

**Comment by zhuhaow** [comment]
You need do double check about the log. At least "No such file or directory" doesn't seem like a reasonable error.

**Comment by newpgt** [comment]
Problem found. It seems that the repository of “CocoaLumberjackSwift.framework” is no longer exist. Wondering if CocoaLumberjackSwiftHelper is the same?

**Comment by zhuhaow** [comment]
How can that be? Even in the latest CocoaLumberjack this project is still present, not to mention the version is fixed in Cartfile.

**Comment by newpgt** [comment]
Somehow the error shows that "The file “CocoaLumberjackSwift.framework” couldn’t be opened because there is no such file." on my iMac and MacBook. 
Could you just try to use Carthage just NEKit in a new folder, to see if it can go through? (my Xcode Version 10.1 (10B61))

**Comment by zhuhaow** [comment]
Just tried with XCode 10, everything works fine.

**Comment by newpgt** [comment]
Problem solved!
Just update Carthage version from 0.16.0 to 0.32.0
Thanks for your patient!
