### ISSUE TITLE
How to create socket5 TLS connection via VPN ?

### ISSUE THREAD

**Issue by dddeee2004** [zhuhaow/NEKit#231]

**Comment by zhuhaow** [comment]
See how HTTPSAdapter is implemented

**Comment by dddeee2004** [comment]
Thank you ,Now I am using SecuretHTTPAdapter for the tls proxy servery,but I can not find where the certificate set,here is my code for your reference:
    let auth = NEKit.HTTPAuthentication.init(username: "", password: "")
    let securtehttpadapter = SecureHTTPAdapterFactory.init(serverHost: "10.168.1.243", serverPort: 8801, auth: auth)

服务器端会报错:
2019/03/19 13:51:01 handshake fail, ERR: new methods request fail,ERR: remote error: tls: unknown certificate
应该是证书没有。请问如何设置证书？谢谢
