### ISSUE TITLE
Carthage Fails Xcode 10.2

### ISSUE THREAD

**Issue by Taher-17** [zhuhaow/NEKit#232]
Building scheme "Resolver-iOS" in Resolver.xcodeproj
Build Failed
	Task failed with exit code 65:

Did: `carthage update --no-use-binaries --platform ios`
Xcode: 10.2
Swift 5

**Comment by zhuhaow** [comment]
Could you provide any error log?

**Comment by Taher-17** [comment]
Terminal

`Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/xxxx/Desktop/Stealth-VPN/Stealth\ VPN/Carthage/Checkouts/MMDB-Swift/MMDB.xcodeproj -scheme MMDB-iOS -configuration Release -derivedDataPath /Users/xxxx/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10P107d/MMDB-Swift/0.2.9 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/42/6ym0nw_55ydb4ptyqy17qd_80000gn/T/MMDB-Swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/xxxx/Desktop/Stealth-VPN/Stealth VPN/Carthage/Checkouts/MMDB-Swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/42/6ym0nw_55ydb4ptyqy17qd_80000gn/T/carthage-xcodebuild.CukLOE.log`

Build fails for MMDB for Swift 5.

Log File:
`** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/xxxx/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10P107d/MMDB-Swift/0.2.9/Build/Intermediates.noindex/ArchiveIntermediates/MMDB-iOS/IntermediateBuildFilesPath/MMDB.build/Release-iphoneos/MMDB-iOS.build/Script-366F5FDD1F05152C00DE3883.sh
(1 failure)`

**Comment by zhuhaow** [comment]
> Terminal
> 
> `Build Failed
> Task failed with exit code 65:
> /usr/bin/xcrun xcodebuild -project /Users/xxxx/Desktop/Stealth-VPN/Stealth\ VPN/Carthage/Checkouts/MMDB-Swift/MMDB.xcodeproj -scheme MMDB-iOS -configuration Release -derivedDataPath /Users/xxxx/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10P107d/MMDB-Swift/0.2.9 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/42/6ym0nw_55ydb4ptyqy17qd_80000gn/T/MMDB-Swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/xxxx/Desktop/Stealth-VPN/Stealth VPN/Carthage/Checkouts/MMDB-Swift)
> 
> This usually indicates that project itself failed to compile. **Please check the xcodebuild log for more details: /var/folders/42/6ym0nw_55ydb4ptyqy17qd_80000gn/T/carthage-xcodebuild.CukLOE.log`**
> 
> Build fails for MMDB for Swift 5.
> 
> Log File:
> `** ARCHIVE FAILED **
> 
> The following build commands failed:
> PhaseScriptExecution Run\ Script /Users/xxxx/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10P107d/MMDB-Swift/0.2.9/Build/Intermediates.noindex/ArchiveIntermediates/MMDB-iOS/IntermediateBuildFilesPath/MMDB.build/Release-iphoneos/MMDB-iOS.build/Script-366F5FDD1F05152C00DE3883.sh
> (1 failure)`
