### ISSUE TITLE
Xcode 10.2 无法编译通过

### ISSUE THREAD

**Issue by android0276** [zhuhaow/NEKit#235]
今天 Xcode 自动升级了10.2，编译不通过

**Comment by qyb** [comment]
https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes 里面有一个关于 swift 的 known issue...

**Comment by android0276** [comment]
早知道我应该关闭 Xcode 自动升级的

**Comment by zhuhaow** [comment]
Fixed. 

But I changed quite a lot code involving dealing with raw buffer. You should test it thoroughly before put into prod.
