### ISSUE TITLE
carthage 导入失败  环境：Xcode10.2 Swift 5.0

### ISSUE THREAD

**Issue by LuckyTyga** [zhuhaow/NEKit#236]
Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos12.0
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'Resolver-iOS')

Build system information
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'Resolver-iOS')

** ARCHIVE FAILED **

**Comment by zhuhaow** [comment]
Are you using the latest version? It should have been fixed.

**Comment by LuckyTyga** [comment]
ok ,  its worked
