### ISSUE TITLE
Module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler:

### ISSUE THREAD

**Issue by owenwatts** [zhuhaow/NEKit#237]
Do you have solve this problem in swift 5?

**Comment by zhuhaow** [comment]
Are you compiling all dependencies with --no-use-binaries?

**Comment by owenwatts** [comment]
yes, i update package by the command, but that's not work.
`
carthage update --no-use-binaries --platform ios
`

**Comment by zhuhaow** [comment]
Try to clean up Carthage cache then try again.

**Comment by owenwatts** [comment]
still not work...

> Module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler: /Users/xx/www/explore/xx/Carthage/Build/iOS/NEKit.framework/Modules/NEKit.swiftmodule/x86_64.swiftmodule

**Comment by zhuhaow** [comment]
Are you using the latest version?

**Comment by owenwatts** [comment]
yes.
Carthage version 0.32
NEKit version 0.14

**Comment by owenwatts** [comment]
I have solve the problem by reinstall the carthage, thx at all.
