### ISSUE TITLE
Errors happen after using latest repo and Xcode 10.2 (swift 5)

### ISSUE THREAD

**Issue by shanda9799** [zhuhaow/NEKit#239]
warning: Swift error in scratch context: <module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/MMDB.h"
        ^

/Users/ShadowSocketSimple/Carthage/Build/iOS/MMDB.framework/Headers/MMDB.h:19:9: note: in file included from /Users/VPN/ios/ShadowSocketSimple/Carthage/Build/iOS/MMDB.framework/Headers/MMDB.h:19:
#import <MMDB/maxminddb.h>
        ^

/Users/ShadowSocketSimple/Carthage/Build/iOS/MMDB.framework/Headers/maxminddb.h:36:10: note: in file included from /Users/ShadowSocketSimple/Carthage/Build/iOS/MMDB.framework/Headers/maxminddb.h:36:
#include <netdb.h>
         ^

error: /Users/ShadowSocketSimple/Carthage/Checkouts/tun2socks/lwip/lwip/netdb.h:32:10: error: 'lwip/opt.h' file not found
#include "lwip/opt.h"
         ^

error: could not build Objective-C module 'MMDB'
.
Shared Swift state for PacketTunnel has developed fatal errors and is being discarded.
REPL definitions and persistent names/types will be lost.

**Comment by shanda9799** [comment]
VPN is showed connected on the device but traffic cannot be tunnelled.

**Comment by zhuhaow** [comment]
How do you manage to get things up and running while the compilation fails?

**Comment by shanda9799** [comment]
It does automatically by itself

**Comment by shanda9799** [comment]
I think the issue is caused by delayed upgrade of MMDB.

**Comment by zhuhaow** [comment]
Is it solved?

**Comment by shanda9799** [comment]
solved by deleting the DerivedData

**Comment by cimonk** [comment]
OOPS! I met this issue again, I use Xcode 11.1.
I already deleted the DerivedData, but it doesn't work.
