### ISSUE TITLE
Line Whatsapp Viber Telegram Netflix这些软件都不能使用nekit，请问怎么解决

### ISSUE THREAD

**Issue by gaga227** [zhuhaow/NEKit#242]

**Comment by gaga227** [comment]
Line Whatsapp Viber Telegram Netflix 这些app都不能使用nekit链接，请问有办法解决嘛？

**Comment by 493441755** [comment]
@gaga227  解决了吗

**Comment by gaga227** [comment]
还没有

**Comment by gaga227** [comment]
你的nekit还能跑起来吗？

**Comment by 493441755** [comment]
跑起来没问题，除了Telegram等部分即时通讯APP链接不上外 其他的都OK

**Comment by 493441755** [comment]
在telegram里面通过nekit socke5代理 connecting过了  但是一直Updating

**Comment by weqeo** [comment]
same

**Comment by candiceatwb** [comment]
@zhuhaow 这个问题有办法解决吗？正在研究这块，又遇到了telegram 连接不上的问题。

**Comment by zhuhaow** [comment]
telegram是因为它会发送一个支持用户名密码的验证选项，NEKit在这里处理的很粗糙，直接断开了，改一下code就好了。其他的估计都没走代理吧

**Comment by weqeo** [comment]
> telegram是因为它会发送一个支持用户名密码的验证选项，NEKit在这里处理的很粗糙，直接断开了，改一下code就好了。其他的估计都没走代理吧

请问下该如何入手呢，谢谢～

**Comment by weqeo** [comment]
> telegram是因为它会发送一个支持用户名密码的验证选项，NEKit在这里处理的很粗糙，直接断开了，改一下code就好了。其他的估计都没走代理吧

您好，我也遇到了同样的问题，请问code要如何改呢？十分感谢！
