### ISSUE TITLE
Make Proxy in View Controller

### ISSUE THREAD

**Issue by Taher-17** [zhuhaow/NEKit#244]
Hey,

Is it possible to make the proxy on 192.168.1.xxx in the View Controller to connect on another device?
I don't want to use PacketTunnel, just create a Shadowsocks proxy in the View Controller to connect manually on another device

`var proxyServer: ProxyServer!
        
        proxyServer = GCDHTTPProxyServer(address: IPAddress(fromString: LOCAL_IP), port: NEKit.Port(port: UInt16(1082)))
        
        try! proxyServer.start()`

**Comment by zhuhaow** [comment]
What do you want to archive? The scenario you described does not make too much sense. If you want other device to connect to your device, just start a normal listening server. And it has nothing to do with view controller any way.

在 2019年5月1日，09:57，Taher-17 <notifications@github.com> 写道：

Hey,

Is it possible to make the proxy on 192.168.1.xxx in the View Controller to connect on another device?
I don't want to use PacketTunnel, just create a Shadowsocks proxy in the View Controller to connect manually on another device

`var proxyServer: ProxyServer!

    proxyServer = GCDHTTPProxyServer(address: IPAddress(fromString: LOCAL_IP), port: NEKit.Port(port: UInt16(1082)))
    
    try! proxyServer.start()`

**Comment by Taher-17** [comment]
I want my application to host a GCDHTTPProxyServer but not connect to shadowsocks as a VPN
Then I want to connect to OpenVPN using my app (I have done this)
I want to add this to my OpenVPN Config http-proxy 127.0.0.1 9090 so I can connect to OpenVPN through the Shadowsocks Tunnel.

The issue with using PacketTunnel is when I start connection to OpenVPN listener on 127.0.0.1:9090 disconnects.

1. Start Shadowsocks in app on 127.0.0.1
2. Connect to OpenVPN with proxy
3. Disconnect Shadowsocks now that the blocked OpenVPN server is already connected

**Comment by zhuhaow** [comment]
I don’t get much of what you want to do, can you clarify what exactly you want and how many devices are involved?

在 2019年5月1日，14:14，Taher-17 <notifications@github.com> 写道：

I want my application to host a GCDHTTPProxyServer but not connect to shadowsocks as a VPN
Then I want to connect to OpenVPN using my app (I have done this)
I want to add this to my OpenVPN Config http-proxy 127.0.0.1 9090 so I can connect to OpenVPN through the Shadowsocks Tunnel.

The issue with using PacketTunnel is when I start connection to OpenVPN listener on 127.0.0.1:9090 disconnects.

Start Shadowsocks in app on 127.0.0.1
Connect to OpenVPN with proxy
Disconnect Shadowsocks now that the blocked OpenVPN server is already connected

**Comment by Taher-17** [comment]
DEVICE A: Create Shadowsocks listener
DEVICE B: Enter proxy details here
![IMG_56B70201CAB8-1](https://user-images.githubusercontent.com/46544295/57007566-afd09c80-6c3d-11e9-8ad3-d0bd016a0b73.jpeg)

Rules: DEVICE A needs to add a listener(local_host:9090) without PacketTunnel or VPN Connection

**Comment by zhuhaow** [comment]
But what’s the point? The http://p.getqujing.com/paths/40ief5qh.pac server you start on device A will be killed when the app go background.

在 2019年5月1日，14:21，Taher-17 <notifications@github.com> 写道：

DEVICE A: Create Shadowsocks listener
DEVICE B: Enter proxy details here


Rules: DEVICE A needs to add a listener(local_host:9090) without PacketTunnel or VPN Connection

**Comment by Taher-17** [comment]
1. Device A is used as a Hotspot for multiple devices
2. Device A and Device B can use OpenVPN through Shadowsocks 
Example: https://www.tipsforchina.com/how-to-tunnel-expressvpn-over-shadowsocks-for-increased-speed-from-china.html

**Comment by zhuhaow** [comment]
If I still get things correct (I’m not expert on iOS development), the hotspot creates an isolated WiFi where the connected device cannot connect to anything on the host device.

Also, the server on device A will be killed when device go to sleep or switch to background.

在 2019年5月1日，14:24，Taher-17 <notifications@github.com> 写道：

Device A is used as a Hotspot for multiple devices
Device A and Device B can use OpenVPN through Shadowsocks
Example: https://www.tipsforchina.com/how-to-tunnel-expressvpn-over-shadowsocks-for-increased-speed-from-china.html

**Comment by Taher-17** [comment]
Thanks for your help.
