### ISSUE TITLE
捕获所有App的请求数据

### ISSUE THREAD

**Issue by ShuailongWang** [zhuhaow/NEKit#246]
我没有服务器，我只想开启vpn代理，然后捕获所有App的请求数据，这样的可以吗？

**Comment by qyb** [comment]
可以，用 DirectAdapter 就是直连

**Comment by ShuailongWang** [comment]
@qyb 
我打印输出， 只能输出Adress, host， Rule
我想输出更加多的详细的信息

**Comment by ShuailongWang** [comment]
@qyb 多谢回复
我打印输出， 只能输出Adress, host， Rule
我想输出更加多的详细的信息

**Comment by chenfengfeng** [comment]
@ShuailongWang 你好，你找到怎么输出其他日志的方法了吗？
