### ISSUE TITLE
连接不上

### ISSUE THREAD

**Issue by sysbol** [zhuhaow/NEKit#249]
我配置好证书后 能编译成功 但连接不上 ，使用的是basictest版
off
connect tap
connecting
off

请问还需要哪些配置吗

**Comment by zhuhaow** [comment]
basictest版是什么

**Comment by sysbol** [comment]
就是 你git上说的呀 不用导入NEKit 只是测试vpn连接的分支

在 2019-06-12 17:04:42，"zhuhaow" <notifications@github.com> 写道：


basictest版是什么

**Comment by zhuhaow** [comment]
不是很理解你指的是什么。
git哪个repo？哪里可以不导入NEKit？测试vpn连接的是哪个分支？

**Comment by sysbol** [comment]
应该是我的问题，nekit没安装好 ，请问我们的vpn服务器有多个，提供 vpn的ip 跟端口号，还有用户名跟密码 ，没有认证证书啥的，请问我应该用那种方式开发network extension 连接 vpn开发刚接触 是小白 求解 谢谢

在 2019-06-13 09:21:32，"zhuhaow" <notifications@github.com> 写道：


不是很理解你指的是什么。
git哪个repo？哪里可以不导入NEKit？测试vpn连接的是哪个分支？

**Comment by zhuhaow** [comment]
我也不知道……
你可能需要补一下基础什么的吧

**Comment by sysbol** [comment]
好的 谢谢

在 2019-06-13 10:10:50，"zhuhaow" <notifications@github.com> 写道：


Closed #249.
