### ISSUE TITLE
在ios上网络类型图标不更新的问题？

### ISSUE THREAD

**Issue by gaotong2055** [zhuhaow/NEKit#25]
非常强大的工具，用来做ss代理很方便，我在ios上写一个简单的demo，配置的ss代理，启动vpn正常，也能连上。但是，在开启vpn时，系统状态栏的网络图标不会更新。比如，我开着Wi-Fi打开VPN，然后关掉Wi-Fi，正常情况下，网络图标应该显示“3G”（可以确认这时用的是3G网络），但还是显示Wi-Fi图标，关掉VPN后，图标立马恢复了正常。知道这是什么问题吗？

**Comment by zhuhaow** [comment]
不知道……

**Comment by YzsXQ** [comment]
@gaotong2055 能看看你的iOS Demo吗! 最近也在研究。

**Comment by zhuhaow** [comment]
没有iOS demo

Zhuhao Wang

2016年11月7日 +0800 17:20 YzsXQ <notifications@github.com>，写道：

**Comment by humiaozuzu** [comment]
开了 tun 会有这个问题

**Comment by CoderJin** [comment]
这个问题 我也遇到了 ..

**Comment by zhuhaow** [comment]
显然和NEKit是无关的，你们可以继续讨论

**Comment by gaotong2055** [comment]
找到问题了，关了这个就没事了，原因是？谁来解答下，多谢！
if enablePacketProcessing {
            let DNSSettings = NEDNSSettings(servers: ["198.18.0.1"])
            DNSSettings.matchDomains = [""]
            DNSSettings.matchDomainsNoSearch = false
            networkSettings.DNSSettings = DNSSettings
        }

**Comment by CoderJin** [comment]
不是这个吧

**Comment by gaotong2055** [comment]
不知道，反正是work了，不知道这个DNSSettings怎么用

**Comment by CoderJin** [comment]
我刚才测试了一下 不行 啊..难道 删除 App 在测试

**Comment by jackyzh** [comment]
感觉这是 iOS 的 bug，这种事情不应该由开发者来处理。

解决办法是用 KVO 监视 defaultPath 的变化， 网络环境变化时重新 setTunnelNetworkSettings
