### ISSUE TITLE
xcode 10.1 carthage fails

### ISSUE THREAD

**Issue by candiceatwb** [zhuhaow/NEKit#250]
*** Building scheme "CocoaLumberjackSwift" in Demos.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/yangqin/iosworkspace/RabbitVpnDemo/Carthage/Checkouts/CocoaLumberjack/Demos/Demos.xcworkspace -scheme CocoaLumberjackSwift -configuration Release -derivedDataPath /Users/yangqin/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/CocoaLumberjack/3.5.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/d8/mm07v3pd5qg_prnrfrv4qbh80000gn/T/CocoaLumberjack SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/yangqin/iosworkspace/RabbitVpnDemo/Carthage/Checkouts/CocoaLumberjack)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/d8/mm07v3pd5qg_prnrfrv4qbh80000gn/T/carthage-xcodebuild.qIIc0e.log

**Comment by candiceatwb** [comment]
open /var/folders/d8/mm07v3pd5qg_prnrfrv4qbh80000gn/T/carthage-xcodebuild.qIIc0e.log
find the error:
Build system information
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'CocoaLumberjackSwift')

**Comment by liuyihua2015** [comment]
I have this problem now? How to solve it? Who can help me?

**Comment by candiceatwb** [comment]
Hi ,
Your xcode version is also 10.1? do you try on other versions?

**Comment by zhuhaow** [comment]
What version of NEKit are you using, it should support swift 5.

**Comment by candiceatwb** [comment]
@zhuhaow Thanks, I use xcode11 , carthage running successfully.

**Comment by liuyihua2015** [comment]
我的 Cartfile 文件内容是  "  github "https://github.com/zhuhaow/NEKit"  "
carthage版本最新的0.33.0  还是报错，错误log信息如下：

=== BUILD TARGET CocoaLumberjackSwift OF PROJECT Lumberjack WITH CONFIGURATION Release ===

Check dependencies
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

** ARCHIVE FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

**Comment by candiceatwb** [comment]
@liuyihua2015  , The content of my Cartfile is " github "zhuhaow/NEKit" " and the carthage version is also 0.33.0.

**Comment by liuyihua2015** [comment]
Thanks, I use xcode10.2.1 , carthage running failure. Or the above question；

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/liuyihua/ios-gspeed(普通版2.0)/Carthage/Checkouts/CocoaLumberjack/Demos/Demos.xcworkspace -scheme CocoaLumberjackSwift -configuration Release -derivedDataPath /Users/liuyihua/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4_9F1027a/CocoaLumberjack/3.5.3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/jp/dhw5h4v1077ct86vs5_tgc9r0000gn/T/CocoaLumberjack SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/liuyihua/ios-gspeed(普通版2.0)/Carthage/Checkouts/CocoaLumberjack)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/jp/dhw5h4v1077ct86vs5_tgc9r0000gn/T/carthage-xcodebuild.AbG7ba.log

    /bin/chmod -RH u+w,go-w,a+rX /Users/liuyihua/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4_9F1027a/CocoaLumberjack/3.5.3/Build/Intermediates.noindex/ArchiveIntermediates/CocoaLumberjackSwift/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaLumberjack.framework

=== BUILD TARGET CocoaLumberjackSwift OF PROJECT Lumberjack WITH CONFIGURATION Release ===

Check dependencies
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

** ARCHIVE FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

**Comment by candiceatwb** [comment]
Does your xcode support "swift 5.0" ?

**Comment by liuyihua2015** [comment]
10.2.1是支持swift的！不行，明天我升级到11试试看吧


发自我的iPhone

------------------ Original ------------------

**Comment by Taher-17** [comment]
Same issue Xcode 11, macOS Catalina

**Comment by liuyihua2015** [comment]
I found the problem. There are two xcodes in the project, one is Xcode 9.4, and the other is Xcode 10.2. The Command Line Tools in the Locations of preferences of Xcode are wrong, so it's no problem to change to Xcode 10. Thank you.

**Comment by candiceatwb** [comment]
@liuyihua2015 sorry , I ignored this issue yesterday, If you have multiple versions of Xcode on your mac, you need to change the default xcode version via the " sudo xcode-select --switch "xcode path" "command.

**Comment by liuyihua2015** [comment]
That's all right. Thank you. Fortunately, I found and solved the problem.
