### ISSUE TITLE
大佬，有没有OC版的啊？

### ISSUE THREAD

**Issue by wdq123550** [zhuhaow/NEKit#251]
RT

**Comment by zhuhaow** [comment]
swift应当有和oc足够的interoperability，可能有的地方没有加@objc，可以自己加一下

**Comment by wdq123550** [comment]
不是，我说的是有没有OC版的NEKit

**Comment by wdq123550** [comment]
有没有打算搞一波OC版的NEKit啊？

**Comment by zhuhaow** [comment]
为什么我要用一个即将淘汰的语言重写一个完全没有任何优点而且和现有功能一模一样的东西

**Comment by wdq123550** [comment]
呵呵，大佬你开心就行。谁让你是大佬呢是吧，大佬你随意
