### ISSUE TITLE
如何支持其他加密方式？

### ISSUE THREAD

**Issue by wdq123550** [zhuhaow/NEKit#255]
public enum CryptoAlgorithm : String {

    case AES128CFB

    case AES192CFB

    case AES256CFB

    case CHACHA20

    case SALSA20

    case RC4MD5
}

除了这些，还支持别的加密方式吗？

**Comment by zhuwudan** [comment]
楼主知道了么

**Comment by wdq123550** [comment]
没有啊，开发人员没回我

**Comment by zhuhaow** [comment]
总是可以自己实现加密算法的，提供的都列在enum里了

在 2019年7月10日，11:51，wdq123550 <notifications@github.com> 写道：

没有啊，开发人员没回我
