### ISSUE TITLE
智能代理和全局代理如何配置？

### ISSUE THREAD

**Issue by wdq123550** [zhuhaow/NEKit#256]
还有就是SSR的协议混淆怎么设置？

**Comment by wdq123550** [comment]
let obfuscater = ShadowsocksAdapter.ProtocolObfuscater.HTTPProtocolObfuscater.Factory(hosts:["intl.aliyun.com","cdn.aliyun.com"], customHeader:nil)
     
let obfuscater = ShadowsocksAdapter.ProtocolObfuscater.OriginProtocolObfuscater.Factory()

大佬，这两个obfuscater有什么区别吗？
好像是设置混淆的，有什么区别吗？

**Comment by zhuhaow** [comment]
细节可以自己过一下代码，我也不记得了

**Comment by chinsyo** [comment]
@wdq123550 
通常意义的智能代理都是通过 PAC，这个框架不支持 PAC 配置。自己在 Rule 里面声明的白名单走代理，Country != CN 走代理，DNSFail 走代理就约等于智能代理了。全局代理就是无条件转发。

上面那个是将报文伪装成 HTTP 报文，下面的做法是不伪装。
