### ISSUE TITLE
SetVersion script is setting invalid Version String

### ISSUE THREAD

**Issue by TheMrugraj** [zhuhaow/NEKit#257]
Archiving is failing because of the invalid value of `CFBundleShortVersionString`
I found the value of Short Version in Built framework was QA(1.1.0) which was creating the issue and after invastigating, I came to know that it's because of the Set Version number Script.

![Monosnap 2019-07-31 19-42-31](https://user-images.githubusercontent.com/6426983/62232875-e6f14e00-b3e4-11e9-8f3d-480bff5bef72.jpg)

![image](https://user-images.githubusercontent.com/6426983/62235123-df807380-b3e9-11e9-8dcc-1ce885cd5bd6.png)

**Comment by zhuhaow** [comment]
Are you creating a tag yourself with that name? In that case, can you use another name that is valid?

Setting the version base on the current tag turns out to be not ideal, but I don't have enough bandwidth for this project for a better solution.

**Comment by TheMrugraj** [comment]
Nope. I have not created any Tag myself.

Thanks,

**Comment by zhuhaow** [comment]
It must be coming from somewhere then, is there any tag in your project repo?

**Comment by TheMrugraj** [comment]
Strange! the Tag which its using is 2 months older one. And for earlier release it never created the issue. Can't we disable the script as I am already setting version to my project.

**Comment by TheMrugraj** [comment]
Yes @zhuhaow  You were right, In the script, It was fetching the most recent Tag for versioning. 
Thanks, It's resolved. but, still, I am not sure why the issue never arose in past releases.

Thanks once again. 
NEKit Rocks 🤘
