### ISSUE TITLE
NEKit  Deployment target 9.3 

### ISSUE THREAD

**Issue by mengke0612** [zhuhaow/NEKit#258]
hello:
       Can you change the minimum supported version to 9.0? thanks

**Comment by zhuhaow** [comment]
I don't recall if there is an issue preventing setting the target to 9.0 so I won't do it. You can try for yourself and use your own folk.

**Comment by mengke0612** [comment]
![DECD9C6A-A70B-4444-A676-CDC9FF86B697](https://user-images.githubusercontent.com/15834014/62842539-73551800-bce5-11e9-9886-c3584b8a2df9.png)

**Comment by zhuhaow** [comment]
You can fork NEKit and use it with Carthage. I'm not going to do it since I'm not sure if that would break anything.

BTW, I can't think of a possible reason why you want to compile for 9.0
