### ISSUE TITLE
What can be possible reason of failure in Tunneling Requests of some domains

### ISSUE THREAD

**Issue by TheMrugraj** [zhuhaow/NEKit#260]
Last week I came across a very strange case, I was basically trying to tunnel traffic through my proxy server but, then I realized that request of some specific domains is not going via my proxy service. After investigating I found that, Requests are not even visible in Network Tab of Safari browser. 

Let me try to explain the case with one of the URL;
https://www.sciencedirect.com/

If I open this URL in Safari, in Network tab I don't see any document request pointing to the domain sciencedirect.com but, if I try the same thing in Chromium, I can see doc requests specifically for ScienceDirect.(I tried after each type of cache clearance method so, its not the reason ;) ) So, one of the reasons I assumed was that, since the Website has been built in such a way maybe because of WebSocket or something, Its not using  document request pointing to sciencedirect.com and that's why those requests are not going through my proxy server.  

To double-check and validate my assumption I tried to put a manual proxy config in wifi settings of the device and then observed the logs on the server. I was able to see those request and things worked perfectly as expected. however in Network tab, I could not see any requests this time as well so, I figured out that the Network Tab's URL is not a reliable way to make the decision in this case. so, now I feel that its something related to my Network Extension built using NEKit.

So, Can anyone please help by suggesting any solution to find what can be the possible reason for failure in Tunneling requests of specific domain whereas I have already added that domains in `matchDomains` of `NEProxySettings` so, just like other domains where things are working smoothly it should work for sciencedirect.com as well.

**Comment by zhuhaow** [comment]
I don't think websocket or anything else would get the website work while not shown in dev tools unless it's a bug. And websocket can't be used to serve a website.

I don't have any running NE mac app at hand so I can't test it, but I would recommend you try to run it on another computer to see if it is reproducible. Also try to set the `matchDomain` to `["*"]` so you can rule out criteria misconfiguration.

**Comment by zhuhaow** [comment]
Also, try to restart you mac to see if the error persists.
