### ISSUE TITLE
使用工厂模式创建socksAdapter初始化之后怎么判断跟代理服务器的连接状态呢

### ISSUE THREAD

**Issue by hair-man** [zhuhaow/NEKit#261]
使用工厂模式初始化之后怎么判断跟代理服务器的，请指点一下 谢谢；目前无论写什么IP地址端口，都会直接显示VPN标志，表示连接成功，所以请问，该如何正确判断与代理服务器的连接状态。

**Comment by zhuhaow** [comment]
你使用Network Extension的方式是完全无状态的，所以不存在一个判断代理服务器连接状态的方法。
你也可以自己写一个probe去不停的连服务器发送心跳包来判断（需要你的服务器支持）。

**Comment by hair-man** [comment]
谢谢
