### ISSUE TITLE
请问在跑测速网站上载时很容易超过记忆体使用限制(15MB)

### ISSUE THREAD

**Issue by cimonk** [zhuhaow/NEKit#262]
在跑测速网站上载时很容易超过记忆体使用限制(15MB)
看起来是因为Proxy端一次从手机端读进来太多的data导致记忆体膨胀过快而达到记忆体使用限制
请问我该如何限制上载的速率或是一次读进来的data大小呢？ 谢谢您

**Comment by zhuhaow** [comment]
数据读进来之后你做了什么处理？如果直接处理完释放那么对内存的影响应该不会特别的大。

如果想要减少每次的读取量，技术上是可以的，但是GCDAsyncSocket基本不支持。

**Comment by so898** [comment]
> 数据读进来之后你做了什么处理？如果直接处理完释放那么对内存的影响应该不会特别的大。
> 
> 如果想要减少每次的读取量，技术上是可以的，但是GCDAsyncSocket基本不支持。

GCDAsyncSocket 支持 `- (void)readDataToLength:(NSUInteger)length withTimeout:(NSTimeInterval)timeout tag:(long)tag;` 方法，应该可以通过这个来限制每次读取的量

**Comment by zhuhaow** [comment]
这个方法要求长度必须要到这么长，不然会一直等

> 在 2019年9月3日，21:04，Bill Cheng <notifications@github.com> 写道：
> 

﻿
数据读进来之后你做了什么处理？如果直接处理完释放那么对内存的影响应该不会特别的大。

如果想要减少每次的读取量，技术上是可以的，但是GCDAsyncSocket基本不支持。

GCDAsyncSocket 支持 - (void)readDataToLength:(NSUInteger)length withTimeout:(NSTimeInterval)timeout tag:(long)tag; 方法，应该可以通过这个来限制每次读取的量

**Comment by so898** [comment]
> 这个方法要求长度必须要到这么长，不然会一直等
> 在 2019年9月3日，21:04，Bill Cheng ***@***.***> 写道：
> ﻿ 数据读进来之后你做了什么处理？如果直接处理完释放那么对内存的影响应该不会特别的大。 如果想要减少每次的读取量，技术上是可以的，但是GCDAsyncSocket基本不支持。 GCDAsyncSocket 支持 - (void)readDataToLength:(NSUInteger)length withTimeout:(NSTimeInterval)timeout tag:(long)tag; 方法，应该可以通过这个来限制每次读取的量 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

你的意思是这个方法的 timeout 是无效的么？这个我可能需要测试来证实一下

**Comment by zhuhaow** [comment]
timeout是可以的，但是不管timeout设多少都有延迟啊
