### ISSUE TITLE
手機顯示有連上vpn 但實際上沒有網路連線

### ISSUE THREAD

**Issue by wuyilong80** [zhuhaow/NEKit#264]
請問我是哪裡沒設定好 所以發生這種狀況呢

**Comment by zhuhaow** [comment]
很难说，你在callback里call的completionhandler之后图标就会显示，至于网络设置基本没啥关系。系统并不会（也不能）检查联通性

**Comment by wuyilong80** [comment]
了解 謝謝你的解釋 那想再問一下 跟packetFlow數據包的處理有關係嗎？ 是否一定要處理數據包呢？

**Comment by zhuhaow** [comment]
也有也没有。路由表某些设置有可能会不显示VPN。

packet不是必须处理

**Comment by wuyilong80** [comment]
好的 謝謝你了!
