### ISSUE TITLE
vpn 连接一段时间之后自动会断开

### ISSUE THREAD

**Issue by mengke0612** [zhuhaow/NEKit#266]
你好！请教一个问题。 vpn连接上之后手机自动锁屏过段时间再打开 vpn会断开，这是系统的原因吗还是

**Comment by zhuhaow** [comment]
可以看看日志里，应该是crash了

**Comment by mengke0612** [comment]
我们app同时使用 openvpn和 nekit两种模式都会出现？我想会不会不是代码问题

**Comment by zhuhaow** [comment]
什么是两种模式？谁的代码有问题？

> 在 2019年9月11日，18:21，mengke0612 <notifications@github.com> 写道：
> 

﻿
我们app同时使用 openvpn和 nekit两种模式都会出现？我想会不会不是代码问题

**Comment by mengke0612** [comment]
extension里面 同时支持openvpn 和 nekit的ss代理模式 加速一段时间之后vpn都会断开

**Comment by zhuhaow** [comment]
九成九crash了

> 在 2019年9月11日，18:27，mengke0612 <notifications@github.com> 写道：
> 

﻿
extension里面 同时支持openvpn 和 nekit的ss代理模式 加速一段时间之后vpn都会断开

**Comment by mengke0612** [comment]
哪有办法加一个crash收集吗

**Comment by zhuhaow** [comment]
不知道，crashlytic？你这种这么容易重现的crash不需要收集

> 在 2019年9月11日，18:31，mengke0612 <notifications@github.com> 写道：
> 

﻿
哪有办法加一个crash收集吗

**Comment by madonya** [comment]
> 你好！请教一个问题。 vpn连接上之后手机自动锁屏过段时间再打开 vpn会断开，这是系统的原因吗还是

请问你解决了吗
