### ISSUE TITLE
SOCKS5AdapterFactory是否只支持无认证链接？

### ISSUE THREAD

**Issue by chenfengfeng** [zhuhaow/NEKit#267]
如果需要账号密码方式的链接，是需要自己写吗？

**Comment by chenfengfeng** [comment]
找了一下，发现这边只提供一个链接的方式，那么我如果要用账号密码登陆的话，那就是需要按照socks5协议的格式把账号密码发送过去给服务器，我想请问，我应该如何监听服务器返回的数据？

**Comment by zhuhaow** [comment]
参考 https://github.com/zhuhaow/NEKit/blob/master/src/Socket/AdapterSocket/SOCKS5Adapter.swift 的实现
