### ISSUE TITLE
HTTPStreamScanner Error

### ISSUE THREAD

**Issue by so898** [zhuhaow/NEKit#268]
I am using Transmission via NEKit and I find there is something wrong with the Transmission RPC request.

I check the browser network history and found the request with problem.

The HTTP header of the request is:

> POST /transmission/rpc HTTP/1.1
> Accept: */*
> Accept-Encoding: gzip
> Connection: keep-alive
> Referer: http://xxxxxx/transmission/web/
> Host: xxxxxx
> User-Agent: Mozilla/5.0 (xxxxxx) Gecko/20100101 Firefox/69.0
> Content-Length: 0
> Accept-Language: xxxxxx
> X-Requested-With: XMLHttpRequest
> Authorization: Basic xxxxxx

As I know, Transmission server will response 409 for the request at first time.

I check the request with Chrome without NEKit and I found the socket closed after Transmission RPC request.

However, with NEKit, proxy will request second header from client after sent the first header and get the response from server. And NEKit will send the second HTTP header with the same socket as first HTTP header, but server will not response to the second header as the socket should be closed.

After read the code, I find it seems like NEKit assume if Content-Length is 0, there should always be another HTTP Header from client.

In the HTTPStreamScanner.swift:

> fileprivate func setNextAction() {
>         switch remainContentLength {
>         case 0:
>             nextAction = .readHeader
>         case _ where remainContentLength < 0:
>             nextAction = .readContent(-1)
>         default:
>             nextAction = .readContent(min(remainContentLength, Opt.MAXHTTPContentBlockLength))
>         }
>     }

I have checked the history of HTTPStreamScanner.swift and I have not idea why NEKit requesting the second HTTP header in the same socket when content length is 0.

I think there might be an error in the code.

**Comment by zhuhaow** [comment]
NEKit simply maps a connection to proxy to a connection to a remote server. It does not try to understand when to close a connection. If you see it sends two requests with one connection, that's because transmission is doing that.
