### ISSUE TITLE
关于版权

### ISSUE THREAD

**Issue by sruirui** [zhuhaow/NEKit#269]
你好，我想在我们的一个已经上架的普通社交软件 加入一个免费的回国加速模块（界面上一个开关），如果使用NEKit，我只需要在设置开源组件清单里面说明就可以了吧？

**Comment by sruirui** [comment]
我是看了这句话  Redistributions in binary form must reproduce **the above copyright notice**, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

**Comment by zhuhaow** [comment]
只要在软件某处的acknowledge里写上license就好了
