### ISSUE TITLE
does this support Objc project?

### ISSUE THREAD

**Issue by nicecui** [zhuhaow/NEKit#27]
I tried to import this project to my Objc project via carthage, but the xCode cannot found Factory classes which is so strange.

I checked the NEKit-Swift.h file and found ProxyServer, Socket, but no Factory, Raw Socket, and Rule.

Could you please tell me why, and how to solve this problem? thank you.

**Comment by zhuhaow** [comment]
If you really want to use it with Objective-C, then inherit every class from NSObject
