### ISSUE TITLE
编译报错（Module 'NEKit' was created for incompatible target x86_64-apple-macos10.11:）

### ISSUE THREAD

**Issue by WangEnMaoFly** [zhuhaow/NEKit#277]
Module 'NEKit' was created for incompatible target x86_64-apple-macos10.11: /Users/yanhao/development/roam_for_ios/Roam/Roam/Carthage/Build/Mac/NEKit.framework/Modules/NEKit.swiftmodule/x86_64.swiftmodule。大神看看这个是什么原因呢？

**Comment by WangEnMaoFly** [comment]
系统版本为什么10.14.6，Xcode版本为11.2

**Comment by zhuhaow** [comment]
你iOS里用了mac的framework
