### ISSUE TITLE
oc调用

### ISSUE THREAD

**Issue by y1024** [zhuhaow/NEKit#28]
使用 Carthage生成framework后 调用，发现没有 ShadowsocksAdapter
![image](https://cloud.githubusercontent.com/assets/9347686/20659692/30424a02-b580-11e6-9b0b-7d0fcc6e606f.png)

**Comment by y1024** [comment]
有空帮忙看看 谢谢

**Comment by y1024** [comment]
![image](https://cloud.githubusercontent.com/assets/9347686/20659723/6d3a3474-b580-11e6-9b38-738c66623395.png)

**Comment by zhuhaow** [comment]
自己把每个类加上@objc或者继承NSObject
