### ISSUE TITLE
xcode11.2.1 telegram socks5代理连接失败

### ISSUE THREAD

**Issue by AliThink** [zhuhaow/NEKit#282]
xcode11编译，新版的telegram配置socks5代理，依然会存在问题，跟踪了下代码，并不存在method数量的问题了 #241 issue中Bill Cheng提到的解决方案失效。Session在创建之后不久就莫名断开了。。。还没找到解决方案。

**Comment by AliThink** [comment]
搞定了，telegram回传的host有问题，处理一下就可以了

**Comment by ednew2018** [comment]
你好，请问是怎么修复的？是因为剔除ip后面的东西吗？

**Comment by yuzhijiang** [comment]
我好像也是存在这个问题，很想知道解决方案
