### ISSUE TITLE
How to support aes-256-gcm?

### ISSUE THREAD

**Issue by ednew2018** [zhuhaow/NEKit#285]

**Comment by itsjohnye** [comment]
any hint or pathway please? @zhuhaow

**Comment by zhuhaow** [comment]
CommonCrypto doesn't expose the GCM related API but you can use if anyway if you want.
https://opensource.apple.com/source/CommonCrypto/CommonCrypto-60074/include/CommonCryptorSPI.h

Or if you only aim iOS 13+, you can use CryptoKit.
