### ISSUE TITLE
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH

### ISSUE THREAD

**Issue by samzhiwei** [zhuhaow/NEKit#286]
用空项目 Carthage 集成的时候出现以下错误

*** Fetching NEKit
*** Fetching tun2socks
*** Fetching Resolver
*** Fetching CocoaAsyncSocket
*** Fetching CocoaLumberjack
*** Checking out NEKit at "0.15.0"
*** Checking out CocoaAsyncSocket at "7.6.3"
*** Checking out MMDB-Swift at "0.5.0"
*** Checking out Sodium-framework at "v1.0.10.1"
*** Checking out CocoaLumberjack at "3.6.1"
*** Checking out Resolver at "0.2.0"
*** Checking out tun2socks at "0.7.0"
*** Checking out YamlSwift at "3.4.3"
*** xcodebuild output can be found in /var/folders/k1/ddvk1dkj5gj358gvltq7xjjm0000gn/T/carthage-xcodebuild.R3UVHt.log
A shell task (/usr/bin/xcrun xcodebuild -project /Users/sam/Desktop/Demo/Demo\ VPN/Carthage/Checkouts/CocoaAsyncSocket/CocoaAsyncSocket.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 72:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH

执行语句 carthage update --no-use-binaries --platform ios  
Carthage 版本 0.34.0
Xcode11.3 Swift 5

可能是哪里出问题吗？

**Comment by zhuhaow** [comment]
https://www.google.com/search?q=unable%20to%20find%20utility%20%22xcodebuild%22%2C%20not%20a%20developer%20tool%20or%20in%20PATH

You are not setting the CLI tools correctly.
