### ISSUE TITLE
你好，我试用NEkit 软件在后台经常遇到Crashed

### ISSUE THREAD

**Issue by qinci** [zhuhaow/NEKit#289]
NEKit：V0.15.0

目前看日志，好像就这两种类型
![截屏2020-02-27下午4 39 04](https://user-images.githubusercontent.com/16683610/75426576-eff8cc80-597f-11ea-998a-60214f01825e.jpg)
![截屏2020-02-27下午4 33 16](https://user-images.githubusercontent.com/16683610/75426579-f25b2680-597f-11ea-959c-c4634e309c07.jpg)

**Comment by qinci** [comment]
还有这个
![截屏2020-02-27下午4 45 40](https://user-images.githubusercontent.com/16683610/75426981-a492ee00-5980-11ea-9bd0-017efcfa51c9.jpg)

**Comment by zhuhaow** [comment]
Do not use IPStack, don't route packet to TUN interface. The IPStack is not stable and will crash.

**Comment by qinci** [comment]
Can I use the old version to fix this problem?

**Comment by zhuhaow** [comment]
Unfortunately,  there isn't a working version. The bug was there in the first day and hasn’t be located ever.

**Comment by qinci** [comment]
你好，有没有办法在不转发 TUN 接口的情况下，让游戏走他原来自己的网络。现在不处理的话，游戏udp就连接不上了

**Comment by zhuhaow** [comment]
自己接管DNS然后只把相关域名解析到某些网络block然后只转发那个block到tun。不要处理tcp包。

**Comment by qinci** [comment]
我现在也不用tun接口了，直接代理http和https，但是还是遇到其他Crashed的问题😭


![截屏2020-03-03下午10 18 27](https://user-images.githubusercontent.com/16683610/75784426-2332c580-5d9d-11ea-8ce7-78f49f8db099.jpg)
![截屏2020-03-03下午10 18 55](https://user-images.githubusercontent.com/16683610/75784433-24fc8900-5d9d-11ea-92a9-c9b19cea41f5.jpg)

**Comment by zhuhaow** [comment]
不要写RawSocketFactory.TunnelProvider = self

**Comment by qinci** [comment]
好的，我试试，谢谢

**Comment by qinci** [comment]
不写RawSocketFactory.TunnelProvider = self后，有遇到内存问题😢

启动vpn后，杀掉主程序，再打开主程序，内存会一点一点增加

![截屏2020-03-04上午1 50 29](https://user-images.githubusercontent.com/16683610/75804242-a31b5880-5dba-11ea-8390-ab6d41d5825d.jpg)

**Comment by zhuhaow** [comment]
swift的版本这个unsafe的接口反复修改后我没有做过太多的测试。

这个leak从图上看起来有点周期性，是偶然现象么。

**Comment by qinci** [comment]
应该不是偶然现象，就刚刚重新调试。打开后打开微博，杀掉微博，再打开微博也是一样的效果。不过不是周期的，上面的点是对应我打开软件时（可能打开软件一瞬间请求很多个连接）
![截屏2020-03-11下午8 17 23](https://user-images.githubusercontent.com/16683610/76416069-5563a900-63d5-11ea-8469-f3bbd35bff6a.jpg)
