### ISSUE TITLE
升级到最新的NEKit ，iOS和MacOS上连接正常的SS都是先连接成功然后过几秒就断开

### ISSUE THREAD

**Issue by 2856571872** [zhuhaow/NEKit#292]
NEKit 内部有没有日志记录之类的

**Comment by zhuhaow** [comment]
Attached到extension的进程上调试，十有八九是 `GeoIP.database = MMDB("PATH_TO_THE_DATABASE")!` 没设

**Comment by 2856571872** [comment]
> Attached到extension的进程上调试，十有八九是 `GeoIP.database = MMDB("PATH_TO_THE_DATABASE")!` 没设

多谢回复，但是问题还是存在。。。
背景是这样，为了适配Xcode 11，我升级了NEKit 的库，目前是swift 4.2。关于连接SS的配置都没变动，PacketTunnel里面的相关配置如下。
情况说明：未加上GeoIP.database = MMDB("PATH_TO_THE_DATABASE")!，连接成功，但是过一会就自动断开。加上了直接就连接失败了
`        var address: String = ""
        var post: Int = 82
        var password: String = ""
        var algorithm: CryptoAlgorithm = .CHACHA20
        var rulesDic: [String:Any] = [:]

        address = configure[addressKey] as? String ?? ""
        if let postString = configure[portKey] as? String {
            post = Int(postString) ?? 82
        }
        password = configure[passwordKey] as? String ?? ""

        if let algorithmString = configure[methodKey] as? String {
            if algorithmString == "CHACHA20" {
                algorithm = .CHACHA20
            }
            if algorithmString == "AES-128-CFB" {
                algorithm = .AES128CFB
            }
            if algorithmString == "AES-192-CFB" {
                algorithm = .AES192CFB
            }
            if algorithmString == "AES-256-CFB" {
                algorithm = .AES256CFB
            }
            if algorithmString == "SALSA20" {
                algorithm = .SALSA20
            }
            if algorithmString == "RC4-MD5" {
                algorithm = .RC4MD5
            }
        }
        
        if let rulesDicJsonData = (configure[rulesKey] as? String)?.data(using: String.Encoding.utf8) {
            if let rules = (try? JSONSerialization.jsonObject(with:rulesDicJsonData, options: [])) as? [String:Any] {
                rulesDic = rules
            }
        }

        // 协议混淆
        let obfuscater = ShadowsocksAdapter.ProtocolObfuscater.OriginProtocolObfuscater.Factory()

        // 算法
        let cryptor = ShadowsocksAdapter.CryptoStreamProcessor.Factory(password: password, algorithm: algorithm)

        let stream = ShadowsocksAdapter.StreamObfuscater.OriginStreamObfuscater.Factory()
        
//        GeoIP.database = MMDB("/path/GeoIP2-City.mmdb")!

        // ss适配器
        let ssAdapterFactory = ShadowsocksAdapterFactory(serverHost: address, serverPort: post, protocolObfuscaterFactory: obfuscater, cryptorFactory: cryptor, streamObfuscaterFactory: stream)

        // 直连适配器
        let directAdapterFactory = DirectAdapterFactory()

        // 设置用户规则
        var userRules:[Rule] = []

        // 直连规则
        let directRules = cofigureAdapter(adapter: directAdapterFactory, parameters: rulesDic[directKey] as? [String : Any])
        // 代理规则
        let adapterRules = cofigureAdapter(adapter: ssAdapterFactory, parameters: rulesDic[proxyAdapterKey] as? [String : Any])

        // 注意: 谁先放在前面，谁的优先级就比较高

        userRules.append(contentsOf: adapterRules)
        userRules.append(contentsOf: directRules)
        
        // 其他规则
        let unKnowLoc = CountryRule(countryCode: "--", match: true, adapterFactory: ssAdapterFactory)

        let dnsFailRule = DNSFailRule(adapterFactory: ssAdapterFactory)

        let allRule = AllRule(adapterFactory: ssAdapterFactory)

        userRules.append(contentsOf: [unKnowLoc,dnsFailRule,allRule])

        let manager = RuleManager(fromRules: userRules, appendDirect: true)
        RuleManager.currentManager = manager`

**Comment by zhuhaow** [comment]
attach上去调试

**Comment by 2856571872** [comment]
> extension
attach停在了这
![image](https://user-images.githubusercontent.com/10896490/77818768-3b81d000-7110-11ea-9b2e-69ad9cff9c5d.png)

**Comment by 2856571872** [comment]
大佬，能帮忙分析下原因吗。。

**Comment by zhuhaow** [comment]
<img width="316" alt="image" src="https://user-images.githubusercontent.com/1287724/78018962-69ba1680-7381-11ea-8371-8cc53c1dc74c.png">
不是显示在这了
