### ISSUE TITLE
急需一个例子

### ISSUE THREAD

**Issue by lemon4ex** [zhuhaow/NEKit#3]
swift不熟，看着好吃力。
demo里代码就几句话，太简单了。NEKit功能应该很强大才对，如果有一个实例相信会对使用者很有帮助。
顺便再提一个，HTTPProxyServer确实是很常用的，加入到库里是比较好的选择，之前我有写了一个，不过不太稳定，如果库里有相关的代码，又可以偷师了😊

**Comment by zhuhaow** [comment]
https://github.com/zhuhaow/Specht
