### ISSUE TITLE
Please check HTTPProxySocket class again

### ISSUE THREAD

**Issue by ralphshane** [zhuhaow/NEKit#36]
I have checked the HTTPProxySocket class many times. 
I think it can not work correctly.
Please check it more times.

**Comment by zhuhaow** [comment]
It would be much better if you could be more specific about "not work correctly".

**Comment by ralphshane** [comment]
here is the fixing. it's ugly. but it can work.



    override public func readData() {
        guard !isCancelled else {
            return
        }

        // Return the first header we read when the socket was opened if the proxy command is not CONNECT.
        if ((writeStatus == .forwarding) && isConnectCommand) {
            delegate?.didRead(data: currentHeader.toData(), from: self)
            readStatus = .readingContent
            return
        }

        switch scanner.nextAction {
        case .readContent(let length):
            readStatus = .readingContent
            if length > 0 {
                socket.readDataTo(length: length)
            } else {
                socket.readData()
            }
        case .readHeader:
            readStatus = .readingHeader
            socket.readDataTo(data: Utils.HTTPData.DoubleCRLF)
        case .stop:
            readStatus = .stopped
            disconnect()
        }

    }

    public override func respondTo(adapter: AdapterSocket) {
        super.respondTo(adapter: adapter)

        guard !isCancelled else {
            return
        }


        if ((readStatus != .pendingFirstHeader) && (readStatus != .readingContent)) {
            return
        }
        readStatus = .invalid        

        if isConnectCommand {
            writeStatus = .sendingConnectResponse
            write(data: Utils.HTTPData.ConnectSuccessResponse)
        } else {
            writeStatus = .forwarding
            observer?.signal(.readyForForward(self))
            delegate?.didBecomeReadyToForwardWith(socket: self)
        }
    }

**Comment by zhuhaow** [comment]
It is still quite confusing, you can speak Chinese if you want to, and it'd be better if you could provide it as a pull request.

**Comment by ralphshane** [comment]
http://photo.weibo.com/2831387475/wbphotos/large/mid/4053727213621600/pid/a8c38b53gw1fatx8tm3cjj20ob0afwhy

**Comment by ralphshane** [comment]
I have updated it now.

**Comment by zhuhaow** [comment]
What do you want to do? 
Return the header every time the `Tunnel` tries to read some thing? Why?

**Comment by ralphshane** [comment]
because the adapter readdata method will never be called if we do not coding like this.

**Comment by zhuhaow** [comment]
Oh, you changed the `respondTo`.
I do not understand why you say it was wrong, have you tried it?
Now you are calling `didRead` even before the `Tunnel` tries to read some thing, which is obviously wrong.

**Comment by ralphshane** [comment]
Yes. In factly, I just copy and paste your old implementation before readStatus and writeStatus. But it works fine.

**Comment by zhuhaow** [comment]
It is working fine with my version?

**Comment by ralphshane** [comment]
No. It's my modified version works fine.

**Comment by zhuhaow** [comment]
How are you using it? Without `Tunnel`?

**Comment by ralphshane** [comment]
Tunnel::didConnectWith will call ProxySocket::respondTo, you know.

**Comment by ralphshane** [comment]
If we use your version, the adapterSocket::readdata will never be called. It's the key point.

**Comment by zhuhaow** [comment]
Is NEKitDemo working?

**Comment by ralphshane** [comment]
I'm not using your Demo. sorry. you can test it yourself.

**Comment by zhuhaow** [comment]
I'm using it and it's fine, have you tried the latest version?
I do not know how you are using it, only with `HTTPProxyServer`?

**Comment by ralphshane** [comment]
Yes. Only `HTTPProxySocket ` class.

**Comment by zhuhaow** [comment]
I do not know how you are using `HTTPProxySocket` but obvious you are using it wrong, `respondTo` do not mean adapter is ready for forwarding data, it just means the adapter connected to remote, that's all. See how to do it right in `Tunnel`.

**Comment by zhuhaow** [comment]
It is not strictly following the standard, because it should reply only when it successfully connected to target host, that's something should be fixed, but has nothing to do with what you are doing.

**Comment by ralphshane** [comment]
OK. I just point out the issue. You make the final decision.

**Comment by zhuhaow** [comment]
Fixed
