### ISSUE TITLE
只对HTTP做代理吗？

### ISSUE THREAD

**Issue by gaotong2055** [zhuhaow/NEKit#37]
IOS上开启VPN，配置的SS，默认全部走代理，但是只有HTTP协议走了SS代理，TCP协议没有走SS代理。

**Comment by zhuhaow** [comment]
嗯

**Comment by gaotong2055** [comment]
有办法解决吗？

**Comment by zhuhaow** [comment]
除非启用TUNInterface

**Comment by gaotong2055** [comment]
TCP可以了，UDP还是不行？

**Comment by zhuhaow** [comment]
不行

**Comment by Sky891028** [comment]
现在UDP可以了吗 ？

**Comment by Sky891028** [comment]
怎么实现tcp代理 我启用tun后 tcp转发会disconnected
PacketTunnel	Adapter socket <ShadowsocksAdapter host:mtrace.qq.com port:80)> disconnected.
