### ISSUE TITLE
Xcode 8.2.1

### ISSUE THREAD

**Issue by ZhouRR** [zhuhaow/NEKit#39]
貌似 tun2socks 不支持swift 3.0.2 ?
<img width="688" alt="2017-01-11 2 58 09" src="https://cloud.githubusercontent.com/assets/8873011/21838713/8f97402e-d80e-11e6-8a94-39343c23d76c.png">

**Comment by zhuhaow** [comment]
错误写的这么清楚了，自己编译

**Comment by zhuhaow** [comment]
> Use `carthage update --no-use-binaries --platform mac,ios` to install all frameworks. Do not use pre-compiled binaries since some of them might be buggy.
