### ISSUE TITLE
CFBundleShortVersionString using git_release_version is illegal

### ISSUE THREAD

**Issue by xiao99xiao** [zhuhaow/NEKit#42]
the `"Set :CFBundleShortVersionString ${git_release_version#*v}\"` in project configurations made `CFBundleShortVersionString` a very long string, which gets app's binary rejected when uploaded to iTunes Connect.

Full error message:
>ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '3ba2400cf93c9c816dc0b9b1da496ab8e020b42b' in the Info.plist file must be a period-separated list of at most three non-negative integers."

Suggestion:
leave the CFBundleShortVersionString as it is.

**Comment by zhuhaow** [comment]
Just release the latest version.
If you are intended to use the `master` branch, then modify the version by yourself after compiling the framework with Carthage

**Comment by corbt** [comment]
I'm running into this issue. I have version 0.12.4 installed with Carthage. Unfortunately, NEKit seems to be substituting my local git repo's commit with the version string, so I have to go in and manually change it back before Apple will accept the app.

**Comment by cnnblike** [comment]
0.12.6 encountered the same issue. solved with adding a building phase:
```
defaults write "$PWD/Carthage/Build/iOS/NEKit.framework/Info.plist" CFBundleShortVersionString 0.2.0
defaults write "$PWD/Carthage/Build/iOS/NEKit.framework.dSYM/Contents/Info.plist" CFBundleShortVersionString 0.2.0
```

**Comment by zhuhaow** [comment]
This version is designed to mark the version of the framework and it only accepts several formats. If you want to modify NEKit yourself, it will pick the commit hash as the version which is not a valid version as far as Apple considers. 

Do you have any recommendation here?
