### ISSUE TITLE
can you send me a NEKit_demo.yaml demo file?

### ISSUE THREAD

**Issue by zkh90644** [zhuhaow/NEKit#46]
when I ran the demo target in the NEKit which called `NEKitDemo`,  Xcode told me the `config` is nil, and I find there no `NEKit_demo.yaml` in the project. Can you add a demo file in the project? I just want to run the project without crash.

**Comment by zhuhaow** [comment]
https://github.com/zhuhaow/SpechtLite

**Comment by zkh90644** [comment]
3Q so much

**Comment by sseen** [comment]
@zkhCreator can u share the yaml files u got ? thank u.

**Comment by zkhCreator** [comment]
@sseen I copy the file in the [SpechtLite](https://github.com/zhuhaow/SpechtLite)'s readme file, and modified someplace.But finally I didn't run the framework in my app correctly, so I delete all the files.Sorry

**Comment by sseen** [comment]
@zkhCreator ok, thanks agian.
