### ISSUE TITLE
Can not compile source code because of no class 'IPv4Address'

### ISSUE THREAD

**Issue by SeanCode** [zhuhaow/NEKit#48]
I tried to compile the source code, only to get the error:
NEKit/IPStack/Router.swift:5:32: Use of undeclared type 'IPv4Address'
....
NEKit/IPStack/Router.swift:58:9: Use of unresolved identifier 'NetworkInterface'

I found no class named 'IPv4Adress' and 'NetworkInterface'
and I see 'IPv4Address is removed. Now both IPv4 and IPv6 are represented by one class IPAddress.' in Changelog.md, so haven't change that in some swift class?
Thx!

**Comment by zhuhaow** [comment]
`Router.swift` is not used, how are you compiling the source code? I recommend using Xcode.

**Comment by SeanCode** [comment]
Yes, I am using Xcode 8.2.1.
I see, I included Router.swift in compile sources, so Thx!
