### ISSUE TITLE
High battery usage

### ISSUE THREAD

**Issue by clementhk** [zhuhaow/NEKit#52]
Referring to https://github.com/hellowingy/wingy-announcement/issues/3
Not sure if it is related, feel free to close it if it is not about NEKit, but on my mac it is also listed as "Using Significant Energy".
Let me know if I could help in anyway.

Thank you for this project, I couldn't find a link for donating, please let me know if there is one.

**Comment by zhuhaow** [comment]
Should be improved in [`libnekit`](https://github.com/zhuhaow/libnekit)
