### ISSUE TITLE
What is the issue with TUNInterface?

### ISSUE THREAD

**Issue by simpzan** [zhuhaow/NEKit#58]
Hi, there. In the readme, it says `Do not enable TUNInterface as of now since it is not working.`.
Could you detail the current issue with `TUNInterface`? Thanks!

**Comment by zhuhaow** [comment]
Crashing. Fixed by some pull requests(but I haven't validated them).

Memory leak.

**Comment by simpzan** [comment]
Thank you for the information. 
Without TUNInterface and tun2socks, as I understand it, the data sent to tun will lost. It will be an negative side effects on iOS.
If tun2socks is not stable, I wonder if something like `TCPDirectStack` possible, which sends data directly to real nic, instead of go through tun2socks? This way the request sent to tun will not lost at least.

**Comment by zhuhaow** [comment]
Just don’t route anything to tun if you are not going to process them.

**Comment by simpzan** [comment]
How to achieve that while http/https/sock5 requests are routed to proxy server?
I understand that If I set http/https proxy of the tun device, http requests are routed to http proxy server, but raw sockets are routed to tun.

**Comment by zhuhaow** [comment]
Well, you have some fundamental misunderstandings  here. HTTP proxy has absolutely nothing todo with route table.

**Comment by simpzan** [comment]
I tried the following code on iOS 9.3.3.

if `v4Settings.includedRoutes = [NEIPv4Route.default()]` is set, safari requests are routed to http proxy server, but raw sockets are routed to tun.
if it is not set, then both types of requests goes directly to real nic.

I don't know how to achieve that http requests goes to http proxy server while raw socket requests goes directly to real nic on iOS. Please help me figure this out, thank you!

```
    public let httpProxyAddress = "127.0.0.1"
    public let httpProxyPort: UInt16 = 9090
    public let socksProxyPort: UInt16 = 9091

    func getTunnelSettings() -> NEPacketTunnelNetworkSettings {
        let settings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: "192.0.2.2")
        settings.mtu = 1600
        settings.dnsSettings = NEDNSSettings(servers: ["114.114.114.114"])
        let v4Settings = NEIPv4Settings(addresses:["192.0.2.1"], subnetMasks:["255.255.255.0"])
        v4Settings.includedRoutes = [NEIPv4Route.default()]
        v4Settings.excludedRoutes = [NEIPv4Route(destinationAddress:"114.114.114.114", subnetMask:"255.255.255.255")]
        settings.iPv4Settings = v4Settings
        settings.proxySettings = getProxySettings()
        return settings
    }
    func getProxySettings() -> NEProxySettings {
        let proxy = NEProxySettings()
        proxy.httpEnabled = true
        proxy.httpServer = NEProxyServer(address: httpProxyAddress, port: Int(httpProxyPort))
        proxy.httpsEnabled = true
        proxy.httpsServer = proxy.httpServer
        return proxy
    }

    override func startTunnel(options: [String : NSObject]? = nil, completionHandler: @escaping (Error?) -> Void) {
        NSLog("startTunnel \(options)")

        DDLog.add(DDTTYLogger.sharedInstance()) // TTY = Xcode console
        DDLog.add(DDASLLogger.sharedInstance()) // ASL = Apple System Logs
        ObserverFactory.currentFactory = DebugObserverFactory()

        self.startProxyServer()
        setTunnelNetworkSettings(getTunnelSettings()) { (error) in
            if error != nil {
                NSLog("\(#function) error:\(error)")
                return
            }
            NSLog("connected")
            self.readTun()
            completionHandler(nil)
        }
    }

    func readTun() {
        packetFlow.readPackets { (packets, protocols) in
            NSLog("read packets \(protocols)")
            self.readTun()
        }
    }

```

**Comment by simpzan** [comment]
@zhuhaow Could you please help me on this? Thanks!

**Comment by zhuhaow** [comment]
See Specht about how to disable packet processing.
