### ISSUE TITLE
the exported header for ios framework is incomplete.

### ISSUE THREAD

**Issue by simpzan** [zhuhaow/NEKit#6]
the header in macos framework is 24KB, while the header in ios framework is only 6KB.
[Headers-macos.zip](https://github.com/zhuhaow/NEKit/files/428780/Headers-macos.zip)
[Headers-ios.zip](https://github.com/zhuhaow/NEKit/files/428781/Headers-ios.zip)

**Comment by zhuhaow** [comment]
That's strange because iOS and macOS framework are compiled with the exactly same source files. Do you have any idea why this may happen?

**Comment by simpzan** [comment]
I think it maybe an Carthage issue, I just encountered this issue when using `carthage update NEKit`.
Then I manually download the repo and add it to xcode as subproject, there's no issue.

**Comment by zhuhaow** [comment]
It seems like the pre-compiled version has wrong header though I do not know why.

I recommend you to try to use
```
carthage update --no-use-binaries --platform mac,iOS
```
to compile all frameworks yourself.

**Comment by simpzan** [comment]
@zhuhaow I just tested again use the command you provide, the issue remains.

the cartfile
```
github "zhuhaow/NEKit" "0.2.2"
```

Xcode 7.3.1 on Mac OS 10.11.6

**Comment by zhuhaow** [comment]
Well, I think I know how to solve it though I still do not understand why there is such difference between macOS and iOS.
If you are using NEKit with a swift project, then everything should be fine, these header files can be ignored (as far as I've tested).
If you want to use NEKit with objective-c, which I DO NOT recommend (**honestly, why would you develop a new project with objective-c?**), it means every class that you want to use must be a subclass of NSObject (or any class from objective-c runtime), it is probably also required to mark them with `@objc`. 
Though it is not difficult to do, that is something I do not like very much, and I'm not sure about the performance impaction of it.
