### ISSUE TITLE
pac file limitation

### ISSUE THREAD

**Issue by itskeKs** [zhuhaow/NEKit#63]
Hello @zhuhaow,

i am running into some issues when i am using a pac file within NEKit on iOS 10.2.1. I dont know if it is related to NEKit or an Apple limitation but maybe you can help.

proxySettings.autoProxyConfigurationEnabled = true
proxySettings.proxyAutoConfigurationJavaScript = local.pacJSCode()
//proxySettings.proxyAutoConfigurationJavaScript = nil
//proxySettings.proxyAutoConfigurationURL = URL(string: "https://some/address/to/pac.js")

The error appears on both versions of code (local or remote pac). If i send a lot of requests either from an App or from Safari i have some kind of loading hang. It starts to load then the loading freezes and it takes the system something like 10-20s to load further.

For clarification: the pac file forwards to the proxy running on port 9090 so thats nit the issue. Requests are also forwarded to remote server when i am sing one.

Thanks for any help you can provide.

Best,

keKs

**Comment by zhuhaow** [comment]
There's a bug when safari connects a https site through proxy, it will pretend it is reading from the remote even if the connection is broken.
I do not know if this is the case or what you settings are. 
Hope that helps.

**Comment by itskeKs** [comment]
hmm i dont think thats the issue here. since when i do not use the pac file everything works just fine. it looks more like there is something wrong within requests handling when pac file is used. when i open something what makes a lot of requests the requests kind of stop for a couple of seconds (some apps throw connection error) but then it starts loading again. i dont understand why this happens :|

**Comment by zhuhaow** [comment]
Since the details are as vague as possible, I really can't tell what happens.
Do you enable TUN interface and route DNS request to NEKit?

**Comment by itskeKs** [comment]
tun interface is disabled. dns requests are routed to nekit. the pac file contains a blacklist of hosts which are blocked. they get redurected to nginx with a 502 error so the system knows what to do.

**Comment by zhuhaow** [comment]
Eh, you can't route dns requests to NEKit without enabling tun interface.

**Comment by itskeKs** [comment]
then i dont get it. so it is disabled then.

how can i check actually?

**Comment by zhuhaow** [comment]
You can paste your code here.

**Comment by itskeKs** [comment]
which part of code? :)

**Comment by zhuhaow** [comment]
`startTunnelWithOptions` if you are using Network Extension.

**Comment by itskeKs** [comment]
//
//  PacketTunnelProvider.swift
//  Fogu
//
//  Created by MAC on 27/02/2017.
//  Copyright © 2017 MAC. All rights reserved.
//

import NEKit
import NetworkExtension
import CocoaLumberjackSwift
import AppBase
import MMWormhole
import CocoaAsyncSocket

class PacketTunnelProvider: NEPacketTunnelProvider, GCDAsyncSocketDelegate {
    var interface: TUNInterface!
    var enablePacketProcessing = false
    
    var proxyPort: Int!
    var proxyServer: ProxyServer!
    
    var ssHost: String!
    var ssPort: String!
    var ssPassword: String!
    var ssAuthScheme: CryptoAlgorithm!
    
    var statusSocket: GCDAsyncSocket!
    var statusClientSocket: GCDAsyncSocket!
    
    var wormhole: MMWormhole!
    var forceStop: Bool!
    
    func createRuleManager() {
        let directAdapterFactory = DirectAdapterFactory()
        let cryptoFactory = ShadowsocksAdapter.CryptoStreamProcessor.Factory(password:ssPassword, algorithm: ssAuthScheme)
        let protocolObfuscatorFactory = ShadowsocksAdapter.ProtocolObfuscater.OriginProtocolObfuscater.Factory()
        let streamObfuscatorFactory = ShadowsocksAdapter.StreamObfuscater.OriginStreamObfuscater.Factory()
        let rejectAdapterFactory = RejectAdapterFactory(delay: 300)
        
        let ssAdapterFactory = ShadowsocksAdapterFactory(serverHost:ssHost, serverPort: Int(ssPort)!, protocolObfuscaterFactory: protocolObfuscatorFactory, cryptorFactory: cryptoFactory, streamObfuscaterFactory: streamObfuscatorFactory)
        
        var rules: [Rule] = []
        
        // create domain rules
        if App.BlockHosts() == true {
            let reject_criterias: [DomainListRule.MatchCriterion] = RuleMaker.rejectCriteriaForDomainRules()
            rules.append(DomainListRule(adapterFactory: rejectAdapterFactory, criteria: reject_criterias))
        }
        
        if App.directAll() == false {
            let proxy_criterias: [DomainListRule.MatchCriterion] = RuleMaker.proxyCriteriaForDomainRules()
            rules.append(DomainListRule(adapterFactory: ssAdapterFactory, criteria: proxy_criterias))
            
            let direct_criterias: [DomainListRule.MatchCriterion] = RuleMaker.directCriteriaForDomainRules()
            rules.append(DomainListRule(adapterFactory: directAdapterFactory, criteria: direct_criterias))
        }
        
        let reject_ip_ranges: [String] = RuleMaker.rejectIPRanges()
        let direct_ip_ranges: [String] = RuleMaker.directIPRanges()
        let proxy_ip_ranges: [String] = RuleMaker.proxyIPRanges()
        
        // create ip cidr rules
        if App.BlockHosts() == true {
            let rejectIPRangeRule: IPRangeListRule?
            do {
                try rejectIPRangeRule = IPRangeListRule(adapterFactory: rejectAdapterFactory, ranges: reject_ip_ranges)
                rules.append(rejectIPRangeRule!)
            } catch {
            }
        }
        
        if App.directAll() == false {
            let directIPRangeRule: IPRangeListRule?
            do {
                try directIPRangeRule = IPRangeListRule(adapterFactory: directAdapterFactory, ranges: direct_ip_ranges)
                rules.append(directIPRangeRule!)
            } catch {
            }
            
            let proxyIPRangeRule: IPRangeListRule?
            do {
                try proxyIPRangeRule = IPRangeListRule(adapterFactory: ssAdapterFactory, ranges: proxy_ip_ranges)
                rules.append(proxyIPRangeRule!)
            } catch {
            }
        }

        // create china rules
        let chinaRule = CountryRule(countryCode: "CN", match: true, adapterFactory: directAdapterFactory)
        rules.append(chinaRule)
        
        if App.directAll() == false {
            let allRule = AllRule(adapterFactory: ssAdapterFactory)
            rules.append(allRule)
        } else {
            let allRule = AllRule(adapterFactory: directAdapterFactory)
            rules.append(allRule)
        }
        
        // Create rule manager, rules will be matched in order.
        let manager = RuleManager(fromRules: rules, appendDirect: true)
        RuleManager.currentManager = manager
    }
    
    func startTUNInterface(completionHandler: @escaping (Error?) -> Void) {
        self.interface = TUNInterface(packetFlow: self.packetFlow)
        
        let ip_range : IPRange?
        do {
            try ip_range = IPRange.init(startIP: IPAddress.init(fromString: "198.18.1.1")!, endIP: IPAddress.init(fromString: "198.18.255.255")!)
        } catch {
            DDLogError("Encountered an error setting up the ip address range for fakeIPPool")
            completionHandler(error)
            return;
        }
        
        let fakeIPPool = IPPool.init(range: ip_range!)
        
        let dnsServer = DNSServer.init(address: IPAddress.init(fromString: "198.18.0.1")!, port: 53, fakeIPPool: fakeIPPool)
        let resolver = UDPDNSResolver.init(address: IPAddress.init(fromString: "114.114.114.114")!, port: 53)
        
        dnsServer.registerResolver(resolver)
        self.interface.register(stack: dnsServer)
        DNSServer.currentServer = dnsServer
        
        let udpStack = UDPDirectStack()
        self.interface.register(stack: udpStack)
        
        let tcpStack = TCPStack.stack
        tcpStack.proxyServer = self.proxyServer
        self.interface.register(stack:tcpStack)
        self.interface.start()
    }
    
    func setOptConfiguration() {
        Opt.MAXNWTCPSocketReadDataSize = 128 * 1024
        
        // This is only used in finding the end of HTTP header (as of now). There is no limit on the length of http header, but Apache set it to 8KB
        Opt.MAXNWTCPScanLength = 8912
        
        Opt.DNSFakeIPTTL = 300
        Opt.DNSPendingSessionLifeTime = 10
        Opt.UDPSocketActiveTimeout = 300
        Opt.UDPSocketActiveCheckInterval = 60
        Opt.MAXHTTPContentBlockLength = 10240
        Opt.RejectAdapterDefaultDelay = 300
        Opt.DNSTimeout = 1
        Opt.forwardReadInterval = 50
    }
    
    func startTunnelProc(options: [String : NSObject]? = nil, completionHandler: @escaping (Error?) -> Void) {
        self.setOptConfiguration()
        self.createRuleManager()
        proxyPort = 9090
        
        RawSocketFactory.TunnelProvider = self
        
        // the `tunnelRemoteAddress` is meaningless because we are not creating a tunnel.
        let networkSettings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: "8.8.8.8")
        networkSettings.mtu = 1400
        
        let ipv4Settings = NEIPv4Settings(addresses: ["192.169.89.1"], subnetMasks: ["255.255.255.0"])
        if enablePacketProcessing {
            ipv4Settings.includedRoutes = [NEIPv4Route.default()]
            ipv4Settings.excludedRoutes = [
                NEIPv4Route(destinationAddress: "10.0.0.0", subnetMask: "255.0.0.0"),
                NEIPv4Route(destinationAddress: "100.64.0.0", subnetMask: "255.192.0.0"),
                NEIPv4Route(destinationAddress: "127.0.0.0", subnetMask: "255.0.0.0"),
                NEIPv4Route(destinationAddress: "169.254.0.0", subnetMask: "255.255.0.0"),
                NEIPv4Route(destinationAddress: "172.16.0.0", subnetMask: "255.240.0.0"),
                NEIPv4Route(destinationAddress: "192.168.0.0", subnetMask: "255.255.0.0"),
            ]
        }
        networkSettings.iPv4Settings = ipv4Settings
        
        let proxySettings = NEProxySettings()
        if App.BlockHosts() == false {
            proxySettings.httpEnabled = true
            proxySettings.httpServer = NEProxyServer(address: "127.0.0.1", port: proxyPort)
            proxySettings.httpServer?.authenticationRequired = false
            proxySettings.httpsEnabled = true
            proxySettings.httpsServer = NEProxyServer(address: "127.0.0.1", port: proxyPort)
            proxySettings.httpsServer?.authenticationRequired = false
            proxySettings.excludeSimpleHostnames = true
        } else {
            proxySettings.autoProxyConfigurationEnabled = true
            proxySettings.proxyAutoConfigurationJavaScript = App.pacJSCode()
            //proxySettings.proxyAutoConfigurationJavaScript = nil
            //proxySettings.proxyAutoConfigurationURL = URL(string: "https://som.site/to/pac.js")
        }
        
        // This will match all domains
        proxySettings.matchDomains = [""]
        networkSettings.proxySettings = proxySettings
        
        // the 198.18.0.0/15 is reserved for benchmark.
        if enablePacketProcessing {
            let DNSSettings = NEDNSSettings(servers: ["198.18.0.1"])
            DNSSettings.matchDomains = [""]
            DNSSettings.matchDomainsNoSearch = false
            networkSettings.dnsSettings = DNSSettings
        }
        
        setTunnelNetworkSettings(networkSettings) {
            error in
            guard error == nil else {
                DDLogError("Encountered an error setting up the network: \(error)")
                completionHandler(error)
                return
            }
            
            self.proxyServer = GCDHTTPProxyServer(address: IPAddress.init(fromString: "127.0.0.1")
                , port: Port(port: UInt16(self.proxyPort)))
            try! self.proxyServer.start()
            
            completionHandler(nil)
            
            if self.enablePacketProcessing {
                self.startTUNInterface(completionHandler: completionHandler)
                return
            }
        }
    }
    
    override func startTunnel(options: [String : NSObject]? = nil, completionHandler: @escaping (Error?) -> Void) {
        self.forceStop = false
        DDLog.removeAllLoggers()
        
        if App.enableLogs() {
            let logFileManager = DDLogFileManagerDefault.init(logsDirectory: App.logDirURL().path)
            DDLog.add(DDFileLogger.init(logFileManager: logFileManager), with: DDLogLevel.all)
            
            // Use the build-in debug observer.
            ObserverFactory.currentFactory = DebugObserverFactory()
        }
        
        AppAPI.sharedInstance().getProxyInfoNE { (success, host, port, authscheme, password) in
            if success == true {
                self.ssHost = host
                self.ssPort = port
                self.ssPassword = password
                
                if authscheme?.uppercased() == "AES-128-CFB" {
                    self.ssAuthScheme = CryptoAlgorithm.AES128CFB
                } else if authscheme?.uppercased() == "AES-192-CFB" {
                    self.ssAuthScheme = CryptoAlgorithm.AES192CFB
                } else if authscheme?.uppercased() == "AES-256-CFB" {
                    self.ssAuthScheme = CryptoAlgorithm.AES256CFB
                } else if authscheme?.uppercased() == "CHACHA20" {
                    self.ssAuthScheme = CryptoAlgorithm.CHACHA20
                } else if authscheme?.uppercased() == "SALSA20" {
                    self.ssAuthScheme = CryptoAlgorithm.SALSA20
                } else if authscheme?.uppercased() == "RC4-MD5" {
                    self.ssAuthScheme = CryptoAlgorithm.RC4MD5
                } else {
                    self.ssAuthScheme = CryptoAlgorithm.AES256CFB
                }
                self.startTunnelProc(options: options, completionHandler: completionHandler)
                self.setupWormhole()
            } else {
                let error = NSError.init(code: 500, description: "Not get proxy info")
                completionHandler(error)
                exit(1)
            }
        }
    }
    
    func setupWormhole() {
        self.wormhole = MMWormhole.init(applicationGroupIdentifier: App.sharedGroupIdentifier(), optionalDirectory: "wormhole")
        
        self.wormhole.listenForMessage(withIdentifier: "getTunnelStatus") { (messageObject) in
            self.wormhole.passMessageObject("ok" as NSCoding?, identifier: "tunnelStatus")
        }
        
        self.wormhole.listenForMessage(withIdentifier: "stopTunnel") { (messageObject) in
            self.stop()
        }
        self.setupStatusSocket()
    }
    
    func setupStatusSocket() {
        self.statusSocket = GCDAsyncSocket.init(delegate: self, delegateQueue: DispatchQueue.global(qos: DispatchQoS.background.qosClass))
        
        do {
            try self.statusSocket.accept(onInterface: "127.0.0.1", port: 0)
            
            self.statusSocket .perform {
                let port = App.sockPort(self.statusSocket.socketFD())
                
                App.standardUserDefaults().set(port, forKey: "tunnelStatusPort");
                App.standardUserDefaults().synchronize()
            }
        } catch {
            
        }
    }
    
    func stop() {
        if enablePacketProcessing {
            interface.stop()
            interface = nil
            DNSServer.currentServer = nil
        }
        
        proxyServer.stop()
        proxyServer = nil
        RawSocketFactory.TunnelProvider = nil
        
        exit(EXIT_SUCCESS)
    }
    
    override func stopTunnel(with reason: NEProviderStopReason, completionHandler: @escaping () -> Void) {
        if self.forceStop == false {
            if enablePacketProcessing {
                interface.stop()
                interface = nil
                DNSServer.currentServer = nil
            }
            
            proxyServer.stop()
            proxyServer = nil
            RawSocketFactory.TunnelProvider = nil
            
            completionHandler()
            exit(EXIT_SUCCESS)
        } else {
            self.forceStop = false
            completionHandler()
        }
    }
    
    override func sleep(completionHandler: @escaping () -> Void) {
        completionHandler()
    }
    
    override func wake() {
    }
    
    override func handleAppMessage(_ messageData: Data, completionHandler: ((Data?) -> Void)? = nil) {
        if completionHandler != nil {
            completionHandler!(nil)
        }
    }
    
    func socket(_ sock: GCDAsyncSocket, didAcceptNewSocket newSocket: GCDAsyncSocket) {
        statusClientSocket = newSocket
    }
}

does this help? :D

**Comment by itskeKs** [comment]
- (void)startVPNWithOptions:(NSDictionary*)options handler:(void(^)(NETunnelProviderManager*, NSError*))handler {
    [self loadAndCreateProviderManager:^(NETunnelProviderManager *manager, NSError *error) {
        if (error != nil) {
            handler(nil, error);
        } else {
            if (manager == nil) {
                handler(nil, [NSError errorWithDomain:kAppBaseErrorDomain code:500 userInfo:@{NSLocalizedDescriptionKey: @"Invalid Provider"}]);
                return;
            } else {
                if (manager.connection.status == NEVPNStatusDisconnected || manager.connection.status == NEVPNStatusInvalid) {
                    NSError *returnError = nil;
                    [manager.connection startVPNTunnelWithOptions:options andReturnError:&returnError];
                    if (returnError == nil) {
                        [self addVPNStatusObserver];
                        handler(manager, nil);
                    } else {
                        handler(manager, returnError);
                    }
                } else {
                    [self addVPNStatusObserver];
                    handler(manager, nil);
                }
            }
        }
    }];
}

**Comment by zhuhaow** [comment]
Whatever is wrong with PAC has nothing to do with NEKit.

**Comment by itskeKs** [comment]
ok :(

**Comment by itskeKs** [comment]
@zhuhaow which remote SS version does NEKit support? i am using ss 2.9.1 i think the issue might be here.

**Comment by zhuhaow** [comment]
Don't know. 
If you can successfully connect to one host through ss proxy I don't think a lot simultaneous connections would make any difference.
