### ISSUE TITLE
Crash in tcp_recv_func when buf is NULL

### ISSUE THREAD

**Issue by JayZhao** [zhuhaow/NEKit#64]
Crash context:

I was debugging Speche using the lastest commit of NEKit.
The crash happened when a 40 bytes tcp packet was received. **TCP_EVENT_CLOSED** was sending a NULL buf parameter to **tcp_recv_func**.

<img width="567" alt="screen shot 2017-03-05 at 23 29 58" src="https://cloud.githubusercontent.com/assets/2278174/23588698/2983afda-01fc-11e7-9ca6-62f6908453d3.png">
<img width="1792" alt="screen shot 2017-03-05 at 23 31 01" src="https://cloud.githubusercontent.com/assets/2278174/23588697/298291fe-01fc-11e7-96be-0da4c1ba99c7.png">

**Comment by chenyihu** [comment]
A temp workaround:

in Cartfile
```
github "zhuhaow/tun2socks" "master"
```

**Comment by wangjinwei0806** [comment]
啥时候能修复好

**Comment by allenwong** [comment]
Any update of this issue?

**Comment by keepyounger** [comment]
+1
