### ISSUE TITLE
iOS packet tunnel provider app extension connection lost

### ISSUE THREAD

**Issue by albertolalama** [zhuhaow/NEKit#70]
I was attempting to use the NEKit framework on an iOS packet tunnel provider app extension, when I ran into this issue. Without the framework, the extension successfully sets up a VPN. When the framework gets added the extension fails to start with the following error:
```
(pkd) <Info>: match returned 1 plug-ins
(Foundation)<Notice>: calling plugIn beginUsing:
(PlugInKit)<Info>: preparing plug-in <private>(<private>)
(PlugInKit)<Notice>: connection to plug-in <private>(847142BB-09E8-4A9A-A342-898C649B6A32) lost
(PlugInKit)<Error>: Hub connection error Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named 
(PlugInKit)<Info>: beginUsing of 847142BB-09E8-4A9A-A342-898C649B6A32 concludes with error=Error Domain=NSCocoaErrorDomain Code=4097 "connection 
(Foundation)<Notice>: PlugInKit error in beginUsing:
(NetworkExtension)<Error>: Failed to start extension org.xxx.yyy.extension: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named org.xxx.yyy.extension" UserInfo={NSDebugDescription=connection to service named org.xxx.yyy.extension}
(Foundation)<Notice>: killing invalid plugIn
```
To reproduce, it is only necessary to link the framework and import it on a working packet tunnel provider extension.

Seems like, most likely, the [memory](https://forums.developer.apple.com/thread/73148) [limit](http://www.openradar.me/27660401) for network extensions could be affecting NEKit. No crash reports are available in the device logs.

**Comment by albertolalama** [comment]
Tested on iOS 10.0 and 10.2.1, using XCode 8.2.1

**Comment by zhuhaow** [comment]
I think any wrong configuration that prohibits the start of the extension would yield the same error. Maybe you forgot to link some frameworks in extension.

**Comment by albertolalama** [comment]
You are absolutely right, there were some missing dependencies.
I was thrown off by the lack of a crash report.

**Comment by mcfedr** [comment]
I see this error from time to time, 90% of the time tunnel is working just fine, and then it will just randomly stop working at some point

**Comment by zkh90644** [comment]
@albertolalama can you tell me what dependence you missing? I get the same problem!

**Comment by zkh90644** [comment]
I solved the problem by add link all framework to the extension. THX @zhuhaow  so much
