### ISSUE TITLE
Got a crash when integrating to my app with Carthage 

### ISSUE THREAD

**Issue by sidan5** [zhuhaow/NEKit#71]
I've built everything with Carthage following instructions and everything looked green. but when I add all frameworks to my project (through "Linked Frameworks and Libraries" under "General") when I run the app it just crashed. When removing that it runs as it should be.

My project is ObjectiveC one and I'm using latest Xcode (8.3). Is there anything I'm missing?

**Comment by zhuhaow** [comment]
First I don't think the objective-c is supported out of box since I do not bridge any methods from Swift.

The crash usually means you are not linking everything needed.

**Comment by sidan5** [comment]
I've added all the frameworks and NetworkExtension and it crash.
![screen shot 2017-03-30 at 17 07 36](https://cloud.githubusercontent.com/assets/1595490/24508222/76482e4a-156b-11e7-8bea-b1098fdc190b.png)

I'll try with a pure swift project.

**Comment by sidan5** [comment]
@zhuhaow Get a linker issue when using pure swift project. I'm clueless... :(

Any working demo using NEKit on iOS?

**Comment by zhuhaow** [comment]
No, but I think just change the target of Specht from x64 to arm should do it

**Comment by sidan5** [comment]
@zhuhaow Just added the frameworks to "Embedded Binary" and it solved the crash (instructions own Carthage says to add only to Linked Frameworks").

I'll try Specht. Thanks!
![screen shot 2017-03-30 at 17 22 39](https://cloud.githubusercontent.com/assets/1595490/24508926/a754b2fe-156d-11e7-9341-a9ff512a0dd7.png)
