### ISSUE TITLE
Supporting ObjectiveC Projects

### ISSUE THREAD

**Issue by sidan5** [zhuhaow/NEKit#72]
Do you plan to support ObjectiveC projects (add relevant bridges)?

Thanks!

**Comment by zhuhaow** [comment]
Yes and no.
NEKit will never support Objective-C
But if libnekit is ready, then objective-c can direct call the c interface.

**Comment by sidan5** [comment]
I meant linking it into objectiveC code out of the box...

**Comment by zhuhaow** [comment]
You can call c in objective-c out of box

> 在 2017年3月30日，22:11，Zhuhao Wang <zhuhaow@gmail.com> 写道：
> 
> ObjectiveC

**Comment by facudy** [comment]
May I know the predict release date of the libnekit？thanks

**Comment by zhuhaow** [comment]
There is no estimation yet.
