### ISSUE TITLE
Any updates to TUNInterface?

### ISSUE THREAD

**Issue by immzz** [zhuhaow/NEKit#74]
First of all, thanks for writing this wonderful library. I'm trying out all the features of the library and noticed that you mentioned TUNInterface is not available at the moment. I was wondering if you have a schedule on when it will be fixed, or would you fix it in libnekit?

Thanks!

**Comment by zhuhaow** [comment]
It will only be fixed in libnekit, and there is no schedule.  But you may assume it won't be long.

**Comment by immzz** [comment]
Cool, thanks for all the efforts!
