### ISSUE TITLE
proxy make chrome open some url ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by 312362115** [zhuhaow/NEKit#75]
baidu image

**Comment by zhuhaow** [comment]
无法重现。
不求多详细（系统，浏览器版本，spechtlite是不是最新），好歹也给个链接吧。

**Comment by 312362115** [comment]
我换了个电脑也重现不了了, 昨天是联通宽带, DNS 114, 最新版chrome, 最新版SpechtLite, 代理直连, 百度的图片列表正常, 详情页打不开.

**Comment by 312362115** [comment]
关掉代理打开就正常

**Comment by ptandDev** [comment]
нихера не понятно
