### ISSUE TITLE
a cache for recent matched rules

### ISSUE THREAD

**Issue by singular78** [zhuhaow/NEKit#78]
Url requests have good temporary locality, so a cache of rules can improve the performance of rule matching. I suggest to use a dict of DOMAIN rules as the cache for buffering the recent matched rules of url requests, because the dict structure is usually an hash table and the time complexity of the search dictionary is O(1). In a short time, only the first time of every different request is time-consuming even if there is not a complete rule list.
Thank you !

**Comment by zhuhaow** [comment]
LRU should be a good choice, though I'm not going to maintain NEKit anymore. Rule cache will definitely be implemented in libnekit.
