### ISSUE TITLE
关于nekit打包 90206  90205 和 CFBundleShortVersionString 解决办法

### ISSUE THREAD

**Issue by aishuidedabai** [zhuhaow/NEKit#79]
90206  90205 解决办法是在tunl 的 build phases的 run scrip 里面 删掉copy framwork。在主程序里面添加run script，copy framwork

  CFBundleShortVersionString 解决办法是全局搜索 CFBundleShortVersionString 然后更换为1.0.1这种三位的id

**Comment by aishuidedabai** [comment]
defaults write "$PWD/Carthage/Build/iOS/NEKit.framework/Info.plist" CFBundleShortVersionString 0.2.0
defaults write "$PWD/Carthage/Build/iOS/NEKit.framework.dSYM/Contents/Info.plist" CFBundleShortVersionString 0.2.0

**Comment by gowinder** [comment]
I delete the run script get git version in the build phases then ok

**Comment by Jiar** [comment]
这个 `Set version number script`同时会导致 `ERROR ITMS-90060` 错误，使得无法提交到`itunesconnect`，建议删除这个 `script`

**Comment by zhuhaow** [comment]
版本在我这里完全没问题，你们可以看一下github release里面的编译好的framework，版本是正确的。
