### ISSUE TITLE
Reject rule takes too many time

### ISSUE THREAD

**Issue by devstar1988** [zhuhaow/NEKit#82]
Hello

I am now trying to use this framework.
Btw, when i use reject rule for blocking some hosts, it takes too many time.

Specially, Youtube video loading is very slow.
Can you investigate about this?

**Comment by zhuhaow** [comment]
Try if you can reproduce this with Chrome

**Comment by devstar1988** [comment]
Yes, I can reproduce this with Chrome also.

Specially, when I browse sites with many advertisement, it takes too many time.

**Comment by devstar1988** [comment]
let rejectAdapterFactory = RejectAdapterFactory(delay: 300)

Reject has delay for 300 ms.
Is this wrong?

I referenced Specht project.

**Comment by zhuhaow** [comment]
Take a look at how things are loaded in developer tools

**Comment by devstar1988** [comment]
mathid.mathtag.com
bid.contextweb.com
adserver-us.adtech.
ib.adnxs.com
com.googletagservi..
s.komoona.com
as.casalemedia.com
ap.lijit.com
media.msg.dotomi.com
www.google-analytics.
googleads.g.doubleclick

These are blocked by reject rules. but site loading is delayed.

**Comment by devstar1988** [comment]
These are from "whatismyipaddress.com".

**Comment by zhuhaow** [comment]
How are things loaded?

**Comment by devstar1988** [comment]
I added this domains in reject rule, so those are blocked.
Site is loaded completely, but it still shows progress bar.

**Comment by zhuhaow** [comment]
Then what is still loading?

**Comment by devstar1988** [comment]
Not loading, but just show progress bar only.
Site is successfully loaded.

I think that progress bar counts total page vs loaded page.
But, reject adapter disconnects hosts contained in reject rule.

So, progress bar may not count blocked pages and shows it still not loaded.

I think that you have to block hosts contained in reject list, just return http code 200 with empty page like Potatso.

**Comment by itskeKs** [comment]
they will be delayed since ads nowadays are loaded through https. this will end up in certificate errors and resultbin depayed loafing times. thats why dns adblocking like pihole are useless. i guess these reject rules are also somekind of dns redirects to localhost?!

**Comment by zhuhaow** [comment]
No, the connection is just closed.

Zhuhao Wang

**Comment by devstar1988** [comment]
Yes,

Because connection is closed, browser will not count that page was not loaded.
So, progress bar will show that site is still loading even though site was loaded completely.

**Comment by devstar1988** [comment]
override public func openSocketWith(session: ConnectSession) {
        super.openSocketWith(session: session)
        
        QueueFactory.getQueue().asyncAfter(deadline: DispatchTime.now() + DispatchTimeInterval.milliseconds(delay)) {
            [weak self] in
            self?.disconnect()
        }
    }

Here

self?.disconnect()

I think that it should not be.

self?.didRead(data, ...)

data will be HTTP response with code 200, empty page.
This will help something?

**Comment by devstar1988** [comment]
Hello, no have solution?
