### ISSUE TITLE
The master branch build fail with swift 3.0.1 

### ISSUE THREAD

**Issue by xuzhiming** [zhuhaow/NEKit#83]
![image](https://cloud.githubusercontent.com/assets/1172124/26610969/86610ac0-45dd-11e7-945f-dbfe488a15cf.png)

I got the above compile error when use this command to build the NEKit

```
carthage update --no-use-binaries --platform ios
```
I wonder if this is a syntax error or my swift version is not compatible with this branch?
Could someone help me to figure out how to compile success on Swift 3.0.1 ?
PS: My Xcode version is 8.1.
Thanks so much.

**Comment by zhuhaow** [comment]
Either you upgrade to the latest Xcode or fix the code yourself, the error should be very clear.

**Comment by xuzhiming** [comment]
OK, I checked the travis.yml, the Xcode 8.2 or greater should compatible with this branch?

**Comment by zhuhaow** [comment]
Not sure, you can try.

**Comment by xuzhiming** [comment]
@zhuhaow I'll try and post the result here later.

**Comment by xuzhiming** [comment]
@zhuhaow After upgrade to Xcode 8.2.1, the ios sdk version should be 10.2, but the compile error below show that the sdk version is 10.1, very weird.
![image](https://cloud.githubusercontent.com/assets/1172124/26619336/9a09a5c2-4610-11e7-9269-2ce25594ad46.png)

 Meanwhile the other dependencies' build is passed and the sdk version is exact 10.2.

**Comment by zhuhaow** [comment]
Delete everything in Carthage/ and recompile all framework

**Comment by xuzhiming** [comment]
@zhuhaow It worked, thanks very much.
