### ISSUE TITLE
ipv6 Support

### ISSUE THREAD

**Issue by itskeKs** [zhuhaow/NEKit#86]
hey,

is there any chance i can get ipv6 running?

best,

keKs

**Comment by zhuhaow** [comment]
What part of IPv6 is not working for you?
As long as you don't use TUN, IPv6 should be just fine.

**Comment by itskeKs** [comment]
every request on the server within shadowsocks is getting resolved by googles ipv4 dns even though the request comes from an ipv6 address.

**Comment by zhuhaow** [comment]
It has nothing to do with NEKit, no matter what I do, how shadowsocks wants to resolve domain is not in my control. 

You may some misunderstandings about networking and how everything works.

**Comment by itskeKs** [comment]
the internal proxy within NEKit is started on ipv4 ip. when i try to start it on ::1 it just does not connect anywhere.

**Comment by zhuhaow** [comment]
Listen on IPv6 address should be fine as long as you adapter have IPv6 enabled.

I’m not sure why you are so confident that how you connect to local proxy server will have anything to do with how ss server resolves domain. But it has nothing to do with it, not even remotely.

**Comment by itskeKs** [comment]
i am on an ipv6 cellular network. so thats where the troubles start. i am also using a pac (proxy autoconfig file) with nekit. so there is only a problem when i use the pac file but it only appears when i use it with nekit. what it does: mail app stops working after some time. mostly when i switch ip version protocols from ipv4 (home network) to ipv6. and when mail app stops working some other ios services do so too, like appstore does not work anymore.

**Comment by zhuhaow** [comment]
Mail app does not follow pac config, so there won't be a problem.

Not sure what's wrong when network switches.

**Comment by itskeKs** [comment]
actually it does. when i use pac from url it requests file from webserver. i am also not sure what is causing the issue but it is somehow relatedto pac and ipv4 to ipv6 switch.

**Comment by zhuhaow** [comment]
Because the when mail loads content from URL it still uses pac.

Actually, I don't understand why you want to set the proxy server to `::1`, you can just use `0.0.0.0`.

**Comment by itskeKs** [comment]
within nekit internal proxy is set to 127.0.0.1 on port 9090 (at least within my code) this proxy redirects http(s) traffic to remote SS (as i understand it) so when i set it to 0.0.0.0 where will the traffic go?!

**Comment by zhuhaow** [comment]
Uh, just keep it as `127.0.0.1`, do not use `0.0.0.0`.

`0.0.0.0` will allow connection from anywhere. `127.0.0.1` only accepts connection from loopback device (which means the same device).

**Comment by itskeKs** [comment]
btw. how do i know if my ios device has ipv6 enabled?!

at least i can try 0.0.0.0 maybe that will help.

**Comment by zhuhaow** [comment]
127.0.0.1 and ::1 should make no difference no matter when. You need to understand you are connecting to local proxy by loopback device, not wifi or cellular.

**Comment by itskeKs** [comment]
yes i get it :) that furst it goes to local proxy running on my device and from there it goes to remote SS server.

is there an exception for the loopback device? so it wont go through proxy?

**Comment by zhuhaow** [comment]
Not likely. I don’t even understand why you want to change it to ::1. You probably are the first one do that.

**Comment by zhuhaow** [comment]
There is an issue with IPv6 i just found (#87). But a little hassle to fix. 

The fundamental problem is that the dns resolve only uses the `A` response as of now. To solve it, we have to handle some fallbacks (DNS `AAAA` lookup and reconnect).

Sorry there won't be a fix for pure IPv6 environment soon.

**Comment by itskeKs** [comment]
@zhuhaow any news about ipv6? :)

**Comment by zhuhaow** [comment]
No. 

I'm working on https://github.com/zhuhaow/freighter, but rust async api seems will never get to stable so the dependencies are not really playing well with each other. It won't be ready any time soon.

As for the ipv6 support, I still don't get why you want to choose the ip protocol connecting to localhost, it should make no difference, and if `localhost` works, use it.
