### ISSUE TITLE
我的工程无法集成

### ISSUE THREAD

**Issue by Sky891028** [zhuhaow/NEKit#89]
master会遇到下面的错误 
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/xxx/ios/Carthage/Checkouts/MMDB-Swift/MMDB.xcodeproj -scheme MMDB-iOS -configuration Release -derivedDataPath /Users/xxx/Library/Caches/org.carthage.CarthageKit/DerivedData/MMDB-Swift/0.2.6 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/cs/x8h6k7j1227dkr9lksppcrq80000gn/T/carthage-xcodebuild.Id3UsM.log

** BUILD FAILED **

The following build commandss failed:
	CpResource MMDB/GeoLite2-Country.mmdb /Users/xxx/Library/Caches/org.carthage.CarthageKit/DerivedData/MMDB-Swift/0.2.6/Build/Products/Release-iphoneos/MMDB.framework/GeoLite2-Country.mmdb
(1 failure)

0.11.1分支集成成功 但是运行会遇到以下问题 
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/xxx/Library/Developer/CoreSimulator/Devices/EC695CF5-8D02-46C9-A3C4-2364B3E68768/data/Containers/Bundle/Application/DF6D0453-1356-4B0E-B27C-FA4419F6F4C7/flysoVPN.app/Frameworks/Yaml.framework/Yaml
  Reason: image not found

**Comment by zhuhaow** [comment]
`Carthage/Checkouts/MMDB-Swift/MMDB` 下面有 `GeoLite2-Country.mmdb`么？
没有删了整个carthage目录重新跑。

image not found是因为framework没有embed。

**Comment by hoorace** [comment]
you need to `cd Carthage/Checkouts/MMDB-Swift/` , and run 
`sh update_database.sh `
you will see GeoLite2-Country.mmdb file in ./MMDB

**Comment by zhuhaow** [comment]
@hoorace There is no need to do that manually.

**Comment by hoorace** [comment]
@zhuhaow perhaps, if curl has timeout error when download GeoLite2-Country.mmdb, and MMDB-Swift framework has not check and download it again .

**Comment by zhuhaow** [comment]
@hoorace That's possible. In that case you have to download it yourself.

**Comment by hoorace** [comment]
@Sky891028 so that's a bug of MMDB-Swift framework, you need take new issue to `https://github.com/lexrus/MMDB-Swift`.

**Comment by LeonHwa** [comment]
I have a problem like this

**Comment by zhuhaow** [comment]
@hoorace That's not a bug of the project but a bug of you network.

**Comment by zhuhaow** [comment]
This bug is fixed in the latest version. Sorry for the inconvenience.

**Comment by Sky891028** [comment]
Tks 
one more things , i want Integration by OC project 
- Hook 1 (expr -- @import UIKit)

- Hook 2 (target stop-hook disable)
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/Sky/Library/Developer/CoreSimulator/Devices/EC695CF5-8D02-46C9-A3C4-2364B3E68768/data/Containers/Bundle/Application/A125F8ED-6F80-4529-9640-4DB8B43BEDE1/flysoVPN.app/Frameworks/Yaml.framework/Yaml
  Reason: image not found

**Comment by zhuhaow** [comment]
It is usually because you does not copy the framework to the correct place so it is not found.

**Comment by scymen** [comment]
1. carthage 编译出错，查看日志，如果是（一般是这个问题）发现无法下载 GeoLite2-Country.mmdb ，我的解决办法是把项目 MMDB-Swift里的 update_database.sh ,修改下载方式为 wget (默认是 curl)，修改后再编译时，就不要再 update了

2.dyld: Library not loaded.
把所有 carthage 编译出来的 *.framework 都拖到 link frameworks and libraries。并在 build phases 里添加 carthage 的复制脚本，复制所有的 *.framework
