### ISSUE TITLE
carthage build failed on MMDB-iOS

### ISSUE THREAD

**Issue by Jiar** [zhuhaow/NEKit#91]
```
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/jiar/Desktop/iOS_Self/Link/Link/Carthage/Checkouts/MMDB-Swift/MMDB.xcodeproj -scheme MMDB-iOS -configuration Release -derivedDataPath /Users/jiar/Library/Caches/org.carthage.CarthageKit/DerivedData/MMDB-Swift/0.2.6 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build
```

**Comment by zhuhaow** [comment]
Everything is working just fine. Make sure you have internet access.

**Comment by Jiar** [comment]
[MMDB-Swift issues 8](https://github.com/lexrus/MMDB-Swift/issues/8)

**Comment by zhuhaow** [comment]
Fixed.

**Comment by wangxuewen** [comment]
You can switch the network, try it a few more times, wifi should not work, 4G should try a few more times.

**Comment by Joeeyy** [comment]
查看日志，是网络的问题。
/Users/yourname/Carthage/Checkouts/MMDB-Swift/update_database.sh脚本里有命令
`curl -L -o $tmpfile http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz`，我是在这里卡住了
