### ISSUE TITLE
reject  RejectAdapterFactory

### ISSUE THREAD

**Issue by LJjack** [zhuhaow/NEKit#92]
已经添加reject  t7z.cupid.iqiyi.com，但是还是会加载。
![55c1dda4-6e71-4122-8467-a655612794c4](https://user-images.githubusercontent.com/9940239/28013560-07120efc-659c-11e7-9ad7-81b0d53d85a2.png)
能否指点一下，谢谢

**Comment by zhuhaow** [comment]
看不出，不是都disconnect了

**Comment by LJjack** [comment]
但是还是加载了，是不是通过什么方法绕过VPN了

**Comment by zhuhaow** [comment]
如果你只是设了个代理，有可能软件决定绕过代理

**Comment by LJjack** [comment]
可能，我写了一个网络请求例子测试一下，发现可以阻止请求。谢谢

**Comment by zhuhaow** [comment]
？

**Comment by LJjack** [comment]
有没有办法软件决定绕过代理，还有在RejectAdapter 中
override public func openSocketWith(session: ConnectSession) {
        super.openSocketWith(session: session)

        QueueFactory.getQueue().asyncAfter(deadline: DispatchTime.now() + DispatchTimeInterval.milliseconds(delay)) {
            [weak self] in
            self?.disconnect()
        }
    }
能够改正返回一个自定义HTTP的响应吗？

**Comment by zhuhaow** [comment]
只有全局的tun了

你可以自己改
