### ISSUE TITLE
(Crashes) Hard to debug 

### ISSUE THREAD

**Issue by CAP-ONE** [zhuhaow/NEKit#95]
Hello,
I keep having crashes when I want to start a VPN Tunnel, but as I can't print the app extension log on the Xcode console, i'm viewing them from the device logs, and, they aren't explicit at all when it come to error messages.  And I'm fairly new to iOS development so I'm quite lost when it comes to reviewing logs. So if someone is kind enough to tell me what's going on here, I'll be very grateful. Thanks !

Those are the logs right after I started the VPN : 

> Jul 11 17:38:38 iPhone-4 VPN[214] <Warning>: Init test...
Jul 11 17:38:38 iPhone-4 VPN[214] <Warning>: Starting PacketTunnel...
Jul 11 17:38:38 iPhone-4 configd[30] <Notice>: network changed
Jul 11 17:38:39 iPhone-4 configd[30] <Notice>: network changed: v4(utun0+:192.169.89.1, en0) DNS! Proxy!
Jul 11 17:38:39 iPhone-4 networkd[84] <Error>: __42-[NETClientConnection evaluateNetworkPath]_block_invoke apsd.85 connection 18: trigger network agents (<NULL>) error Error Domain=NWPathEvaluatorErrorDomain Code=1 "(null)"
Jul 11 17:38:39 iPhone-4 VPN[214] <Warning>: Set tunnel network settings
Jul 11 17:38:39 iPhone-4 VPN[214] <Warning>: Began tunneling session
Jul 11 17:38:39 iPhone-4 VPN[214] <Warning>: Proxy server <GCDHTTPProxyServer address:Optional(127.0.0.1) port:<Port 9090>> started.
Jul 11 17:38:39 iPhone-4 nesessionmanager[190] <Notice>: NESMVPNSession[ProxyPony VPN:77E47F63-1A69-4A23-8541-5F73767C9382]: status changed to connected
Jul 11 17:38:39 iPhone-4 VPN[214] <Warning>: start interface
Jul 11 17:38:39 iPhone-4 nehelper[95] <Error>: Configuration for provider com.apple.NetworkExtension.NetworkServiceProxy does not exist (<__NSConcreteUUID 0x14d22a10> 8E61F56F-54AB-46C7-9ECE-7E2D54810C2B) or is not enabled (0)
Jul 11 17:38:39 iPhone-4 UserEventAgent[23] <Error>: Report metrics message failed
Jul 11 17:38:39 iPhone-4 MobileMail[148] <Notice>: LogOther <t:0x14e54ce0> ERROR: MFMessageErrorDomain/No Delivery Accounts Configured - Ce compte est inactif. Vérifiez les réglages dans Réglages > Mail, Contacts, Calendrier.
Jul 11 17:38:39 iPhone-4 VPN[214] <Warning>: Proxy socket <HTTPProxySocket host:init-p01st.push.apple.com port: 80)> received request <ConnectSession host:init-p01st.push.apple.com port:80>.
Jul 11 17:38:39 iPhone-4 VPN[214] <Warning>: Rule <AllRule> matched session <ConnectSession host:init-p01st.push.apple.com port:80>.
Jul 11 17:38:39 iPhone-4 VPN[214] <Warning>: Adapter socket <HTTPAdapter host:init-p01st.push.apple.com port:80)> connected to remote.
Jul 11 17:38:40 iPhone-4 nehelper[95] <Error>: Configuration for provider com.apple.NetworkExtension.NetworkServiceProxy does not exist (<__NSConcreteUUID 0x14d22a10> 8E61F56F-54AB-46C7-9ECE-7E2D54810C2B) or is not enabled (0)
Jul 11 17:38:40 iPhone-4 UserEventAgent[23] <Error>: Report metrics message failed
Jul 11 17:38:40 iPhone-4 MobileMail[148] <Notice>: LogOther <t:0x14e54ce0> ERROR: MFMessageErrorDomain/No Delivery Accounts Configured - Ce compte est inactif. Vérifiez les réglages dans Réglages > Mail, Contacts, Calendrier.
Jul 11 17:38:40 iPhone-4 networkd[84] <Error>: -[NETProxyLookup url] invalid URL scheme '5223'
Jul 11 17:38:40 iPhone-4 assertiond[64] <Error>: assertion failed: 13G36: assertiond + 60233 [490D29F9-F790-3C02-B1F0-75F21A182589]: 0x3
Jul 11 17:38:40 iPhone-4 Unknown[64] <Error>: 
Jul 11 17:38:40 iPhone-4 nesessionmanager[190] <Notice>: NESMVPNSession[ProxyPony VPN:77E47F63-1A69-4A23-8541-5F73767C9382]: status changed to disconnecting
Jul 11 17:38:40 iPhone-4 neagent[191] <Warning>: plugin fr.evina.proxypony.VPN interrupted
Jul 11 17:38:40 iPhone-4 neagent[191] <Error>: Extension fr.evina.proxypony.VPN died unexpectedly
Jul 11 17:38:40 iPhone-4 neagent[191] <Warning>: plugin fr.evina.proxypony.VPN invalidated
Jul 11 17:38:40 iPhone-4 networkd[84] <Error>: __42-[NETClientConnection evaluateNetworkPath]_block_invoke apsd.85 connection 20: trigger network agents (<NULL>) error Error Domain=NWPathEvaluatorErrorDomain Code=1 "(null)"
Jul 11 17:38:40 iPhone-4 configd[30] <Notice>: network changed: v4(en0:192.168.43.167) DNS! Proxy!
Jul 11 17:38:40 iPhone-4 com.apple.xpc.launchd[1] (fr.evina.proxypony.VPN[214]) <Notice>: Service exited due to signal: Trace/BPT trap: 5
Jul 11 17:38:40 iPhone-4 nehelper[95] <Error>: Configuration for provider com.apple.NetworkExtension.NetworkServiceProxy does not exist (<__NSConcreteUUID 0x14d22a10> 8E61F56F-54AB-46C7-9ECE-7E2D54810C2B) or is not enabled (0)
Jul 11 17:38:41 iPhone-4 UserEventAgent[23] <Error>: Report metrics message failed
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Error>: assertion failed: 13G36: libsystem_trace.dylib + 15927 [E82A6F2D-873A-39AD-8014-EDEB52248157]: 0x0
Jul 11 17:38:41 iPhone-4 Unknown[215] <Error>: 
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Warning>: os_activity_diagnostic_for_pid() failed!
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Notice>: Formulating report for corpse[214] VPN
Jul 11 17:38:41 iPhone-4 kernel[0] <Notice>: SIOCPROTODETACH_IN6: utun0 error=6
Jul 11 17:38:41 iPhone-4 nesessionmanager[190] <Error>: SIOCGIFMTU failed: Device not configured
Jul 11 17:38:41 iPhone-4 nesessionmanager[190] <Error>: NEVirtualInterfaceAdjustReadBufferSize: interface_get_mtu failed (6), defaulting to max mtu
Jul 11 17:38:41 iPhone-4 nesessionmanager[190] <Notice>: NESMVPNSession[ProxyPony VPN:77E47F63-1A69-4A23-8541-5F73767C9382]: status changed to disconnected, last stop reason Plugin failed
Jul 11 17:38:41 iPhone-4 configd[30] <Notice>: network changed
Jul 11 17:38:41 iPhone-4 symptomsd[106] <Error>: nw_interface_get_agents SIOCGIFAGENTIDS failed for interface "utun0" (index 9, type other): [6] Device not configured
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Warning>: Report of type '109(109_VPN)' not saved because the limit of 25 logs has been reached
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Error>: Notice: This report is abbreviated for syslog inclusion because it could not be saved to disk.
	Symbolication may be possible by manually cleaning up and including the Binary Image section of a full report from this same device -- good luck!
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Error>: Process:             VPN [214]
	Path:                /private/var/containers/Bundle/Application/D2530F64-35C4-460C-9714-8F5BF9D823F4/ProxyPony.app/PlugIns/VPN.appex/VPN
	OS Version:          iOS 9.3.5 (13G36)
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Error>: Exception Type:  EXC_BREAKPOINT (SIGTRAP)
	Exception Codes: 0x0000000000000001, 0x00000000e7ffdefe
	Triggered by Thread:  1
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Error>: Thread 0 name:  Dispatch queue: com.apple.main-thread
	Thread 0:
	0   libsystem_kernel.dylib        	0x241ae8d0 0x241ae000 + 2256
	1   libsystem_kernel.dylib        	0x241ae6d4 0x241ae000 + 1748
	2   CoreFoundation                	0x244f9ac4 0x2443e000 + 768708
	3   CoreFoundation                	0x244f7e4c 0x2443e000 + 761420
	4   CoreFoundation                	0x24447228 0x2443e000 + 37416
	5   CoreFoundation                	0x24447014 0x2443e000 + 36884
	6   Foundation                    	0x24c90044 0x24c85000 + 45124
	7   Foundation                    	0x24cdea4c 0x24c85000 + 367180
	8   libxpc.dylib                  	0x24291020 0x24284000 + 53280
	9   libxpc.dylib                  	0x24292734 0x24284000 + 59188
	10  Foundation                    	0x24e38794 0x24c85000 + 1783700
	11  PlugInKit                     	0x2a9c212c 0x2a9b5000 + 53548
	12  PlugInKit                     	0x2a9c1dfa 0x2a9b5000 + 52730
	13  PlugInKit                     	0x2a9c2160 0x2a9b5000 + 53600
	14  libextension.dylib            	0x24c777cc 0x24c64000 + 79820
	15  libdyld.dylib                 	0x240ef872 0x240ed000 + 10354
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Error>: Thread 1 name:  Dispatch queue: NEKit.ProcessingQueue
	Thread 1 Crashed:
	0   tun2socks                     	0x009dcc90 0x9d3000 + 40080
	1   tun2socks                     	0x009dccf0 0x9d3000 + 40176
	2   tun2socks                     	0x009d9240 0x9d3000 + 25152
	3   lwip                          	0x00a1a5f0 0xa13000 + 30192
	4   lwip                          	0x00a18018 0xa13000 + 20504
	5   tun2socks                     	0x009d96a4 0x9d3000 + 26276
	6   NEKit                         	0x00203f8c 0x1c3000 + 266124
	7   NEKit                         	0x001ccc64 0x1c3000 + 40036
	8   NEKit                         	0x00215388 0x1c3000 + 336776
	9   NEKit                         	0x00215674 0x1c3000 + 337524
	10  libdispatch.dylib             	0x240a5822 0x240a3000 + 10274
	11  libdispatch.dylib             	0x240b2422 0x240a3000 + 62498
	12  libdispatch.dylib             	0x240b1a60 0x240a3000 + 60000
	13  libdispatch.dylib             	0x240b45e8 0x240a3000 + 71144
	14  libdispatch.dylib             	0x240b3fcc 0x240a3000 + 69580
	15  libsystem_pthread.dylib       	0x24269b28 0x24268000 + 6952
	16  libsystem_pthread.dylib       	0x24269718 0x24268000 + 5912
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Error>: Thread 2 name:  Dispatch queue: com.apple.libdispatch-manager
	Thread 2:
	0   libsystem_kernel.dylib        	0x241c42f8 0x241ae000 + 90872
	1   libdispatch.dylib             	0x240b9d60 0x240a3000 + 93536
	2   libdispatch.dylib             	0x240b9abe 0x240a3000 + 92862
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Error>: Thread 3:
	0   libsystem_kernel.dylib        	0x241c3864 0x241ae000 + 88164
	1   libsystem_pthread.dylib       	0x24269b34 0x24268000 + 6964
	2   libsystem_pthread.dylib       	0x24269718 0x24268000 + 5912
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Error>: Thread 4:
	0   libsystem_kernel.dylib        	0x241c3864 0x241ae000 + 88164
	1   libsystem_pthread.dylib       	0x24269b34 0x24268000 + 6964
	2   libsystem_pthread.dylib       	0x24269718 0x24268000 + 5912
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Error>: Thread 5:
	0   libsystem_kernel.dylib        	0x241c3864 0x241ae000 + 88164
	1   libsystem_pthread.dylib       	0x24269b34 0x24268000 + 6964
	2   libsystem_pthread.dylib       	0x24269718 0x24268000 + 5912
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Error>: Thread 6:
	0   libsystem_kernel.dylib        	0x241c3864 0x241ae000 + 88164
	1   libsystem_pthread.dylib       	0x24269b34 0x24268000 + 6964
	2   libsystem_pthread.dylib       	0x24269718 0x24268000 + 5912
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Error>: Thread 7:
	0   libsystem_kernel.dylib        	0x241c3864 0x241ae000 + 88164
	1   libsystem_pthread.dylib       	0x24269b34 0x24268000 + 6964
	2   libsystem_pthread.dylib       	0x24269718 0x24268000 + 5912
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Error>: Thread 1 crashed with ARM Thread State (32-bit):
	    r0: 0xffffffff    r1: 0x00000000      r2: 0x00000010      r3: 0x0000000c
	    r4: 0x17e7cbc0    r5: 0x17d66c50      r6: 0x17d5bab0      r7: 0x1f080d8c
	    r8: 0x17d66c50    r9: 0x010258bc     r10: 0x002a7bc4     r11: 0xc0797bc3
	    ip: 0x3ad78178    sp: 0x1f080d6c      lr: 0x009da9e4      pc: 0x009dcc90
	  cpsr: 0xa0000010
Jul 11 17:38:41 iPhone-4 ReportCrash[215] <Error>: Error Formulating Crash Report:
	Failed while requesting activity/breadcrumb diagnostics
Jul 11 17:38:57 iPhone-4 com.apple.CDScheduler[23] <Error>: Failed to read UserNextSleepPeriod from contextstore
Jul 11 17:38:57 iPhone-4 com.apple.CDScheduler[23] <Error>: Failed to get user inactivity forecast
Jul 11 17:38:57 iPhone-4 com.apple.CDScheduler[23] <Error>: AutoSu doesn't have any prediction yet
Jul 11 17:38:57 iPhone-4 com.apple.CDScheduler[23] <Error>: Failed to get device restart forecast
Jul 11 17:39:48 iPhone-4 networkd[84] <Error>: nw_interface_get_agents SIOCGIFAGENTIDS failed for interface "utun0" (index 9, type other): [6] Device not configured
Jul 11 17:39:49 iPhone-4 networkd[84] <Error>: nw_interface_get_agents SIOCGIFAGENTIDS failed for interface "utun0" (index 9, type other): [6] Device not configured
Jul 11 17:39:49 iPhone-4 nehelper[95] <Error>: Configuration for provider com.apple.NetworkExtension.NetworkServiceProxy does not exist (<__NSConcreteUUID 0x14d22a10> 8E61F56F-54AB-46C7-9ECE-7E2D54810C2B) or is not enabled (0)
Jul 11 17:39:49 iPhone-4 UserEventAgent[23] <Error>: Report metrics message failed
Jul 11 17:40:27 iPhone-4 ABLE[135] <Warning>: Current charge is 100.000000
Jul 11 17:44:00 iPhone-4 syslogd[22] <Notice>: ASL Sender Statistics

**Comment by CAP-ONE** [comment]
And those logs is when I'm retesting right after, and I'm ale to connect without any crashes : 

> Jul 11 17:55:06 iPhone-4 ProxyPony[209] <Notice>: The configuration was not saved because it was unchanged from the previously saved version
Jul 11 17:55:06 iPhone-4 syslogd[22] <Notice>: ASL Sender Statistics
Jul 11 17:55:06 iPhone-4 nesessionmanager[190] <Notice>: NESMVPNSession[ProxyPony VPN:77E47F63-1A69-4A23-8541-5F73767C9382]: Received a start command from ProxyPony[209]
Jul 11 17:55:06 iPhone-4 nesessionmanager[190] <Notice>: NESMVPNSession[ProxyPony VPN:77E47F63-1A69-4A23-8541-5F73767C9382]: status changed to connecting
Jul 11 17:55:06 iPhone-4 pkd[136] <Warning>: assigning plug-in fr.evina.proxypony.VPN(1.0) to plugin sandbox
Jul 11 17:55:06 iPhone-4 pkd[136] <Warning>: enabling pid=191 for plug-in fr.evina.proxypony.VPN(1.0) F70B11A8-AF64-473A-8A16-23065B1A9BCE /private/var/containers/Bundle/Application/D2530F64-35C4-460C-9714-8F5BF9D823F4/ProxyPony.app/PlugIns/VPN.appex
Jul 11 17:55:06 iPhone-4 kernel[0] <Notice>: xpcproxy[216] Container: /private/var/mobile/Containers/Data/PluginKitPlugin/51F0C60D-E541-4F88-8F61-1899D2E2CF24 (sandbox)
Jul 11 17:55:06 iPhone-4 com.apple.xpc.launchd[1] <Error>: assertion failed: 13G36: launchd + 85529 [083E000D-4C31-3B98-A2C4-6FADB4D1940F]: 0x3
Jul 11 17:55:06 iPhone-4 VPN[216] <Warning>: Init test...
Jul 11 17:55:06 iPhone-4 VPN[216] <Warning>: Starting PacketTunnel...
Jul 11 17:55:06 iPhone-4 configd[30] <Notice>: network changed
Jul 11 17:55:06 iPhone-4 configd[30] <Notice>: network changed: v4(utun0+:192.169.89.1, en0) DNS! Proxy!
Jul 11 17:55:07 iPhone-4 networkd[84] <Error>: -[NETProxyLookup url] invalid URL scheme '5223'
Jul 11 17:55:07 iPhone-4 networkd[84] <Error>: __42-[NETClientConnection evaluateNetworkPath]_block_invoke apsd.85 connection 22: trigger network agents (<NULL>) error Error Domain=NWPathEvaluatorErrorDomain Code=1 "(null)"
Jul 11 17:55:07 iPhone-4 apsd[85] <Error>: tcp_connection_handle_connect_conditions_bad 22 failed: 4 - Network Agent [domain: NetworkExtension, type: VPN, description: VPN: ProxyPony VPN, uuid: 02D88513-2CFB-4043-80CB-F2B694EAE587, flags: 1] is unsatisfied
Jul 11 17:55:07 iPhone-4 networkd[84] <Notice>: -[NETClientConnection effectiveBundleID] using process name apsd as bundle ID (this is expected for daemons without bundle ID
Jul 11 17:55:07 iPhone-4 VPN[216] <Warning>: Set tunnel network settings
Jul 11 17:55:07 iPhone-4 VPN[216] <Warning>: Began tunneling session
Jul 11 17:55:07 iPhone-4 VPN[216] <Warning>: Proxy server <GCDHTTPProxyServer address:Optional(127.0.0.1) port:<Port 9090>> started.
Jul 11 17:55:07 iPhone-4 nesessionmanager[190] <Notice>: NESMVPNSession[ProxyPony VPN:77E47F63-1A69-4A23-8541-5F73767C9382]: status changed to connected
Jul 11 17:55:07 iPhone-4 VPN[216] <Warning>: start interface
Jul 11 17:55:07 iPhone-4 nehelper[95] <Error>: Configuration for provider com.apple.NetworkExtension.NetworkServiceProxy does not exist (<__NSConcreteUUID 0x14d22a10> 8E61F56F-54AB-46C7-9ECE-7E2D54810C2B) or is not enabled (0)

**Comment by zhuhaow** [comment]
Hi, there has been report that there might be some errors in 32-bit system, I tried to fix some, but not sure if every issue is resolved. But that should not be a big problem since there won't be any issue hard to solve.

As for you question, since what you want is to route traffic to you http proxy, i think you may not need to enable TUN interface, just set `enablePacketProcessing` to `false` in the Specht demo. Of course, it depends on what you want to achieve. TUN support is not stable and you should expect it will crash.

The log info you provide is not quite informative, you should attach to you extension process to debug what is exactly wrong.

**Comment by CAP-ONE** [comment]
I'm using an iPhone 4 as a test device, I'll try on newer devices to see if the system is somewhat related too.

Also, you are saying I don't need to activate packet processing in order to redirect the traffic ? I haven't got the time yet to dive into the source code but, from what i understand, the TUN Interface take the packetFlow from the PacketTunnelProvider and resassemble TCP/UDP packets to send them to the remote server.

**Comment by zhuhaow** [comment]
You just need to set a proxy to get most traffic from apps using system API

**Comment by CAP-ONE** [comment]
What do you mean by "using system API" ? I have to set a global proxy yes, but it must work for either 4G/3G connection or Wifi. I've already done it on Android, the only way to do that is by opening a VPN connection on 127.0.0.1, that will then open a tun interface

**Comment by zhuhaow** [comment]
For most of the time a proxy is enough. The tun device is more like a mock device because you are not going to route anything to it. 

As for the system API, a just mean most apps are using system API and they will obey the proxy config automatically.

**Comment by CAP-ONE** [comment]
So in order to do what I want, the Network Extension APIs are not necessary ?  I googled a bit and most of the time they said i should set the proxy settings on the Wifi settings, or use Apple Configurator, and from this, setup Global HTTP Proxy with a .pac file, but all of this is a little confusing now. I'll do my research on my side to see if it is possible to configure all of that automatically, from my app, without user intervention.
Thanks

**Comment by zhuhaow** [comment]
Network extension is a must, you also need to set up a tun device with NE, but you do not need to route anything to tun device. Apart from tun device, you can set up the system to use proxy with NE

**Comment by CAP-ONE** [comment]
I've setted enablePacketProcessing to false, and this is working fine, i mean no crash, for now, but i'm a little confused, I must lack some knowledge but I don't know how without routting to tun we are able to get the packetFlow and all

**Comment by zhuhaow** [comment]
You don't get data from tun device. You get data from local proxy started with NEKit.

**Comment by CAP-ONE** [comment]
OKay, i guess my head is still stuck on how it worked on Android, but apparently thing are always different with iOS. 
Thanks for helping, this is a nice library, if I could contribute some how, it will be a pleasure. 
Also, just to know, there aren't any restriction from Apple regarding this library if I want to release the app on the App Store ?
