### ISSUE TITLE
您好,项目一开始可以出墙,打包在testfight使用一段时间后国内国外网都无法访问.

### ISSUE THREAD

**Issue by Zafirzzf** [zhuhaow/NEKit#96]
您好,集成NEKit写了一个VPN Demo,运行后可以翻墙.但这个应用打包在testfight测试的时候有的手机连接成功,状态栏也有VPN字样,但是国内国外网都无法访问,.或者是过一段时间出现这种问题.时间不固定.而且昨天测试又可以进行翻墙了.
       重新打包一个版本之后新版本又可以进行翻墙了.排除了SS账号的问题...
       求问这种不稳定性是什么原因呢?
       因为从工程直接真机测试一直都可以翻墙,实在定位不到问题所在.

**Comment by zhuhaow** [comment]
你有试过切换网络会有影响么

**Comment by Zafirzzf** [comment]
出现问题的时候4G和无线都会有这个问题..同样的网络环境新装一个打包的app又没问题了.

**Comment by zhuhaow** [comment]
切换网络会导致这个问题么

**Comment by Zafirzzf** [comment]
您好.刚试了一下,并不会导致这个问题.

**Comment by Zafirzzf** [comment]
您好我同事刚才又测了一下,他那边一开始运行时候wifi状态没有问题..然后切换到4G之后没有网了 ...现在它再次运行程序安装无线4G都没有网了....这是哪里造成的问题呢?

**Comment by zhuhaow** [comment]
那就不要route任何东西。重启程序都不能用的原因我就不知道了

**Comment by Sky891028** [comment]
检查dns

**Comment by zhaoyunyi** [comment]
我E也这样，iOS10.3.3 iphon 5S 连了之后内网和外网都访问不了，但是有几个机型和最新的IOS11 又是可以访问的
