### ISSUE TITLE
could you support AHEAD encryption method?

### ISSUE THREAD

**Issue by facudy** [zhuhaow/NEKit#98]
AHEAD  is now a popular encryption method for SS, would you please support it in NEKit?

**Comment by facudy** [comment]
sorry, it should be "AEAD"

**Comment by zhuhaow** [comment]
AEAD will only be provided through pull request by volunteers. I'm not going to add new feature to `NEKit`. Sorry.

**Comment by facudy** [comment]
Always expect for your new lib to have SSR feature and AEAD encryption,thank you
