### ISSUE TITLE
Lots of errors when submitting to App Store

### ISSUE THREAD

**Issue by CAP-ONE** [zhuhaow/NEKit#99]
When trying to submit my app to the App Store, I'm getting a lot of errors coming from NEKit and his libs, it also say it's trying to use Mac architecture even if I build for iOS, and executed the command `carthage update --no-use-binaries --platform ios` at the very start

Log summary : https://pastebin.com/06VXHE0N

**Comment by zhuhaow** [comment]
It has nothing to do with `NEKit` and everything to do with `Carthage`.

https://github.com/Carthage/Carthage/blob/master/README.md#if-youre-building-for-ios-tvos-or-watchos
